// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://audio-video-api.adobe.io' | (string & {});
};

/**
 * List of available voices.
 */
export type SuccessfulVoicesResponse = {
    voices?: Array<VoiceEntity>;
};

/**
 * Details of Voice Entity.
 */
export type VoiceEntity = {
    /**
     * The unique ID for the voice.
     */
    voiceId?: string;
    /**
     * The displayed name for the voice.
     */
    displayName?: string;
    /**
     * The gender of the voice.
     */
    gender?: string;
    /**
     * The speaking style of the voice.
     */
    style?: 'Casual' | 'Excited';
    /**
     * Not applicable at this time.
     */
    voiceType?: string;
    /**
     * This determines if the specific voice ID is available for use. Deprecated voices will have an Inactive status.
     */
    status?: 'Active' | 'Inactive';
    /**
     * This is a field for any additional properties for the voice.
     */
    extendedPropertyMap?: {
        [key: string]: unknown;
    };
    /**
     * The speed of speaking, in words per minute.
     */
    wordsPerMinute?: string;
    /**
     * Not applicable at this time.
     */
    rolePlayList?: Array<string>;
    /**
     * A pre-signed URL for downloading the sample audio.
     */
    sampleURL?: string;
};

/**
 * List of available avatars.
 */
export type SuccessfulAvatarsResponse = {
    avatars?: Array<AvatarEntity>;
};

/**
 * Details of the avatar entity.
 */
export type AvatarEntity = {
    /**
     * The unique ID for the avatar.
     */
    avatarId?: string;
    /**
     * The displayed name for the avatar.
     */
    displayName?: string;
    /**
     * The gender of the avatar.
     */
    gender?: string;
    /**
     * The clothing style worn by the avatar.
     */
    clothingStyle?: 'Casual' | 'Formal' | 'Professional';
    /**
     * The intended age bracket of the avatar.
     */
    ageGroup?: 'Young Adult' | 'Middle Aged' | 'Senior';
    /**
     * The ethnicity of the avatar.
     */
    ethnicity?: string;
    /**
     * This property is used when the avatar wears a professional or region-specific costume (like Nurse, Doctor, Emergency Worker, Retail Worker, etc.).
     */
    style?: string;
    /**
     * This determines if the specific avatar ID is available for use. Deprecated avatars will have an Inactive status.
     */
    status?: 'Active' | 'Inactive';
    /**
     * This is a field for any additional properties for the avatar.
     */
    extendedPropertyMap?: {
        aspectRatio?: {
            x?: number;
            y?: number;
        };
        resolution?: {
            width?: number;
            height?: number;
        };
    };
    thumbnailUrls?: {
        /**
         * A pre-signed URL for downloading the high-resolution avatar thumbnail.
         */
        hd?: string;
        /**
         * A pre-signed URL for downloading the low-resolution avatar thumbnail.
         */
        lowRes?: string;
    };
    /**
     * The unique ID for the voice.
     */
    voiceId?: string;
    sampleVideo?: {
        /**
         * A pre-signed URL for downloading avatar sample video in WEBM format.
         */
        webm?: string;
        /**
         * A pre-signed URL for downloading avatar sample video in MP4 format.
         */
        mp4?: string;
    };
};

/**
 * The language code for the supported language desired in the result.
 */
export type SupportedLanguageCode = 'en-US' | 'es-ES' | 'de-DE' | 'fr-FR' | 'da-DK' | 'en-GB' | 'en-IN' | 'es-419' | 'es-AR' | 'fr-CA' | 'hi-IN' | 'it-IT' | 'ja-JP' | 'ko-KR' | 'nb-NO' | 'pt-BR' | 'pt-PT' | 'nl-NL' | 'zh-CN' | 'sv-SE';

/**
 * The supported audio format for output.
 */
export type SupportedAudioOutputAudioFormat = 'audio/wav';

/**
 * The supported video format for background video for Avatar.
 */
export type SupportedOutputVideoFormat = 'video/mp4';

/**
 * Supported background type for output Avatar video.
 */
export type SupportedBackgroundType = 'color' | 'video' | 'image';

export type TtsRequest = GenerateSpeechUsingPlainText;

export type GenerateSpeechUsingPlainText = {
    script: (TextSource | UrlSource) & {
        localeCode: SupportedLanguageCode;
        /**
         * The format of the text resource.
         */
        mediaType: 'text/plain';
    };
    /**
     * ID of the voice to use from the catalog of voices.
     */
    voiceId: string;
    output: {
        mediaType: SupportedAudioOutputAudioFormat;
    };
};

export type AvatarRequest = GenerateAvatarUsingPlainText | GenerateAvatarUsingAudioFile;

/**
 * Using Plain Text
 */
export type GenerateAvatarUsingPlainText = {
    script: (TextSource | UrlSource) & {
        localeCode: SupportedLanguageCode;
        /**
         * The format of the text resource.
         */
        mediaType: 'text/plain';
    };
    /**
     * ID of the voice to use from the catalog of voices.
     */
    voiceId: string;
    /**
     * ID of the avatar to use from the catalog of avatars.
     */
    avatarId: string;
    output: AvatarOutputObject;
};

/**
 * Using Audio File
 */
export type GenerateAvatarUsingAudioFile = {
    audio: {
        source: UrlObject;
        mediaType: 'audio/wav';
        localeCode: SupportedLanguageCode;
    };
    /**
     * ID of the avatar to use from the catalog of avatars.
     */
    avatarId: string;
    output: AvatarOutputObject;
};

/**
 * Image or video background
 */
export type UrlSource = {
    /**
     * Details of the source including a pre-signed URL. See the [list of allowed domains for storage](https://developer.adobe.com/audio-video-firefly-services/getting-started/storage-solutions/).
     */
    source?: {
        /**
         * The pre-signed URL pointing to the resource to be used for avatar/speech generation.
         */
        url?: string;
    };
};

/**
 * URL object containing a pre-signed URL. See the [list of allowed domains for storage](https://developer.adobe.com/audio-video-firefly-services/getting-started/storage-solutions/).
 */
export type UrlObject = {
    /**
     * The pre-signed URL pointing to the resource to be used for avatar/speech generation.
     */
    url?: string;
};

/**
 * Output configuration for avatar video generation.
 */
export type AvatarOutputObject = {
    mediaType: SupportedOutputVideoFormat;
    background?: (OutputColor | UrlSource) & {
        type?: SupportedBackgroundType;
    };
    resolution?: {
        width?: string;
        height?: string;
    };
};

/**
 * Details of the text resource.
 */
export type TextSource = string;

/**
 * Color background
 *
 * Color specification for avatar background.
 */
export type OutputColor = string;

/**
 * Response returned when a job is successfully submitted.
 */
export type SubmitApiResponse = {
    jobId?: string;
    statusUrl?: string;
};

/**
 * Response object for job status queries.
 */
export type StatusApiResponse = StatusApiInprogressResponse | StatusApiCompletedResponse | StatusApiFailedResponse | JobStatus;

/**
 * Status of the job.
 */
export type StatusApiResponseStatus = 'pending' | 'running' | 'failed' | 'succeeded';

export type StatusApiInprogressResponse = {
    jobId?: string;
    status?: StatusApiResponseStatus;
};

export type StatusApiCompletedResponse = {
    jobId?: string;
    status?: StatusApiResponseStatus;
    output?: {
        destination?: Destination;
    };
};

/**
 * Response object for failed jobs.
 */
export type StatusApiFailedResponse = {
    status?: StatusApiResponseStatus;
    jobId?: string;
    error_code?: string;
    message?: string;
};

/**
 * Generic error response object.
 */
export type FailedResponse = {
    error_code?: string;
    message?: string;
};

export type ErrorResponse = {
    /**
     * The error code returned with the response.
     */
    error_code: string;
    /**
     * The error message returned with the response.
     */
    message: string;
    /**
     * The error message ID returned with the response.
     */
    messageId?: string;
};

export type TemplateDescribeRequest = {
    /**
     * Contains metadata about the source of the input template.
     */
    source: {
        /**
         * A pre-signed URL pointing to the input template file.
         */
        url: string;
    };
};

export type TemplateDescribeResponse = {
    /**
     * Unique identifier for the describe job.
     */
    jobId: string;
    /**
     * URL to poll for the status of the describe job.
     */
    statusUrl: string;
};

export type PresetItem = {
    /**
     * Unique identifier for the preset.
     */
    presetId: string;
    /**
     * Human-readable label for the preset.
     */
    label: string;
    /**
     * MIME type of the output media (e.g., video/mp4).
     */
    mediaType: string;
    /**
     * Video codec used (e.g., H.264).
     */
    codec: string;
    /**
     * Codec profile (e.g., high).
     */
    profile?: string;
    /**
     * Maximum frames per second as a fraction.
     */
    maxFps: {
        /**
         * Frames-per-second numerator.
         */
        numerator: number;
        /**
         * Frames-per-second denominator.
         */
        denominator: number;
    };
    /**
     * Bitrate mode (e.g., vbr, cbr).
     */
    bitrateMode: string;
    /**
     * Target bitrate in kilobits per second.
     */
    targetBitrateInKbps?: number;
    /**
     * Maximum bitrate in kilobits per second.
     */
    maxBitrateInKbps?: number;
    /**
     * Whether the preset supports alpha channel.
     */
    alpha: boolean;
    /**
     * Primary use case for this preset.
     */
    primaryUsage: string;
};

export type PresetsResponse = {
    items: Array<PresetItem>;
};

export type TemplateRenderRequest = {
    /**
     * Contains metadata about the source of the input template.
     */
    source: {
        /**
         * A pre-signed URL pointing to the input template file.
         */
        url: string;
    };
    /**
     * Array of fonts to be used in the template.
     */
    fonts?: Array<{
        /**
         * PostScript name of the font.
         */
        name: string;
        source: {
            /**
             * Pre-signed URL for the font file (.ttf/.otf).
             */
            url: string;
        };
    }>;
    /**
     * Configuration options for the render request.
     */
    config?: {
        /**
         * How to handle missing fonts. 'fail' will cause the render to fail; 'use_default' will use Premiere Pro fallback behavior.
         */
        handleMissingFonts?: 'fail' | 'use_default';
    };
    /**
     * Array of image, video, or audio assets referenced by variations via assetIndex.
     */
    assets?: Array<{
        source: {
            /**
             * Pre-signed URL for the image, video, or audio asset.
             */
            url: string;
        };
    }>;
    /**
     * Array of export presets. Each item is either a built-in preset (by presetId) or a custom preset (by URL). Outputs reference presets by presetIndex.
     */
    presets?: Array<{
        source: {
            /**
             * ID of a built-in preset from the presets endpoint.
             */
            presetId?: string;
            /**
             * Pre-signed URL for a custom Encoder preset file.
             */
            url?: string;
        };
    }>;
    /**
     * List of variations. Each variation contains variable overrides applied to the template.
     */
    variations: Array<{
        /**
         * Variable overrides for this variation. Each object targets one template variable by variableId and supplies the override value.
         */
        variables: Array<{
            /**
             * Unique identifier for the template variable (from describe response).
             */
            variableId: string;
            /**
             * Override for checkbox controls.
             */
            selectedCheckboxValue?: boolean;
            /**
             * Override for dropdown controls.
             */
            selectedDropdownValue?: string;
            /**
             * Override for slider controls.
             */
            selectedSliderValue?: number;
            /**
             * Override for text controls.
             */
            text?: string;
            /**
             * PostScript font name for text controls.
             */
            fontName?: string;
            /**
             * Index into the assets array for media or audio controls.
             */
            assetIndex?: number;
            /**
             * Scaling behavior for media controls.
             */
            scale?: 'no_scale' | 'fit_to_frame' | 'stretch_to_fill' | 'fill_frame';
            /**
             * Audio preference for audio controls.
             */
            audioPreference?: 'replace' | 'mix';
        }>;
    }>;
    /**
     * Defines which variation and preset combinations to render and optional output file names.
     */
    outputs?: Array<{
        /**
         * Zero-based index of the variation to render.
         */
        variationIndex: number;
        /**
         * Zero-based index of the preset in the presets array.
         */
        presetIndex: number;
        /**
         * Optional custom file name for the output.
         */
        fileName?: string;
    }>;
};

export type TemplateRenderResponse = {
    /**
     * Unique identifier for the render job.
     */
    jobId: string;
    /**
     * URL to poll for the status of the rendering job.
     */
    statusUrl: string;
};

export type JobStatus = {
    /**
     * ID of the render job.
     */
    jobId: string;
    /**
     * Current status of the job.
     */
    status: 'not_started' | 'running' | 'succeeded' | 'failed' | 'partially_succeeded';
    /**
     * Error message when job status is failed.
     */
    message?: string;
    /**
     * Percentage of job completed, as a string.
     */
    percentCompleted?: string;
    /**
     * Array of output files with destination URLs, keyed by variation and preset indices.
     */
    outputs?: Array<{
        /**
         * Zero-based index of the variation that was rendered.
         */
        variationIndex: number;
        /**
         * Zero-based index of the preset that was used for rendering.
         */
        presetIndex: number;
        destination: {
            /**
             * URL from which the rendered video can be downloaded.
             */
            url: string;
        };
    }>;
    /**
     * Array of errors for failed variations (only present when status is partially_succeeded).
     */
    errors?: Array<{
        /**
         * Zero-based index of the variation that failed.
         */
        variationIndex: number;
        /**
         * Zero-based index of the preset that was used for the failed variation.
         */
        presetIndex: number;
        error: {
            /**
             * Error code for the failure.
             */
            error_code: string;
            /**
             * Error message describing the failure.
             */
            message: string;
        };
    }>;
    /**
     * Output for describe API jobs.
     */
    output?: {
        /**
         * Array of fonts from the template.
         */
        fonts?: Array<{
            /**
             * PostScript name of the font.
             */
            name: string;
            /**
             * Whether the font needs to be uploaded in the render request.
             */
            uploadRequired?: boolean;
        }>;
        /**
         * Array of elements from the template.
         */
        elements?: Array<{
            /**
             * Unique identifier for the element.
             */
            id?: string;
            /**
             * Type of the element.
             */
            type: 'mogrt';
            /**
             * Array of controls from the template.
             */
            controls: Array<{
                /**
                 * Unique identifier for the template variable.
                 */
                variableId?: string;
                /**
                 * Unique identifier for the control.
                 */
                id?: string;
                /**
                 * Human-readable label for the control.
                 */
                label?: string;
                /**
                 * Type of the control.
                 */
                type?: 'text' | 'media' | 'dropdown' | 'checkbox' | 'slider' | 'audio' | 'comment';
                /**
                 * Default or current values for the control (e.g., text, fontName, selectedCheckboxValue, selectedDropdownValue, selectedSliderValue, scale).
                 */
                defaultData?: {
                    [key: string]: unknown;
                };
                /**
                 * Data associated with the control.
                 */
                data?: {
                    [key: string]: unknown;
                };
                /**
                 * Available options (object for dropdown; array for checkbox).
                 */
                options?: unknown;
                /**
                 * Minimum and maximum values for slider controls.
                 */
                range?: {
                    minimum?: number;
                    maximum?: number;
                };
                /**
                 * Dimensions for media controls.
                 */
                size?: {
                    width?: number;
                    height?: number;
                };
                /**
                 * Possible scale values for media controls.
                 */
                possibleScaleValues?: Array<string>;
                /**
                 * Duration in seconds for audio controls.
                 */
                durationInSeconds?: number;
                /**
                 * Possible audio preferences (e.g., replace, mix) for audio controls.
                 */
                possibleAudioPreferences?: Array<string>;
                /**
                 * Comment text for comment controls.
                 */
                text?: string;
            }>;
        }>;
    };
};

/**
 * Configuration for an overlay in the reframed video.
 */
export type Overlay = {
    /**
     * The media type of the overlay.
     */
    mediaType: 'image/gif' | 'image/png' | 'image/jpeg';
    /**
     * Details of the source including a pre-signed URL. See the [list of allowed domains for storage](https://developer.adobe.com/audio-video-firefly-services/getting-started/storage-solutions/).
     */
    source: {
        /**
         * The pre-signed URL pointing to the overlay source.
         */
        url: string;
    };
    /**
     * The start time of the overlay in the video.
     */
    startTime: string;
    /**
     * The duration of the overlay in the video.
     */
    duration: string;
    /**
     * The scale of the overlay.
     */
    scale: {
        /**
         * The width of the overlay.
         */
        width: number;
        /**
         * The height of the overlay.
         */
        height: number;
    };
    /**
     * The position of the overlay.
     */
    position: {
        /**
         * The anchor point of the overlay.
         */
        anchorPoint: 'top_left' | 'top_right' | 'bottom_left' | 'bottom_right' | 'center';
        /**
         * The X offset of the overlay from the anchor point.
         */
        offsetX: number;
        /**
         * The Y offset of the overlay from the anchor point.
         */
        offsetY: number;
    };
    /**
     * The repeat behavior of the overlay.
     */
    repeat?: 'loop' | 'once';
};

/**
 * Error response for the reframed video job.
 */
export type GenerateReframedVideoJobErrorBody = {
    /**
     * A code representing the specific error type.
     */
    error_code: string;
    /**
     * A description of the error that occurred.
     */
    message: string;
};

export type TranscribeRequest = (TranscribeAudioInput | TranscribeVideoInput) & {
    /**
     * This determines the language used in the processed output. See the usage notes for more about [the supported languages](https://developer.adobe.com/audio-video-firefly-services/getting-started/usage/#language-support).
     */
    targetLocaleCodes?: Array<TargetLocaleCodes>;
    /**
     * Details to generate captions.
     */
    captions?: Captions;
};

/**
 * The request body for transcribing audio.
 */
export type TranscribeAudioInput = {
    audio: AudioInput;
};

/**
 * The request body for transcribing video.
 */
export type TranscribeVideoInput = {
    video: VideoInput;
};

export type Captions = {
    /**
     * Accepted values: ['SRT']
     */
    targetFormats?: Array<TargetCaptionFormats>;
};

/**
 * Source details including a pre-signed URL for accessing the input media. See the [list of allowed domains for storage](https://developer.adobe.com/audio-video-firefly-services/getting-started/storage-solutions/).
 */
export type Source = {
    /**
     * The pre-signed URL pointing to the input source.
     */
    url: string;
};

/**
 * Destination details including a pre-signed URL for the output media.
 */
export type Destination = {
    /**
     * The pre-signed URL pointing to the output destination.
     */
    url: string;
};

/**
 * The dub request body.
 */
export type DubRequest = DubAudioRequest | DubVideoRequest;

/**
 * Audio dub request
 *
 * The audio dub request body.
 */
export type DubAudioRequest = {
    /**
     * This determines the language used in the processed output. See the usage notes for more about [the supported languages](https://developer.adobe.com/audio-video-firefly-services/getting-started/usage/#language-support).
     */
    targetLocaleCodes?: Array<TargetLocaleCodes>;
    transcripts?: Array<TranscriptInput>;
    audio: AudioInput;
};

/**
 * Video dub request
 *
 * The video dub request body.
 */
export type DubVideoRequest = {
    /**
     * This determines the language used in the processed output. See the usage notes for more about [the supported languages](https://developer.adobe.com/audio-video-firefly-services/getting-started/usage/#language-support).
     */
    targetLocaleCodes?: Array<TargetLocaleCodes>;
    transcripts?: Array<TranscriptInput>;
    video: VideoInput;
    /**
     * If `true`, a high-quality composited lip sync will be used in the video output.
     */
    lipSync?: boolean;
};

/**
 * Job status response.
 */
export type JobStatusLinkResponse = {
    /**
     * URL to download the results of the job.
     */
    statusUrl: string;
    /**
     * The job ID.
     */
    jobId: string;
};

/**
 * Status of the job.
 */
export type FireflyJobApiResponseStatus = 'pending' | 'running' | 'failed' | 'succeeded';

/**
 * Firefly job response.
 */
export type FireflyJobResponse = FireflyJobApiResponse | FireflyJobErrorResponse;

/**
 * Firefly job success response.
 */
export type FireflyJobApiResponse = {
    status: FireflyJobApiResponseStatus;
    /**
     * Associated job ID.
     */
    jobId: string;
    /**
     * Job response details.
     */
    outputs?: Array<DubJobResponse | TranscribeOutput>;
};

/**
 * Firefly job error response.
 */
export type FireflyJobErrorResponse = {
    status: FireflyJobApiResponseStatus;
    /**
     * Associated job ID.
     */
    jobId: string;
    /**
     * The error message.
     */
    message?: string;
    /**
     * Associated error code.
     */
    error_code?: string;
};

/**
 * The error response object.
 */
export type ErrorBody = {
    /**
     * The error message.
     */
    message: string;
    /**
     * Associated error code.
     */
    error_code: string;
};

/**
 * Transcribe success response
 */
export type TranscribeOutput = Array<{
    destination?: Destination;
    captions?: CaptionOutput;
    localeCode?: TargetLocaleCodes;
}>;

/**
 * Captions output
 */
export type CaptionOutput = Array<{
    destination?: Destination;
    /**
     * Format of the caption
     */
    format?: TargetCaptionFormats;
}>;

/**
 * Dubbing success response
 */
export type DubJobResponse = DubSuccess | DubPartialFailure;

/**
 * Dubbing success
 */
export type DubSuccess = {
    audioOutput?: AudioOutput;
    videoOutput?: VideoOutput;
    transcriptOutput?: TranscribeOutput;
};

/**
 * Media type of the audio output.
 */
export type AudioOutputMediaType = 'audio/wav';

/**
 * Media type of the video output.
 */
export type VideoOutputMediaType = 'video/mp4' | 'video/mov';

/**
 * Audio output in dubbing response.
 */
export type AudioOutput = {
    mediaType?: AudioOutputMediaType;
    destination?: Destination;
};

/**
 * Video output in dubbing response.
 */
export type VideoOutput = {
    mediaType?: VideoOutputMediaType;
    destination?: Destination;
};

/**
 * Dubbing failure for specific language.
 */
export type DubPartialFailure = {
    error?: ErrorBody;
};

/**
 * Transcript input details for a transcribe request.
 */
export type TranscriptInput = {
    /**
     * The pre-signed URL to download the translated/edited transcripts. See the [list of allowed domains for storage](https://developer.adobe.com/audio-video-firefly-services/getting-started/storage-solutions/).
     */
    source: Source;
};

/**
 * Locale code for dubbing target.
 */
export type TargetLocaleCodes = 'da-DK' | 'en-IN' | 'en-GB' | 'es-AR' | 'es-419' | 'fr-CA' | 'hi-IN' | 'ja-JP' | 'ko-KR' | 'nb-NO' | 'nl-NL' | 'pt-BR' | 'sv-SE' | 'zh-CN' | 'en-US' | 'es-ES' | 'de-DE' | 'fr-FR' | 'it-IT' | 'pt-PT';

/**
 * Target caption format.
 */
export type TargetCaptionFormats = 'SRT';

/**
 * The audio input details for a dub request.
 */
export type AudioInput = {
    source?: Source;
    mediaType: AudioInputMediaType;
};

/**
 * The video input details for a dub request.
 */
export type VideoInput = {
    source?: Source;
    mediaType: VideoInputMediaType;
    metadata?: {
        dialogTrackNumber?: number;
    };
};

/**
 * Media type of the audio input.
 */
export type AudioInputMediaType = 'audio/mp3' | 'audio/wav' | 'audio/mpeg' | 'audio/x-m4a' | 'audio/aac';

/**
 * Media type of the video input.
 */
export type VideoInputMediaType = 'video/mp4' | 'video/mov' | 'video/quicktime' | 'video/x-msvideo' | 'video/x-matroska';

/**
 * Video input details for generate reframed video request.
 */
export type VideoInputV2 = {
    /**
     * Details of the source including a pre-signed URL. See the [list of allowed domains for storage](https://developer.adobe.com/audio-video-firefly-services/getting-started/storage-solutions/).
     */
    source: {
        /**
         * The pre-signed URL pointing to the input source.
         */
        url: string;
    };
};

/**
 * Analysis configuration for the video processing.
 */
export type AnalysisV2 = {
    /**
     * Applies scene edit detection before reframing.
     */
    sceneEditDetection?: boolean;
    /**
     * Array of focal point keyword identifiers for reframing. Up to 10 keywords are allowed. Keywords must be alphanumeric characters, spaces, hyphens, or underscores only, with a maximum of 1000 characters per keyword.
     */
    focalPoints?: Array<string>;
};

export type OverlayV2 = {
    source?: Source;
    /**
     * Start time for the overlay in the format HH:MM:SS:FF.
     */
    startTime?: string;
    /**
     * Duration of the overlay in the format HH:MM:SS:FF.
     */
    duration?: string;
    scale?: ScaleV2;
    position?: PositionV2;
    /**
     * Repeat behavior for GIF overlay (optional).
     */
    repeat?: null | RepeatV2;
};

/**
 * Position configuration for overlay placement.
 */
export type PositionV2 = {
    /**
     * Anchor point for taking the position reference.
     */
    anchorPoint?: 'top_left' | 'top_right' | 'bottom_left' | 'bottom_right' | 'center';
    /**
     * Horizontal offset for the anchor point.
     */
    offsetX?: number | null;
    /**
     * Vertical offset for the anchor point.
     */
    offsetY?: number | null;
};

/**
 * Defines the repeat behavior of the overlay.
 */
export type RepeatV2 = 'stop_on_last_frame' | 'loop' | 'time_stretch';

/**
 * Scale configuration for overlay dimensions.
 */
export type ScaleV2 = {
    /**
     * The width of the scaled overlay.
     */
    width?: number;
    /**
     * The height of the scaled overlay.
     */
    height?: number;
};

/**
 * Aspect ratio specification for video output.
 */
export type AspectRatioV2 = {
    /**
     * AspectRatio x ratio.
     */
    x: number;
    /**
     * AspectRatio y ratio.
     */
    y: number;
};

/**
 * Output format configuration. A media property is mandatory when this format object is specified.
 */
export type OutputFormatV2 = {
    /**
     * Media format for the output video. If only the OTIO file is needed, set this as `none`.
     */
    media: 'none' | 'mp4' | 'mov' | 'source';
    /**
     * Sidecar format for additional metadata.
     */
    sidecar: 'json' | 'otio';
};

/**
 * Configuration for composing elements on the video.
 */
export type CompositionV2 = {
    /**
     * List of overlays to be composed on the video.
     */
    overlays?: Array<OverlayV2>;
};

export type VoicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/voices';
};

export type VoicesErrors = {
    /**
     * Unauthorized
     */
    401: FailedResponse;
    /**
     * Forbidden
     */
    403: FailedResponse;
    /**
     * Too Many Requests
     */
    429: FailedResponse;
    /**
     * Internal Server Error
     */
    500: FailedResponse;
};

export type VoicesError = VoicesErrors[keyof VoicesErrors];

export type VoicesResponses = {
    /**
     * Success
     */
    200: SuccessfulVoicesResponse;
};

export type VoicesResponse = VoicesResponses[keyof VoicesResponses];

export type GenerateSpeechData = {
    /**
     * The request body contains the transcript used for generating speech.
     */
    body: GenerateSpeechUsingPlainText;
    path?: never;
    query?: never;
    url: '/v1/generate-speech';
};

export type GenerateSpeechErrors = {
    /**
     * Bad Request
     */
    400: FailedResponse;
    /**
     * Unauthorized
     */
    401: FailedResponse;
    /**
     * Forbidden
     */
    403: FailedResponse;
    /**
     * Unprocessable Entity
     */
    422: FailedResponse;
    /**
     * Too Many Requests
     */
    429: FailedResponse;
    /**
     * Unauthorized For Legal Reasons
     */
    451: FailedResponse;
    /**
     * Internal Server Error
     */
    500: FailedResponse;
};

export type GenerateSpeechError = GenerateSpeechErrors[keyof GenerateSpeechErrors];

export type GenerateSpeechResponses = {
    /**
     * Accepted
     */
    202: SubmitApiResponse;
};

export type GenerateSpeechResponse = GenerateSpeechResponses[keyof GenerateSpeechResponses];

export type StatusData = {
    body?: never;
    path: {
        /**
         * The job ID of an asynchronous job.
         */
        jobId: string;
    };
    query?: never;
    url: '/v1/status/{jobId}';
};

export type StatusErrors = {
    /**
     * Unauthorized
     */
    401: FailedResponse;
    /**
     * Forbidden
     */
    403: FailedResponse;
    /**
     * Not Found
     */
    404: FailedResponse;
    /**
     * Too Many Requests
     */
    429: FailedResponse;
    /**
     * Internal Server Error
     */
    500: FailedResponse;
};

export type StatusError = StatusErrors[keyof StatusErrors];

export type StatusResponses = {
    /**
     * Success
     */
    200: StatusApiResponse;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type TemplateDescribeData = {
    body: TemplateDescribeRequest;
    path?: never;
    query?: never;
    url: '/v1/templates/describe';
};

export type TemplateDescribeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type TemplateDescribeError = TemplateDescribeErrors[keyof TemplateDescribeErrors];

export type TemplateDescribeResponses = {
    /**
     * Accepted
     */
    202: TemplateDescribeResponse;
};

export type TemplateDescribeResponse2 = TemplateDescribeResponses[keyof TemplateDescribeResponses];

export type GetPresetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/presets';
};

export type GetPresetsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
};

export type GetPresetsError = GetPresetsErrors[keyof GetPresetsErrors];

export type GetPresetsResponses = {
    /**
     * Success
     */
    200: PresetsResponse;
};

export type GetPresetsResponse = GetPresetsResponses[keyof GetPresetsResponses];

export type TemplateRenderData = {
    body: TemplateRenderRequest;
    path?: never;
    query?: never;
    url: '/v1/templates/render';
};

export type TemplateRenderErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type TemplateRenderError = TemplateRenderErrors[keyof TemplateRenderErrors];

export type TemplateRenderResponses = {
    /**
     * Accepted
     */
    202: TemplateRenderResponse;
};

export type TemplateRenderResponse2 = TemplateRenderResponses[keyof TemplateRenderResponses];

export type GenerateReframedVideoData = {
    /**
     * The reframe request body.
     */
    body: {
        /**
         * Video input details.
         */
        video: {
            /**
             * Details of the source including a pre-signed URL. See the [list of allowed domains for storage](https://developer.adobe.com/audio-video-firefly-services/getting-started/storage-solutions/).
             */
            source: {
                /**
                 * The pre-signed URL pointing to the input source.
                 */
                url: string;
            };
            /**
             * Supported video media types.
             */
            mediaType: 'video/mp4' | 'video/quicktime';
        };
        /**
         * Apply Scene Edit Detection before reframing.
         */
        sceneEditDetection?: boolean;
        /**
         * Configuration details for video overlays.
         */
        overlays?: Array<Overlay>;
        /**
         * Configuration details for the generated reframed video.
         */
        outputConfig: {
            /**
             * A list of aspect ratios for the output video.
             */
            aspectRatios: Array<string>;
        };
    };
    path?: never;
    query?: never;
    url: '/v1/reframe';
};

export type GenerateReframedVideoErrors = {
    /**
     * Bad Request
     */
    400: GenerateReframedVideoJobErrorBody;
    /**
     * Unauthorized
     */
    401: GenerateReframedVideoJobErrorBody;
    /**
     * Forbidden
     */
    403: GenerateReframedVideoJobErrorBody;
    /**
     * Resource not found
     */
    404: GenerateReframedVideoJobErrorBody;
    /**
     * Method Not Allowed
     */
    405: GenerateReframedVideoJobErrorBody;
    /**
     * Too many requests
     */
    429: GenerateReframedVideoJobErrorBody;
    /**
     * Internal Server Error
     */
    500: GenerateReframedVideoJobErrorBody;
};

export type GenerateReframedVideoError = GenerateReframedVideoErrors[keyof GenerateReframedVideoErrors];

export type GenerateReframedVideoResponses = {
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    202: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
};

export type GenerateReframedVideoResponse = GenerateReframedVideoResponses[keyof GenerateReframedVideoResponses];

export type TranscribeData = {
    /**
     * The transcribe request body.
     */
    body: TranscribeRequest;
    path?: never;
    query?: never;
    url: '/v1/transcribe';
};

export type TranscribeErrors = {
    /**
     * Bad Request
     */
    400: ErrorBody;
    /**
     * Unauthorized
     */
    401: ErrorBody;
    /**
     * Forbidden
     */
    403: ErrorBody;
    /**
     * Resource Not Found
     */
    404: ErrorBody;
    /**
     * Method Not Allowed
     */
    405: ErrorBody;
    /**
     * Unprocessable Entity
     */
    422: ErrorBody;
    /**
     * Too Many Requests
     */
    429: ErrorBody;
    /**
     * Unauthorized For Legal Reasons
     */
    451: ErrorBody;
    /**
     * Internal Server Error
     */
    500: ErrorBody;
};

export type TranscribeError = TranscribeErrors[keyof TranscribeErrors];

export type TranscribeResponses = {
    /**
     * Accepted
     */
    202: JobStatusLinkResponse;
};

export type TranscribeResponse = TranscribeResponses[keyof TranscribeResponses];

export type DubData = {
    /**
     * The dub request body.
     */
    body: DubRequest;
    path?: never;
    query?: never;
    url: '/v1/dub';
};

export type DubErrors = {
    /**
     * Bad Request
     */
    400: ErrorBody;
    /**
     * Unauthorized
     */
    401: ErrorBody;
    /**
     * Forbidden
     */
    403: ErrorBody;
    /**
     * Resource Not Found
     */
    404: ErrorBody;
    /**
     * Method Not Allowed
     */
    405: ErrorBody;
    /**
     * Unprocessable Entity
     */
    422: ErrorBody;
    /**
     * Too Many Requests
     */
    429: ErrorBody;
    /**
     * Unauthorized For Legal Reasons
     */
    451: ErrorBody;
    /**
     * Internal Server Error
     */
    500: ErrorBody;
};

export type DubError = DubErrors[keyof DubErrors];

export type DubResponses = {
    /**
     * Accepted
     */
    202: JobStatusLinkResponse;
};

export type DubResponse = DubResponses[keyof DubResponses];

export type AvatarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/avatars';
};

export type AvatarsErrors = {
    /**
     * Unauthorized
     */
    401: FailedResponse;
    /**
     * Forbidden
     */
    403: FailedResponse;
    /**
     * Too Many Requests
     */
    429: FailedResponse;
    /**
     * Internal Server Error
     */
    500: FailedResponse;
};

export type AvatarsError = AvatarsErrors[keyof AvatarsErrors];

export type AvatarsResponses = {
    /**
     * Success
     */
    200: SuccessfulAvatarsResponse;
};

export type AvatarsResponse = AvatarsResponses[keyof AvatarsResponses];

export type GenerateReframedVideoV2Data = {
    /**
     * Generate reframed video request body.
     */
    body: {
        video: VideoInputV2;
        analysis?: AnalysisV2;
        composition?: CompositionV2;
        /**
         * Output configuration details for generating the reframed video.
         */
        output: {
            format?: OutputFormatV2;
            /**
             * Array of output rendition specifications.
             */
            renditions: Array<{
                aspectRatio: AspectRatioV2;
                mediaDestination?: Destination;
                sidecarDestination?: Destination;
            } | {
                resolution: {
                    /**
                     * Resolution width of the output in pixels.
                     */
                    width: number;
                    /**
                     * Resolution height of the output in pixels.
                     */
                    height: number;
                };
                mediaDestination?: Destination;
                sidecarDestination?: Destination;
            }>;
        };
    };
    path?: never;
    query?: never;
    url: '/v2/reframe';
};

export type GenerateReframedVideoV2Errors = {
    /**
     * Error response for the reframed video job.
     */
    400: {
        /**
         * A code representing the specific error type.
         */
        error_code: string;
        /**
         * A description of the error that occurred.
         */
        message: string;
    };
    /**
     * Error response for the reframed video job.
     */
    401: {
        /**
         * A code representing the specific error type.
         */
        error_code: string;
        /**
         * A description of the error that occurred.
         */
        message: string;
    };
    /**
     * Error response for the reframed video job.
     */
    403: {
        /**
         * A code representing the specific error type.
         */
        error_code: string;
        /**
         * A description of the error that occurred.
         */
        message: string;
    };
    /**
     * Error response for the reframed video job.
     */
    404: {
        /**
         * A code representing the specific error type.
         */
        error_code: string;
        /**
         * A description of the error that occurred.
         */
        message: string;
    };
    /**
     * Error response for the reframed video job.
     */
    405: {
        /**
         * A code representing the specific error type.
         */
        error_code: string;
        /**
         * A description of the error that occurred.
         */
        message: string;
    };
    /**
     * Error response for the reframed video job.
     */
    429: {
        /**
         * A code representing the specific error type.
         */
        error_code: string;
        /**
         * A description of the error that occurred.
         */
        message: string;
    };
    /**
     * Error response for the reframed video job.
     */
    500: {
        /**
         * A code representing the specific error type.
         */
        error_code: string;
        /**
         * A description of the error that occurred.
         */
        message: string;
    };
};

export type GenerateReframedVideoV2Error = GenerateReframedVideoV2Errors[keyof GenerateReframedVideoV2Errors];

export type GenerateReframedVideoV2Responses = {
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    202: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
};

export type GenerateReframedVideoV2Response = GenerateReframedVideoV2Responses[keyof GenerateReframedVideoV2Responses];

export type JobResultV2Data = {
    body?: never;
    path: {
        /**
         * The job ID to get status for an asynchronous generate reframed video job.
         */
        jobId: string;
    };
    query?: never;
    url: '/v2/status/{jobId}';
};

export type JobResultV2Errors = {
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    400: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    401: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    403: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    404: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    405: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    422: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    429: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
    /**
     * Response indicating that the reframed video job has been successfully submitted.
     */
    500: {
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * The URL to monitor the status of the job.
         */
        statusUrl: string;
    };
};

export type JobResultV2Error = JobResultV2Errors[keyof JobResultV2Errors];

export type JobResultV2Responses = {
    /**
     * Job response on status API.
     */
    200: {
        /**
         * The status of the reframed video job.
         */
        status: 'not_started' | 'running' | 'failed' | 'succeeded' | 'partially_succeeded';
        /**
         * The unique identifier for the job.
         */
        jobId: string;
    } | {
        /**
         * The status of the reframed video job.
         */
        status: 'not_started' | 'running' | 'failed' | 'succeeded' | 'partially_succeeded';
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * Array of output rendition results.
         */
        outputs: Array<{
            /**
             * Details of the output destination, including a pre-signed URL.
             */
            destination: {
                /**
                 * The pre-signed URL pointing to the output.
                 */
                url: string;
            };
        } | {
            /**
             * Details of the error encountered during the reframing process.
             */
            error: {
                /**
                 * A code representing the specific error type.
                 */
                error_code: string;
                /**
                 * A description of the error that occurred.
                 */
                message: string;
            };
        }>;
    } | {
        /**
         * The status of the reframed video job.
         */
        status: 'not_started' | 'running' | 'failed' | 'succeeded' | 'partially_succeeded';
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * Details of the job's partial success, including successful outputs and any errors encountered.
         */
        outputs: Array<{
            /**
             * Details of the output destination, including a pre-signed URL.
             */
            destination: {
                /**
                 * The pre-signed URL pointing to the output.
                 */
                url: string;
            };
        } | {
            /**
             * Details of the error encountered during the reframing process.
             */
            error: {
                /**
                 * A code representing the specific error type.
                 */
                error_code: string;
                /**
                 * A description of the error that occurred.
                 */
                message: string;
            };
        }>;
    } | {
        /**
         * The status of the reframed video job, indicating a failure.
         */
        status: 'not_started' | 'running' | 'failed' | 'succeeded' | 'partially_succeeded';
        /**
         * The unique identifier for the job.
         */
        jobId: string;
        /**
         * Details of the errors encountered during the job.
         */
        outputs: {
            /**
             * Array of failed rendition outputs.
             */
            renditions: Array<{
                /**
                 * Details of the error encountered during the reframing process.
                 */
                error: {
                    /**
                     * A code representing the specific error type.
                     */
                    error_code: string;
                    /**
                     * A description of the error that occurred.
                     */
                    message: string;
                };
            }>;
        };
    };
};

export type JobResultV2Response = JobResultV2Responses[keyof JobResultV2Responses];

export type GenerateAvatarData = {
    /**
     * The request body contains the transcript and details for generating an avatar.
     */
    body: AvatarRequest;
    path?: never;
    query?: never;
    url: '/v1/generate-avatar';
};

export type GenerateAvatarErrors = {
    /**
     * Bad Request
     */
    400: FailedResponse;
    /**
     * Unauthorized
     */
    401: FailedResponse;
    /**
     * Forbidden
     */
    403: FailedResponse;
    /**
     * Unprocessable Entity.
     */
    422: FailedResponse;
    /**
     * Too Many Requests
     */
    429: FailedResponse;
    /**
     * Unavailable For Legal Reasons
     */
    451: FailedResponse;
    /**
     * Internal Server Error
     */
    500: FailedResponse;
};

export type GenerateAvatarError = GenerateAvatarErrors[keyof GenerateAvatarErrors];

export type GenerateAvatarResponses = {
    /**
     * Accepted
     */
    202: SubmitApiResponse;
};

export type GenerateAvatarResponse = GenerateAvatarResponses[keyof GenerateAvatarResponses];
