// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://indesign.adobe.io' | (string & {});
};

/**
 * Supported hyphenation dictionary languages.
 */
export type HyphenationLanguage = 'Arabic' | 'Bengali (India)' | 'Bulgarian' | 'Burmese (Myanmar [Burma])' | 'Catalan' | 'Croatian' | 'Czech' | 'Danish' | 'Dutch: 2005 Reform' | 'Dutch: Old Rules' | 'English: Canadian' | 'English: UK' | 'English: USA' | 'English: USA Legal' | 'English: USA Medical' | 'Estonian' | 'Finnish' | 'French' | 'French: Canadian' | 'German: 1996 Reform' | 'German: 2006 Reform' | 'German: Austria 2006 Reform' | 'German: Old Rules' | 'German: Swiss' | 'German: Swiss 2006 Reform' | 'Greek' | 'Gujarati (India)' | 'Hebrew' | 'Hindi (India)' | 'Hungarian' | 'Indonesian (Indonesia)' | 'Italian' | 'Kannada (India)' | 'Khmer (Cambodia)' | 'Lao (Laos)' | 'Latvian' | 'Lithuanian' | 'Malayalam (India)' | 'Marathi (India)' | 'Norwegian: Bokmål' | 'Norwegian: Nynorsk' | 'Oriya (India)' | 'Polish' | 'Portuguese' | 'Portuguese: Brazilian' | 'Portuguese: Orthographic Agreement' | 'Punjabi (India)' | 'Romanian' | 'Russian' | 'Sinhala (Sri Lanka)' | 'Slovak' | 'Slovenian' | 'Spanish' | 'Swedish' | 'Tamil (India)' | 'Telugu (India)' | 'Thai' | 'Turkish' | 'Ukrainian' | 'Vietnamese';

/**
 * The URL where the asset will be fetched.
 */
export type InputAsset = {
    source: {
        /**
         * The pre-signed URL of the input asset. This is the URL of the asset that will be downloaded and acted upon during the job.
         */
        url: string;
    };
    /**
     * This provides a path relative to a temporary base directory (working directory) where the resource would be downloaded. This would be used to identify the assets within the parameters. It cannot go up using '..' or '/'. Should be a valid file name.
     */
    destination?: string;
};

/**
 * The base job request for any job.
 */
export type BaseJobRequest = {
    /**
     * Information about the assets, which will be used to process the job.
     */
    assets: Array<InputAsset>;
    params?: {
        /**
         * General settings.
         */
        generalSettings?: {
            /**
             * Settings related to fonts. It is recommended to include fonts to avoid missing fonts warnings when processing the job.
             */
            fonts?: {
                /**
                 * This lists the font directories for the input InDesign documents. "Document Fonts" in parallel to the document will continue to work even without specifying them.  <br></br> If none are specified, a temporary base directory (working directory) will be considered as a font directory.
                 */
                fontsDirectories?: Array<string>;
            };
            /**
             * Settings related to links.
             */
            links?: {
                replaceLinks?: Array<{
                    /**
                     * The document in which the relinking is to be done. Relinking of assets is required to ensure that there are no missing links in the output document.
                     */
                    targetDocument: string;
                    mapping: Array<{
                        /**
                         * This provides a path relative to a temporary base directory (working directory) where the asset to be linked to can be found. It cannot go up using '..' or '/'. Should be a valid file name.
                         */
                        newAssetRelativePath: string;
                        /**
                         * The existing URI of the link that needs relinking. If multiple links with this URI are found, all will be relinked. If `linkID` is provided, this attribute will be ignored. Either `currentURI` or `linkID` should be present.
                         */
                        currentURI?: string;
                        /**
                         * The ID of the link which is to be relinked. If `currentURI` is also provided, it will be ignored. Either `currentURI` or `linkID` should be present.
                         */
                        linkID?: number;
                    }>;
                }>;
            };
            /**
             * Describes parameters regarding application logs.
             */
            appLogs?: {
                /**
                 * This provides a path to a file, relative to the temporary base directory (working directory). This file is where the application's logs are to be dumped.
                 */
                logsRelativePath?: string;
            };
        };
    };
};

/**
 * The URL where the output assets are to be posted after the job is processed.
 */
export type OutputAsset = {
    destination: {
        /**
         * The URL of the asset.
         */
        url: string;
        /**
         * This is an optional parameter, however IT IS RECOMMENDED to provide this information.
         */
        storageType?: 'Azure' | 'Dropbox' | 'AWS';
    };
    /**
     * This provides a path relative of the output where the resource would be generated. It cannot go up using '..' or '/'. Should be a valid file name.
     */
    source: string;
};

export type BaseJobRequestWithOutput = BaseJobRequest & {
    outputs?: Array<OutputAsset>;
};

export type MergeDataRequest = BaseJobRequestWithOutput & {
    params: {
        /**
         * The tagged document to be used as the template for merging.
         */
        targetDocument: string;
        /**
         * The data source files to be used.
         */
        dataSource: string;
        /**
         * The type of output.
         */
        outputMediaType?: 'image/jpeg' | 'image/png' | 'application/pdf' | 'application/x-indesign';
        /**
         * The settings corresponding to the output format.
         */
        exportSettings?: {
            /**
             * File path reference to a `.joboptions` file (Adobe PDF preset file) containing custom PDF export settings. This file must be included as part of the input assets. It defines detailed PDF output configurations such as compression, color management, and security settings. When provided, this takes precedence over the `pdfPreset` attribute. Only applicable when generating PDF output.
             */
            jobOptionsFile?: string;
            /**
             * The PDF export style to be used. This is relevant if `outputMediaType` is `application/pdf`.
             */
            pdfPreset?: 'High Quality Print' | 'PDF/X-1a:2001' | 'PDF/X-3:2002' | 'PDF/X-4:2008' | 'Press Quality' | 'Smallest File Size';
            /**
             * Defines the quality of the output for JPEG and PNG formats.
             */
            quality?: 'low' | 'medium' | 'high' | 'maximum';
            /**
             * If `true`, links images to the target document. If `false`, embeds linked images already referred in the target document.  Only relevant if `outputMediaType` is `application/x-indesign`.
             */
            linkImages?: boolean;
        };
        /**
         * The ranges of records to process for this job. Value can be `All`, along with numeral ranges. For example, '1-2, 5'.
         */
        recordRange?: string;
        /**
         * If `true`, will show as many records as will fit on a page.
         */
        allowMultipleRecordsPerPage?: boolean;
        /**
         * The options to be used when `allowMultipleRecordsPerPage` is set to `true`.
         */
        multipleRecordLayoutOptions?: {
            /**
             * The order that records will be arranged in the target document.
             * * `rows_first` - Arranges records by row.
             * * `columns_first` - Arranges records by column.
             *
             */
            arrangeBy?: 'rows_first' | 'columns_first';
            /**
             * The offset value of the bottom margin in the target document. The values can be specified like `1 pt`, `1 pica`, `1`, etc. If a number is mentioned in the string, it will be used as a value in pica.
             */
            bottomMargin?: string;
            /**
             * The offset value of the top margin in the target document.  The values can be specified like `1 pt`, `1 pica`, `1`, etc. If a number is mentioned in the string, it will be used as a value in pica.
             */
            topMargin?: string;
            /**
             * The offset value of the left margin in the target document. The values can be specified like `1 pt`, `1 pica`, `1`, etc. If a number is mentioned in the string, it will be used as a value in pica.
             */
            leftMargin?: string;
            /**
             * The offset value of the right margin in the target document. The values can be specified like `1 pt`, `1 pica`, `1`, etc. If a number is mentioned in the string, it will be used as a value in pica.
             */
            rightMargin?: string;
            /**
             * The amount of spacing between columns of records in the target document.  The values can be specified like `1 pt`, `1 pica`, `1`, etc. If a number is mentioned in the string, it will be used as a value in pica.
             */
            columnSpacing?: string;
            /**
             * The amount of spacing between rows of records in the target document.  The values can be specified like `1 pt`, `1 pica`, `1`, etc. If a number is mentioned in the string, it will be used as a value in pica.
             */
            rowSpacing?: string;
        };
        /**
         * These are the options for image placement which will be used while merging images in the document.
         */
        imagePlacementOptions?: {
            /**
             * If true, this centers the image in the frame while preserving the frame size as content size and proportions. If the content is larger than the frame, content around the edges is obscured by the bounding box of the frame. <br></br> This won't work when `fittingOption` is `Content_Aware_Fit`.
             */
            centerImage?: boolean;
            /**
             * The method of fitting content in a frame.
             * * `content_aware_fit` - Selects best crop region of the content for the frame based on Adobe Sensei. This preserves frame size but it might scale the content size. If this fitting is set, the `centerImage` property is turned-off.
             * * `fill_proportional` - Resizes content to fill the frame while preserving the proportions of the content. If the content and frame have different proportions, some of the content is obscured by the bounding box of the frame.
             * * `fit_content_to_frame` - Resizes content to fit the frame. Content that is a different size than the frame appears stretched or squeezed.
             * * `fit_frame_to_content` - Resizes the frame so it fits the content.
             * * `honor_existing_style` - Applies the frame fitting based on existing settings applied on the original frame.
             * * `preserve_sizes` - Preserves the original sizes of the frame and the content. Content that is larger than the frame is obscured around the edges.
             * * `proportional` - Resizes content to fit the frame while preserving content proportions. If the content and frame have different proportions, an empty space occurs in the frame.
             *
             */
            fittingOption?: 'content_aware_fit' | 'fill_proportional' | 'fit_content_to_frame' | 'fit_frame_to_content' | 'honor_existing_style' | 'preserve_sizes' | 'proportional';
            /**
             * This applies to the images being brought in the document while merging. If true, this links images to the target document. If false, it embeds images in the target document.
             */
            linkImages?: boolean;
        };
        /**
         * Hyphenation settings to control word breaking and hyphenation behavior during merge.
         */
        hyphenationSettings?: {
            /**
             * Minimum number of characters at the start of a word before a hyphen may be inserted.
             */
            afterFirst?: number;
            /**
             * Minimum number of characters at the end of a word after a hyphen.
             */
            beforeLast?: number;
            /**
             * Minimum word length for hyphenation to apply.
             */
            wordsLongerThan?: number;
            /**
             * Maximum allowed consecutive hyphenated lines.
             */
            ladderLimit?: number;
            /**
             * Whitespace ratio allowed at the end of a line before hyphenation begins (0–1).
             */
            zone?: number;
            /**
             * If true, allows hyphenation of capitalized words.
             */
            capitalizedWords?: boolean;
            /**
             * If true, allows hyphenation of the last word in a paragraph.
             */
            lastWord?: boolean;
            /**
             * If true, allows hyphenation across columns.
             */
            acrossColumns?: boolean;
            /**
             * Special hyphenation definitions by language.
             */
            dictionarySettings?: Array<{
                language: HyphenationLanguage;
                /**
                 * List of special hyphenation definitions (use `~` to mark break points, e.g., `Know~how`, `check~in`. Put `~` at the beginning of the word to exclude it from hyphenation, e.g., `~Wallstreet`, `~Starbucks`).
                 */
                wordList: Array<string>;
            }>;
        };
        /**
         * The maximum number of pages per document.
         */
        pagesPerDocument?: number;
        /**
         * If true, removes blank lines caused by empty fields.
         */
        removeBlankLines?: boolean;
        /**
         * If true, all URLs in the merged document are converted into hyperlinks.
         */
        convertUrlToHyperlink?: boolean;
        /**
         * The name of the output file.
         */
        outputFileBaseString?: string;
        /**
         * The path of the output folder.
         */
        outputFolderPath?: string;
    };
};

export type Error = {
    message: string;
    error_code: string;
};

export type MergeDataTagsRequest = BaseJobRequest & {
    params: {
        /**
         * The target document that will have its tags extracted.
         */
        targetDocument: string;
        /**
         * The data source file to be used for extracting and matching the tags.
         */
        dataSource?: string;
        /**
         * The filter applied for tags. Accepts multiple values.
         */
        filter?: Array<'all' | 'text' | 'image' | 'qr'>;
        /**
         * If true, the information for associated page items is added to the tags extracted from the document.
         */
        includePageItemIdentifiers?: boolean;
    };
};

/**
 * Inputs for the link remapping request.
 */
export type RemapLinksRequest = {
    assets: Array<InputAsset>;
    params: {
        /**
         * The InDesign documents in which links need to be remapped.
         */
        targetDocument: Array<string>;
        /**
         * Array of link mappings containing source and destination URIs.
         */
        dataSource: Array<{
            /**
             * File path/resource URI for the existing link that needs to be remapped.
             */
            sourceURI: string;
            /**
             * AEM URI that will replace the existing link.
             */
            destinationURI: string;
        }>;
    };
    outputs?: Array<OutputAsset>;
};

export type DocumentInfoRequest = BaseJobRequest & {
    params: {
        /**
         * The document to be used for data extraction.
         */
        targetDocument: string;
        /**
         * Settings for extracting page information.
         */
        pageInfo?: {
            /**
             * If true, return pages information.
             */
            enabled?: boolean;
        };
        /**
         * Settings for extracting link information.
         */
        linkInfo?: {
            /**
             * If true, return links information.
             */
            enabled?: boolean;
        };
        /**
         * Settings for extracting font information.
         */
        fontInfo?: {
            /**
             * If true, return fonts information.
             */
            enabled?: boolean;
        };
        /**
         * Settings for extracting page item information.
         */
        pageItemInfo?: {
            /**
             * If true, return page items details.
             */
            enabled?: boolean;
        };
        /**
         * Settings for extracting text story information.
         */
        textStoryInfo?: {
            /**
             * If true, return text stories information.
             */
            enabled?: boolean;
        };
    };
};

export type ConvertToInDesignRequest = BaseJobRequestWithOutput & {
    params: {
        /**
         * Array of PDF documents to convert. Each entry corresponds to the filename of the PDF document to convert. Currently supports one document at a time.
         */
        targetDocuments: [
            string
        ];
        /**
         * The MIME type of the output file.
         */
        outputMediaType: 'application/x-indesign' | 'application/vnd.adobe.indesign-idml-package';
        /**
         * If true, all links (images and other assets) from the PDF are embedded directly in the resulting INDD/IDML file. If false (default), the INDD/IDML file is created with external links, and all assets are provided in a separate folder within the output ZIP.
         */
        embedLinks?: boolean;
        /**
         * The name of the output ZIP file. If not specified, defaults to 'output.zip'.
         */
        outputFilebaseString?: string;
    };
};

/**
 * Response data returned when PDF to InDesign conversion is successful. This data is returned in the `data` field of the succeeded status response. The output is always a ZIP file containing subfolders for each converted PDF with the requested INDD/IDML file and associated assets.
 */
export type ConvertToInDesignResponse = {
    /**
     * Array of conversion outputs. Each item provides information about the conversion result for a specific input PDF.
     */
    outputs?: Array<{
        /**
         * Path to the output folder for the particular input PDF file within the ZIP archive.
         */
        outputPath?: string;
        /**
         * Name of the input PDF file that was converted.
         */
        input?: string;
        /**
         * Warnings encountered during conversion.
         */
        warnings?: {
            /**
             * Array of links that are missing or inaccessible in the converted document.
             */
            missingLinks?: Array<string>;
            /**
             * Array of fonts that are not available in the runtime environment.
             */
            missingFonts?: Array<string>;
            /**
             * Array of other warnings generated during conversion.
             */
            otherWarnings?: Array<string>;
        };
    }>;
};

export type CreateRenditionRequest = BaseJobRequestWithOutput & {
    params: {
        /**
         * The documents that will be processed and rendered. Currently, only one document at a time is supported.
         */
        targetDocuments: [
            string
        ];
        /**
         * The MIME type output of the rendered file.
         */
        outputMediaType: 'image/jpeg' | 'image/png' | 'application/pdf';
        /**
         * Specify `true` if you consider range as spread numbers. Use `false` if you treat range as pages.
         */
        exportingSpread?: boolean;
        /**
         * The page ranges, based on the index of the page within the document. The value can be 'All', as well as numeral ranges. If `exportingSpread` is true, this range would represent spread indices in the document.
         */
        pageRange?: string;
        /**
         * Defines the quality of the output.
         */
        quality?: 'low' | 'medium' | 'high' | 'maximum';
        /**
         * Specifies formatting options for the converted JPEG images.
         */
        renderingStyle?: 'baseline_encoding' | 'progressive_encoding';
        /**
         * Specifies the resolution of the final image.
         */
        resolution?: number;
        /**
         * Specifies formatting options for converted JPEG images.
         */
        colorSpace?: 'rgb' | 'cmyk' | 'gray';
        /**
         * Specify `true` to embed the color profile. Otherwise, use `false`.
         */
        embedColorProfile?: boolean;
        /**
         * If `true`, anti-aliasing is used for text and vectors during export.
         */
        antiAlias?: boolean;
        /**
         * If `true`, this simulates the effects of overprinting spot and processes colors in the same way they would occur with a print.
         */
        simulateOverprint?: boolean;
        /**
         * If `true`, the document's bleed settings are used in the exported JPEG.
         */
        useDocumentBleeds?: boolean;
        /**
         * This is the color settings file to be used for generating a rendition.
         */
        colorSettingsFile?: string;
        /**
         * If `true`, this uses a transparent background for the exported PNG. This is valid only for PNG renditions.
         */
        transparentBackground?: boolean;
        /**
         * Specify `true` to create separate PDF files for all the specified pages/spreads. This is applicable only in case of PDF rendition.
         */
        createSeparateFiles?: boolean;
        /**
         * Specify `true` to optimize the PDF for faster web viewing. This is applicable only in case of PDF rendition.
         */
        optimizeForFastWebView?: boolean;
        /**
         * Specify `true` for embedding page thumbnails. This is applicable only in case of PDF rendition.
         */
        embedPageThumbnails?: boolean;
        /**
         * If `true`, this displays bookmarks and table-of-contents entries as links in the bookmarks pane of the PDF document. If `false`, bookmarks are not exported. This is applicable only in case of PDF rendition.
         */
        includeBookmarks?: boolean;
        /**
         * If `true`, this includes the hyperlinks when exporting the document. This is applicable only in case of PDF rendition.
         */
        includeHyperlinks?: boolean;
        /**
         * If `true`, this makes non-printing objects visible in the PDF document. This is applicable only in case of PDF rendition.
         */
        exportNonprintingObjects?: boolean;
        /**
         * If `true`, this includes visible guides and baseline grids in the PDF. This is applicable only in case of PDF rendition. document.
         */
        exportGuidesAndGrids?: boolean;
        /**
         * If `true`, this creates a tagged PDF file. This is applicable only in case of PDF rendition.
         */
        createTaggedPDF?: boolean;
        /**
         * Specifies the option to draw interactive elements. This is applicable only in case of PDF rendition.
         */
        includeInteractiveElements?: 'do_not_include' | 'appearance_only';
        /**
         * This indicates the image layers to be exported. This is applicable only in case of PDF rendition.
         */
        exportWhichLayers?: 'export_all_layers' | 'export_visible_layers' | 'export_visible_printable_layers';
        /**
         * File path reference to a `.joboptions` file (Adobe PDF preset file) containing custom PDF export settings. This file must be included as part of the input assets. It defines detailed PDF output configurations such as compression, color management, and security settings. When provided, this takes precedence over the `pdfPreset` attribute. Only applicable when generating PDF output.
         */
        jobOptionsFile?: string;
        /**
         * The export style to be used. This is applicable only in case of PDF rendition.
         */
        pdfPreset?: 'High Quality Print' | 'PDF/X-1a:2001' | 'PDF/X-3:2002' | 'PDF/X-4:2008' | 'Press Quality' | 'Smallest File Size';
        /**
         * The name of the output file.
         */
        outputFileBaseString?: string;
        /**
         * The path of the output folder.
         */
        outputFolderPath?: string;
    };
};

/**
 * Response containing list of registered custom scripts
 */
export type CustomScriptsListResponse = {
    capabilities?: Array<CustomScriptDetails>;
    paging?: {
        /**
         * URL for the next page of results
         */
        nextUrl?: string;
    };
};

/**
 * Details of a custom script
 */
export type CustomScriptDetails = {
    /**
     * Version of the custom script
     */
    version?: string;
    /**
     * URL that was generated during registration
     */
    url?: string;
    /**
     * Pre-signed URL for downloading the script (valid for 30 minutes)
     */
    downloadurl?: string;
    /**
     * Registration date of the script
     */
    createdDate?: string;
    /**
     * Name of the custom script
     */
    scriptName?: string;
    /**
     * Strategy used to determine the InDesign app version for this script
     */
    appVersionStrategy?: 'latest_version' | 'fixed_major_version' | 'fixed_major_and_minor_version';
    /**
     * Major version of the InDesign app required for this script
     */
    majorAppVersion?: string;
    /**
     * Minor version of the InDesign app required for this script
     */
    minorAppVersion?: string;
};

/**
 * Request body for updating app version configuration for a custom script
 */
export type AppVersionUpdateRequest = {
    /**
     * Strategy for determining the InDesign app version to use. latest_version uses the most recent version, fixed_major_version locks to a major version, fixed_major_and_minor_version locks to a specific version.
     */
    appVersionStrategy: 'latest_version' | 'fixed_major_version' | 'fixed_major_and_minor_version';
    /**
     * Major version of the InDesign app. Required when appVersionStrategy is fixed_major_version or fixed_major_and_minor_version.
     */
    majorAppVersion?: string;
    /**
     * Minor version of the InDesign app. Required when appVersionStrategy is fixed_major_and_minor_version.
     */
    minorAppVersion?: string;
};

/**
 * Information about a registered InDesign app version
 */
export type AppVersionInfo = {
    /**
     * The product name
     */
    product?: string;
    /**
     * Major version of the InDesign app
     */
    majorAppVersion?: string;
    /**
     * Minor version of the InDesign app
     */
    minorAppVersion?: string;
    /**
     * Status of this app version
     */
    status?: 'active' | 'preview';
};

/**
 * The job event response object.
 */
export type BaseEvent = {
    /**
     * The GUID for the job.
     */
    jobId?: string;
};

export type NotstartedEvent = BaseEvent & {
    /**
     * The current state of the job.
     */
    status?: 'not_started';
};

export type RunningEvent = BaseEvent & {
    /**
     * The current state of the job.
     */
    status?: 'running';
    /**
     * A description of the current running state.
     */
    message?: string;
};

export type SucceededEvent = BaseEvent & {
    /**
     * The current state of the job.
     */
    status?: 'succeeded';
    /**
     * The output response from the current state of the job.
     */
    data?: {
        [key: string]: unknown;
    };
    /**
     * The data returned from the execution of the job. If the data size is between 250 KB and 20 MB, it will be provided as a pre-signed URL. If it is larger than 20 MB, the job will fail.
     */
    dataURL?: string;
    /**
     * A list of URLs for all the generated assets.
     */
    outputs?: {
        [key: string]: unknown;
    };
};

export type FailedEvent = BaseEvent & {
    /**
     * The current state of the job.
     */
    status?: 'failed';
    /**
     * A list of errors that caused the job to fail.
     */
    errors?: Array<{
        /**
         * The error code for the failure.
         */
        error_code?: string;
        /**
         * The error message for the failure
         */
        message?: string;
        /**
         * The source file of the error, if applicable.
         */
        source?: string;
        /**
         * A URL related to an asset causing the failure(if any), if applicable.
         */
        url?: string;
    }>;
};

export type PartialSuccessEvent = BaseEvent & {
    /**
     * The current state of the job.
     */
    status?: 'partial_success';
    /**
     * The output response from the current state of the job.
     */
    data?: {
        [key: string]: unknown;
    };
    /**
     * The data returned from the execution of the job. If the data size is between 250 KB and 20 MB, it will be provided as a pre-signed URL. If it is larger than 20 MB, the job will fail.
     */
    dataURL?: string;
    /**
     * A list of URLs for all the successfully generated assets.
     */
    outputs?: {
        [key: string]: unknown;
    };
    /**
     * A list of errors that occurred during a partially successful job.
     */
    errors?: Array<{
        /**
         * The error code for the partial failure.
         */
        error_code?: string;
        /**
         * The error message for the partial failure
         */
        message?: string;
        /**
         * The source file of the partial failure error, if applicable.
         */
        source?: string;
        /**
         * A URL related to an asset causing the partial failure(if any), if applicable.
         */
        url?: string;
    }>;
};

export type DataMergeData = {
    /**
     * This job request object specifies parameters for merging the data with the given template.
     */
    body: MergeDataRequest;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/merge-data';
};

export type DataMergeErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Too Many Requests
     */
    429: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type DataMergeError = DataMergeErrors[keyof DataMergeErrors];

export type DataMergeResponses = {
    /**
     * The job has been accepted for processing.
     */
    202: {
        /**
         * The job ID.
         */
        jobId?: string;
        /**
         * The status URL.
         */
        statusUrl?: string;
    };
};

export type DataMergeResponse = DataMergeResponses[keyof DataMergeResponses];

export type DataMergeTagsData = {
    /**
     * This job request object specifies parameters for retrieving the data merge tags.
     */
    body: MergeDataTagsRequest;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/merge-data-tags';
};

export type DataMergeTagsErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Too Many Requests
     */
    429: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type DataMergeTagsError = DataMergeTagsErrors[keyof DataMergeTagsErrors];

export type DataMergeTagsResponses = {
    /**
     * The job has been accepted for processing.
     */
    202: {
        /**
         * The job ID.
         */
        jobId?: string;
        /**
         * The status URL.
         */
        statusUrl?: string;
    };
};

export type DataMergeTagsResponse = DataMergeTagsResponses[keyof DataMergeTagsResponses];

export type RemapLinksData = {
    /**
     * Job request object that specifies parameters for remapping links in the InDesign document.
     */
    body: RemapLinksRequest;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * Bearer token generated for the AEM technical account without the bearer keyword.
         */
        'x-aem-token': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/remap-links';
};

export type RemapLinksErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type RemapLinksError = RemapLinksErrors[keyof RemapLinksErrors];

export type RemapLinksResponses = {
    /**
     * The job has been accepted for processing.
     */
    202: {
        /**
         * The job ID.
         */
        jobId?: string;
        /**
         * The status URL.
         */
        statusUrl?: string;
    };
};

export type RemapLinksResponse = RemapLinksResponses[keyof RemapLinksResponses];

export type RenditionJobData = {
    /**
     * This object specifies parameters for the JPEG, PNG or PDF output.
     */
    body: CreateRenditionRequest;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/create-rendition';
};

export type RenditionJobErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Too Many Requests
     */
    429: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type RenditionJobError = RenditionJobErrors[keyof RenditionJobErrors];

export type RenditionJobResponses = {
    /**
     * The job has been accepted for processing.
     */
    202: {
        /**
         * The job ID.
         */
        jobId?: string;
        /**
         * The status URL.
         */
        statusUrl?: string;
    };
};

export type RenditionJobResponse = RenditionJobResponses[keyof RenditionJobResponses];

export type ListCustomScriptsData = {
    body?: never;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
    };
    url: '/v3/scripts';
};

export type ListCustomScriptsErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ListCustomScriptsError = ListCustomScriptsErrors[keyof ListCustomScriptsErrors];

export type ListCustomScriptsResponses = {
    /**
     * List of registered custom scripts
     */
    200: CustomScriptsListResponse;
};

export type ListCustomScriptsResponse = ListCustomScriptsResponses[keyof ListCustomScriptsResponses];

export type SubmitCustomScriptData = {
    /**
     * The custom script bundle, in ZIP format. This package describes the script to the app engine.
     */
    body: {
        [key: string]: unknown;
    };
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/scripts';
};

export type SubmitCustomScriptErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Too Many Requests
     */
    429: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type SubmitCustomScriptError = SubmitCustomScriptErrors[keyof SubmitCustomScriptErrors];

export type SubmitCustomScriptResponses = {
    /**
     * Status of a job execution.
     */
    202: {
        /**
         * The name of the custom script, as specified in the custom script manifest.
         */
        capability?: string;
        /**
         * The version of the custom script, as specified in the custom script manifest.
         */
        version?: string;
        /**
         * The URL to submit an execution request for the custom script.
         */
        url?: string;
    };
};

export type SubmitCustomScriptResponse = SubmitCustomScriptResponses[keyof SubmitCustomScriptResponses];

export type ExecuteCustomScriptData = {
    /**
     * This job request object specifies parameters for the execution of the custom script.
     */
    body: BaseJobRequestWithOutput;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path: {
        /**
         * script_id as reported in the response to custom script submit request.
         */
        script_id: string;
        /**
         * The name of the custom script, specified in the custom script manifest.
         */
        script_name: string;
    };
    query?: never;
    url: '/v3/{script_id}/{script_name}';
};

export type ExecuteCustomScriptErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Too Many Requests
     */
    429: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ExecuteCustomScriptError = ExecuteCustomScriptErrors[keyof ExecuteCustomScriptErrors];

export type ExecuteCustomScriptResponses = {
    /**
     * The job has been accepted for processing.
     */
    202: {
        /**
         * The job ID.
         */
        jobId?: string;
        /**
         * The status URL.
         */
        statusUrl?: string;
    };
};

export type ExecuteCustomScriptResponse = ExecuteCustomScriptResponses[keyof ExecuteCustomScriptResponses];

export type DeleteCustomScriptData = {
    body?: never;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path: {
        /**
         * Name of the custom script to delete
         */
        script_name: string;
    };
    query?: never;
    url: '/v3/scripts/{script_name}';
};

export type DeleteCustomScriptErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type DeleteCustomScriptError = DeleteCustomScriptErrors[keyof DeleteCustomScriptErrors];

export type DeleteCustomScriptResponses = {
    /**
     * Script successfully deleted
     */
    204: void;
};

export type DeleteCustomScriptResponse = DeleteCustomScriptResponses[keyof DeleteCustomScriptResponses];

export type GetCustomScriptDetailsData = {
    body?: never;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path: {
        /**
         * Name of the custom script
         */
        script_name: string;
    };
    query?: never;
    url: '/v3/scripts/{script_name}';
};

export type GetCustomScriptDetailsErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type GetCustomScriptDetailsError = GetCustomScriptDetailsErrors[keyof GetCustomScriptDetailsErrors];

export type GetCustomScriptDetailsResponses = {
    /**
     * Details of the custom script
     */
    200: CustomScriptDetails;
};

export type GetCustomScriptDetailsResponse = GetCustomScriptDetailsResponses[keyof GetCustomScriptDetailsResponses];

export type UpdateScriptAppVersionData = {
    /**
     * Configuration for the app version strategy. The majorAppVersion and minorAppVersion fields are optional and their requirement depends on the selected strategy.
     */
    body: AppVersionUpdateRequest;
    headers: {
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
    };
    path: {
        /**
         * Name of the custom script to update
         */
        script_name: string;
    };
    query?: never;
    url: '/v3/scripts/{script_name}/app-version';
};

export type UpdateScriptAppVersionErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type UpdateScriptAppVersionError = UpdateScriptAppVersionErrors[keyof UpdateScriptAppVersionErrors];

export type UpdateScriptAppVersionResponses = {
    /**
     * App version configuration updated successfully
     */
    200: {
        message?: string;
    };
};

export type UpdateScriptAppVersionResponse = UpdateScriptAppVersionResponses[keyof UpdateScriptAppVersionResponses];

export type ListAppVersionsData = {
    body?: never;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/app-versions';
};

export type ListAppVersionsErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ListAppVersionsError = ListAppVersionsErrors[keyof ListAppVersionsErrors];

export type ListAppVersionsResponses = {
    /**
     * List of registered app versions for the product
     */
    200: Array<AppVersionInfo>;
};

export type ListAppVersionsResponse = ListAppVersionsResponses[keyof ListAppVersionsResponses];

export type GetDocumentInfoData = {
    /**
     * This job request object specifies parameters for extracting document information.
     */
    body: DocumentInfoRequest;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/document-info';
};

export type GetDocumentInfoErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Too Many Requests
     */
    429: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type GetDocumentInfoError = GetDocumentInfoErrors[keyof GetDocumentInfoErrors];

export type GetDocumentInfoResponses = {
    /**
     * The job has been accepted for processing.
     */
    202: {
        /**
         * The job ID.
         */
        jobId?: string;
        /**
         * The status URL.
         */
        statusUrl?: string;
    };
};

export type GetDocumentInfoResponse = GetDocumentInfoResponses[keyof GetDocumentInfoResponses];

export type GetDocumentInfoJobStatusData = {
    body?: never;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path: {
        /**
         * The ID of the Document Info job you want to see the status of. This comes from the response of the Document Info request.
         */
        'document-info_job_id': string;
    };
    query?: never;
    url: '/v3/status/{document-info_job_id}';
};

export type GetDocumentInfoJobStatusResponses = {
    /**
     * Status of a Document Info job execution.
     */
    200: NotstartedEvent | RunningEvent | SucceededEvent | FailedEvent | PartialSuccessEvent;
};

export type GetDocumentInfoJobStatusResponse = GetDocumentInfoJobStatusResponses[keyof GetDocumentInfoJobStatusResponses];

export type ConvertPdfToInDesignData = {
    /**
     * This job request object specifies parameters for converting PDF to InDesign format.
     */
    body: ConvertToInDesignRequest;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/convert-pdf-to-indesign';
};

export type ConvertPdfToInDesignErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Too Many Requests
     */
    429: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type ConvertPdfToInDesignError = ConvertPdfToInDesignErrors[keyof ConvertPdfToInDesignErrors];

export type ConvertPdfToInDesignResponses = {
    /**
     * The job has been accepted for processing.
     */
    202: {
        /**
         * The job ID.
         */
        jobId?: string;
        /**
         * The status URL.
         */
        statusUrl?: string;
    };
};

export type ConvertPdfToInDesignResponse = ConvertPdfToInDesignResponses[keyof ConvertPdfToInDesignResponses];

export type GetConvertPdfToInDesignJobStatusData = {
    body?: never;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path: {
        /**
         * The ID of the Convert PDF to InDesign job you want to see the status of. This comes from the response of the Convert PDF to InDesign request.
         */
        'convert-pdf-to-indesign_job_id': string;
    };
    query?: never;
    url: '/v3/status/{convert-pdf-to-indesign_job_id}';
};

export type GetConvertPdfToInDesignJobStatusErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Too Many Requests
     */
    429: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type GetConvertPdfToInDesignJobStatusError = GetConvertPdfToInDesignJobStatusErrors[keyof GetConvertPdfToInDesignJobStatusErrors];

export type GetConvertPdfToInDesignJobStatusResponses = {
    /**
     * Status of a Convert to InDesign job execution.
     */
    200: NotstartedEvent | RunningEvent | SucceededEvent | FailedEvent | PartialSuccessEvent;
};

export type GetConvertPdfToInDesignJobStatusResponse = GetConvertPdfToInDesignJobStatusResponses[keyof GetConvertPdfToInDesignJobStatusResponses];

export type GetJobStatusData = {
    body?: never;
    headers: {
        /**
         * The authorization token with bearer "token_value". For example: `Bearer <access_token>`.
         */
        Authorization: string;
        /**
         * The API key as defined in Adobe's Developer Console.
         */
        'x-api-key': string;
        /**
         * This is the identifier for Adobe Identity Management Service (IMS) as defined in Adobe's Developer Console. This is optional.
         */
        'x-gw-ims-org-id'?: string;
    };
    path: {
        /**
         * The ID of the job you want to see the status of. This comes from the response of the executed job request.
         */
        id: string;
    };
    query?: {
        /**
         * Number of output items to return per page when outputs are paginated. Defaults to 10.
         */
        size?: number;
        /**
         * Zero-based page index to retrieve when outputs are paginated. Defaults to 0.
         */
        page?: number;
    };
    url: '/v3/status/{id}';
};

export type GetJobStatusErrors = {
    /**
     * Bad Parameter
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not Found
     */
    404: Error;
    /**
     * Too Many Requests
     */
    429: Error;
    /**
     * Internal Server Error
     */
    500: Error;
};

export type GetJobStatusError = GetJobStatusErrors[keyof GetJobStatusErrors];

export type GetJobStatusResponses = {
    /**
     * Status of an API Job execution.
     */
    200: NotstartedEvent | RunningEvent | SucceededEvent | FailedEvent | PartialSuccessEvent;
};

export type GetJobStatusResponse = GetJobStatusResponses[keyof GetJobStatusResponses];
