// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApplyAutoToneData, ApplyAutoToneErrors, ApplyAutoToneResponses, ApplyEditsData, ApplyEditsErrors, ApplyEditsResponses, ApplyPresetData, ApplyPresetErrors, ApplyPresetFromXmpContentData, ApplyPresetFromXmpContentErrors, ApplyPresetFromXmpContentResponses, ApplyPresetResponses, AutoStraightenImageData, AutoStraightenImageErrors, AutoStraightenImageResponses, LrJobStatusData, LrJobStatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new LightroomSdk()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class LightroomSdk extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<LightroomSdk>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        LightroomSdk.__registry.set(this, args?.key);
    }
    
    /**
     * Auto-straighten
     *
     * Auto-straighten an image by applying the Auto Upright transformation.
     */
    public autoStraightenImage<ThrowOnError extends boolean = false>(options: Options<AutoStraightenImageData, ThrowOnError>) {
        return (options.client ?? this.client).post<AutoStraightenImageResponses, AutoStraightenImageErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/lrService/autoStraighten',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Auto-tone
     *
     * Automatically correct exposure, contrast, sharpness, and saturation on an image.
     */
    public applyAutoTone<ThrowOnError extends boolean = false>(options: Options<ApplyAutoToneData, ThrowOnError>) {
        return (options.client ?? this.client).post<ApplyAutoToneResponses, ApplyAutoToneErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/lrService/autoTone',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Apply Lightroom edits
     *
     * Apply one or more Lightroom edits (exposure, contrast, sharpness, saturation) to an image.
     */
    public applyEdits<ThrowOnError extends boolean = false>(options: Options<ApplyEditsData, ThrowOnError>) {
        return (options.client ?? this.client).post<ApplyEditsResponses, ApplyEditsErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/lrService/edit',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Apply Lightroom presets
     *
     * Apply one or more XMP Lightroom presets to the given image, by using the given preset XMP file(s).
     */
    public applyPreset<ThrowOnError extends boolean = false>(options: Options<ApplyPresetData, ThrowOnError>) {
        return (options.client ?? this.client).post<ApplyPresetResponses, ApplyPresetErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/lrService/presets',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Add XMP to image
     *
     * Apply XMP-based Lightroom preset to an image. XMP content is passed inline to the API.
     */
    public applyPresetFromXmpContent<ThrowOnError extends boolean = false>(options: Options<ApplyPresetFromXmpContentData, ThrowOnError>) {
        return (options.client ?? this.client).post<ApplyPresetFromXmpContentResponses, ApplyPresetFromXmpContentErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/lrService/xmp',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get status
     *
     * Get job status of a Lightroom job.
     */
    public lrJobStatus<ThrowOnError extends boolean = false>(options: Options<LrJobStatusData, ThrowOnError>) {
        return (options.client ?? this.client).get<LrJobStatusResponses, unknown, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/lrService/status/{jobId}',
            ...options
        });
    }
}
