// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApplyAutoCropAsyncData, ApplyAutoCropAsyncErrors, ApplyAutoCropAsyncResponses, ApplyDepthBlurAsyncData, ApplyDepthBlurAsyncErrors, ApplyDepthBlurAsyncResponses, ConvertToActionsJsonAsyncData, ConvertToActionsJsonAsyncErrors, ConvertToActionsJsonAsyncResponses, CreateArtboardAsyncData, CreateArtboardAsyncErrors, CreateArtboardAsyncResponses, CreateDocumentAsyncData, CreateDocumentAsyncErrors, CreateDocumentAsyncResponses, CreateMaskAsyncData, CreateMaskAsyncErrors, CreateMaskAsyncResponses, CreateRenditionAsyncData, CreateRenditionAsyncErrors, CreateRenditionAsyncResponses, EditTextLayerAsyncData, EditTextLayerAsyncErrors, EditTextLayerAsyncResponses, FacadeJobStatusData, FacadeJobStatusErrors, FacadeJobStatusResponses, FillMaskedAreasData, FillMaskedAreasErrors, FillMaskedAreasResponses, GetDocumentManifestAsyncData, GetDocumentManifestAsyncErrors, GetDocumentManifestAsyncResponses, GetJobStatusData, GetJobStatusErrors, GetJobStatusResponses, MaskBodyPartsData, MaskBodyPartsErrors, MaskBodyPartsResponses, MaskObjectsData, MaskObjectsErrors, MaskObjectsResponses, ModifyDocumentAsyncData, ModifyDocumentAsyncErrors, ModifyDocumentAsyncResponses, PlayPhotoshopActionsAsyncData, PlayPhotoshopActionsAsyncErrors, PlayPhotoshopActionsAsyncResponses, PlayPhotoshopActionsJsonAsyncData, PlayPhotoshopActionsJsonAsyncErrors, PlayPhotoshopActionsJsonAsyncResponses, PsJobStatusData, PsJobStatusResponses, RefineMaskData, RefineMaskErrors, RefineMaskResponses, RemoveBackgroundAsyncData, RemoveBackgroundAsyncErrors, RemoveBackgroundAsyncResponses, RemoveBackgroundData, RemoveBackgroundErrors, RemoveBackgroundResponses, ReplaceSmartObjectAsyncData, ReplaceSmartObjectAsyncErrors, ReplaceSmartObjectAsyncResponses, SenseiJobStatusData, SenseiJobStatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new PhotoshopSdk()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class PhotoshopSdk extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<PhotoshopSdk>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        PhotoshopSdk.__registry.set(this, args?.key);
    }
    
    /**
     * Get status - mask
     *
     * This endpoint returns the status of a job for a Remove Background and Create Mask operation. The schema of a 200 response varies depending on the status of the job.
     */
    public senseiJobStatus<ThrowOnError extends boolean = false>(options: Options<SenseiJobStatusData, ThrowOnError>) {
        return (options.client ?? this.client).get<SenseiJobStatusResponses, unknown, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/sensei/status/{jobId}',
            ...options
        });
    }
    
    /**
     * Remove background v1 (Deprecated)
     *
     * ⚠️ **DEPRECATED**: This endpoint is deprecated and will no longer be accessible after Oct 15, 2025. Use `/v2/remove-background` instead. For more information, see the [Deprecation Announcement](https://developer.adobe.com/firefly-services/docs/photoshop/getting_started/deprecation_announcement/). This endpoint will identify the main subject of your image and removes the background automatically. It also provides options to return a PNG file in 4 channel RGBA or 3 channel RGB format. To check the status of this process, utilize the `Get Status - Mask` endpoint.
     *
     * @deprecated
     */
    public removeBackgroundAsync<ThrowOnError extends boolean = false>(options: Options<RemoveBackgroundAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<RemoveBackgroundAsyncResponses, RemoveBackgroundAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/sensei/cutout',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Remove background v2
     *
     * This endpoint allows you to remove the background from an image. The request is processed asynchronously and the status of the running job can be checked with the Get Status endpoint.
     */
    public removeBackground<ThrowOnError extends boolean = false>(options: Options<RemoveBackgroundData, ThrowOnError>) {
        return (options.client ?? this.client).post<RemoveBackgroundResponses, RemoveBackgroundErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/v2/remove-background',
            ...options
        });
    }
    
    /**
     * Get status - v2
     *
     * Retrieve the status of a running Remove Background job by providing the job ID. The job ID is obtained from the response of the asynchronous Remove Background API call.
     */
    public facadeJobStatus<ThrowOnError extends boolean = false>(options: Options<FacadeJobStatusData, ThrowOnError>) {
        return (options.client ?? this.client).get<FacadeJobStatusResponses, FacadeJobStatusErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/v2/status/{jobId}',
            ...options
        });
    }
    
    /**
     * Create mask
     *
     * ⚠️ **DEPRECATED**: This endpoint is deprecated and will no longer be accessible after Oct 15, 2025. Use `/v2/remove-background` instead. For more information, see the [Deprecation Announcement](https://developer.adobe.com/firefly-services/docs/photoshop/getting_started/deprecation_announcement/).This endpoint uses the Remove Background AI/ML model to return a PNG file with a mask applied around the subject. To check the status of this process, utilize the `Get Status - Mask` endpoint.
     *
     * @deprecated
     */
    public createMaskAsync<ThrowOnError extends boolean = false>(options: Options<CreateMaskAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<CreateMaskAsyncResponses, CreateMaskAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/sensei/mask',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get status
     *
     * Get the job status of a Photoshop job.
     */
    public psJobStatus<ThrowOnError extends boolean = false>(options: Options<PsJobStatusData, ThrowOnError>) {
        return (options.client ?? this.client).get<PsJobStatusResponses, unknown, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/status/{jobId}',
            ...options
        });
    }
    
    /**
     * Extract document manifest
     *
     * Extract metadata from PSD document, including general file and layer information.
     */
    public getDocumentManifestAsync<ThrowOnError extends boolean = false>(options: Options<GetDocumentManifestAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<GetDocumentManifestAsyncResponses, GetDocumentManifestAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/documentManifest',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Create PSD
     *
     * Create new PSD with layers.
     */
    public createDocumentAsync<ThrowOnError extends boolean = false>(options: Options<CreateDocumentAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<CreateDocumentAsyncResponses, CreateDocumentAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/documentCreate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Apply photoshop edits
     *
     * Apply basic layer edits (name, state, etc.), add/edit adjustment, pixel, and shape layers.
     */
    public modifyDocumentAsync<ThrowOnError extends boolean = false>(options: Options<ModifyDocumentAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<ModifyDocumentAsyncResponses, ModifyDocumentAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/documentOperations',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Create renditions
     *
     * Create flat image representations of a PSD in multiple formats.
     */
    public createRenditionAsync<ThrowOnError extends boolean = false>(options: Options<CreateRenditionAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<CreateRenditionAsyncResponses, CreateRenditionAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/renditionCreate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Replace smart object
     *
     * Replace Smart Object in a PSD.
     */
    public replaceSmartObjectAsync<ThrowOnError extends boolean = false>(options: Options<ReplaceSmartObjectAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<ReplaceSmartObjectAsyncResponses, ReplaceSmartObjectAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/smartObject',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Run photoshop actions
     *
     * Executes Photoshop Action file against a PSD, JPEG, PNG, or TIFF.
     */
    public playPhotoshopActionsAsync<ThrowOnError extends boolean = false>(options: Options<PlayPhotoshopActionsAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<PlayPhotoshopActionsAsyncResponses, PlayPhotoshopActionsAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/photoshopActions',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Run actionJSON
     *
     * Execute given Photoshop Action specified in actionJSON format.
     */
    public playPhotoshopActionsJsonAsync<ThrowOnError extends boolean = false>(options: Options<PlayPhotoshopActionsJsonAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<PlayPhotoshopActionsJsonAsyncResponses, PlayPhotoshopActionsJsonAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/actionJSON',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Convert to actionJSON
     *
     * Convert an ATN file to actionJSON format.
     */
    public convertToActionsJsonAsync<ThrowOnError extends boolean = false>(options: Options<ConvertToActionsJsonAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<ConvertToActionsJsonAsyncResponses, ConvertToActionsJsonAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/actionJsonCreate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Product crop
     *
     * This endpoint identifies the subject of the input file and automatically crops the image to keep the subject in the center. Check the status of this process with the `Get Status` endpoint.
     */
    public applyAutoCropAsync<ThrowOnError extends boolean = false>(options: Options<ApplyAutoCropAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<ApplyAutoCropAsyncResponses, ApplyAutoCropAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/productCrop',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Depth blur
     *
     * Apply depth blur to an image input.
     */
    public applyDepthBlurAsync<ThrowOnError extends boolean = false>(options: Options<ApplyDepthBlurAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<ApplyDepthBlurAsyncResponses, ApplyDepthBlurAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/depthBlur',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Edit text layer
     *
     * Change the contents of a text layer in a PSD, e.g. for localization.
     */
    public editTextLayerAsync<ThrowOnError extends boolean = false>(options: Options<EditTextLayerAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<EditTextLayerAsyncResponses, EditTextLayerAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/text',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Create artboards
     *
     * Create artboards from multiple PSD inputs.
     */
    public createArtboardAsync<ThrowOnError extends boolean = false>(options: Options<CreateArtboardAsyncData, ThrowOnError>) {
        return (options.client ?? this.client).post<CreateArtboardAsyncResponses, CreateArtboardAsyncErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/pie/psdService/artboardCreate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Generate object and background masks
     *
     * Given an image, this API generates semantic masks for the foreground objects and a list of background masks that segment the background elements of the image. Each mask includes a label and a URL for the mask image. To check the status of this process, utilize the `Get Status - V1` endpoint.
     */
    public maskObjects<ThrowOnError extends boolean = false>(options: Options<MaskObjectsData, ThrowOnError>) {
        return (options.client ?? this.client).post<MaskObjectsResponses, MaskObjectsErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/v1/mask-objects',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Generate human item masks
     *
     * This endpoint processes an input image of a human, then identifies and creates masks for various items and sections on the body including sunglasses, hats, upper body apparel, lower body apparel, left arm, right arm, and more. The API returns an array of masks corresponding to each detected item and body part. To check the status of this process, utilize the `Get Status - V1` endpoint.
     */
    public maskBodyParts<ThrowOnError extends boolean = false>(options: Options<MaskBodyPartsData, ThrowOnError>) {
        return (options.client ?? this.client).post<MaskBodyPartsResponses, MaskBodyPartsErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/v1/mask-body-parts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Refine mask
     *
     * This endpoint allows you to refine and improve the quality of existing masks. The API will enhance the edges and details of the provided masks to create more precise and accurate results. To check the status of this process, utilize the `Get Status - V1` endpoint.
     */
    public refineMask<ThrowOnError extends boolean = false>(options: Options<RefineMaskData, ThrowOnError>) {
        return (options.client ?? this.client).post<RefineMaskResponses, RefineMaskErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/v1/refine-mask',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Fill masked areas
     *
     * This endpoint allows you to inpaint masked areas within an image. The API will remove the objects represented by these masks and inpaint the specified areas. Provide a list of masks corresponding to the regions you wish to modify. To check the status of this process, utilize the `Get Status - V1` endpoint.
     */
    public fillMaskedAreas<ThrowOnError extends boolean = false>(options: Options<FillMaskedAreasData, ThrowOnError>) {
        return (options.client ?? this.client).post<FillMaskedAreasResponses, FillMaskedAreasErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/v1/fill-masked-areas',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get status - v1
     *
     * This endpoint allows you to check the status of an asynchronous job for a masking operation. The schema of a 200 response varies depending on the status of the job. A job with a `succeeded` status will include the results in the response and the result objects vary depending on the operation.
     */
    public getJobStatus<ThrowOnError extends boolean = false>(options: Options<GetJobStatusData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetJobStatusResponses, GetJobStatusErrors, ThrowOnError>({
            security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
            url: '/v1/status/{jobId}',
            ...options
        });
    }
}
