// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://image.adobe.io' | (string & {});
};

/**
 * JobError
 *
 * Any errors reported in the requested output.
 */
export type JobError = {
    /**
     * The error type.
     */
    type?: string;
    /**
     * The error code.
     */
    code?: string;
    /**
     * The error description.
     */
    title?: string;
    /**
     * The internal error code.
     */
    error_code?: string;
    /**
     * The details of the error returned.
     */
    details?: Array<ErrorDetails>;
};

/**
 * InputValidationError
 *
 * Any errors reported in the requested output.
 */
export type InputValidationError = {
    /**
     * The error type.
     */
    type?: string;
    /**
     * The error code.
     */
    code?: string;
    /**
     * The error description.
     */
    title?: string;
    /**
     * The details of the error returned.
     */
    details?: Array<InputValidationErrorDetail>;
};

/**
 * TrialLimitExceededError
 *
 * Any errors reported in the requested output.
 */
export type TrialLimitExceededError = {
    /**
     * The error type.
     */
    type?: string;
    /**
     * The error code.
     */
    code?: string;
    /**
     * The error description.
     */
    title?: string;
    /**
     * The details of the error returned.
     */
    details?: string;
};

/**
 * InputValidationErrorDetail
 *
 * Details of the input validation error returned.
 */
export type InputValidationErrorDetail = {
    /**
     * The name of the input parameter.
     */
    allowedValues?: string;
    /**
     * The reason for the error.
     */
    reason?: string;
};

/**
 * StorageDetails
 *
 * A file located on Adobe's cloud or a supported external service.
 */
export type StorageDetails = {
    /**
     * A pre-signed GET URL.
     */
    href: string;
    storage: StorageType;
};

/**
 * SenseiColor
 *
 * Color space for output image
 */
export type SenseiColor = {
    space?: ColorSpaceType;
};

/**
 * ColorSpaceType
 *
 * Color space for output image
 */
export type ColorSpaceType = 'rgb' | 'rgba';

/**
 * SenseiOutputDetails
 *
 * A PNG file.
 */
export type SenseiOutputDetails = {
    /**
     * A pre-signed POST URL to the output file.
     */
    href: string;
    storage: StorageType;
    mask?: MaskFormat;
    color?: SenseiColor;
    /**
     * If the file already exists, indicates if the output file should be overwritten. Will eventually support eTags. Only applies to CC Storage.
     */
    overwrite?: boolean;
};

/**
 * SenseiJobApiResponse
 */
export type SenseiJobApiResponse = {
    /**
     * The job ID requested.
     */
    jobId?: string;
    /**
     * Created timestamp of the job (YYYY-DD-MMThh:mm:ss.mmmmmZ).
     */
    created?: string;
    /**
     * Modified timestamp of the job (YYYY-DD-MMThh:mm:ss.mmmmmZ).
     */
    modified?: string;
    status?: JobStatus;
    output?: SenseiOutputDetails;
    errors?: JobError;
    _links?: JobStatusLink;
};

/**
 * JobStatusLink
 */
export type JobStatusLink = {
    self?: SelfLink;
};

/**
 * RemoveBackgroundRequest
 */
export type RemoveBackgroundRequest = {
    input: StorageDetails;
    output: SenseiOutputDetails;
};

/**
 * CreateMaskRequest
 */
export type CreateMaskRequest = {
    input: StorageDetails;
    output: SenseiOutputDetails;
};

/**
 * JobStatusLinkResponse
 */
export type JobStatusLinkResponse = {
    _links?: JobStatusLink;
};

/**
 * IccProfileDetails
 */
export type IccProfileDetails = {
    imageMode?: ImageModeType;
    input?: StorageDetails;
    profileName?: ColorProfileType;
};

/**
 * SmartObjectOutputDetails
 *
 * An output object.
 */
export type SmartObjectOutputDetails = {
    /**
     * A pre-signed POST URL to the output file.
     */
    href: string;
    storage: StorageType;
    type: ImageFormatType;
    /**
     * If the file already exists, indicates if the output file should be overwritten. Will eventually support eTags. Only applies to CC Storage.
     */
    overwrite?: boolean;
    /**
     * The width, in pixels, of the renditions. A width of 0 generates a full size rendition. Height is generated automatically using the aspect ratio. Only supported for image rendition.
     */
    width?: number;
    /**
     * The quality of the renditions for JPEG. The range is 1 to 7, 7 being the highest quality.
     */
    quality?: number;
    compression?: CompressionType;
};

/**
 * ActionOutputDetails
 *
 * An output object.
 */
export type ActionOutputDetails = {
    /**
     * A pre-signed POST URL to the output file.
     */
    href: string;
    storage: StorageType;
    type: ImageFormatType;
    /**
     * If the file already exists, indicates if the output file should be overwritten. Will eventually support eTags. Only applies to CC Storage.
     */
    overwrite?: boolean;
    /**
     * The quality of the renditions for JPEG. The range is 1 to 7, 7 being the highest quality.
     */
    quality?: number;
    compression?: CompressionType;
};

/**
 * PsOutputDetails
 *
 * An output object.
 */
export type PsOutputDetails = {
    /**
     * A pre-signed POST URL to the output file.
     */
    href: string;
    storage: StorageType;
    type: ImageFormatType;
    /**
     * If the file already exists, indicates if the output file should be overwritten. Will eventually support eTags. Only applies to CC Storage.
     */
    overwrite?: boolean;
    /**
     * The width, in pixels, of the renditions. A width of 0 generates a full size rendition. Height is generated automatically using the aspect ratio. Only supported for image rendition.
     */
    width?: number;
    /**
     * The size, in pixels, of the renditions. When width is 0, maxWidth can be provided to get the rendition size. maxWidth when less than document width gets precedence over width. Height is not necessary as the rendition generate will automatically maintain the aspect ratio.
     */
    maxWidth?: number;
    /**
     * The quality of the renditions for JPEG. The range is 1 to 7, 7 being the highest quality.
     */
    quality?: number;
    compression?: CompressionType;
    trimToCanvas?: TrimToCanvasType;
    /**
     * An array of layer objects.
     * By including this array you are signaling that you'd like a rendition created from these layer id's or layer names. Excluding it will generate a document-level rendition.
     */
    layers?: Array<LayerReference>;
    iccProfile?: IccProfileDetails;
};

/**
 * RenditionLinkDetails
 *
 * A rendition object.
 */
export type RenditionLinkDetails = {
    /**
     * The rendition location.
     */
    href?: string;
    storage?: StorageType;
    /**
     * The requested rendition width in pixels.
     */
    width?: number;
    type?: ImageFormatType;
};

/**
 * ManifestJobApiResponse
 */
export type ManifestJobApiResponse = {
    /**
     * The job ID requested.
     */
    jobId?: string;
    /**
     * The outputs requested.
     */
    outputs?: Array<ManifestJobStatusOutputDetails>;
    _links?: JobStatusLink;
};

/**
 * PsJobApiResponse
 */
export type PsJobApiResponse = {
    /**
     * The job ID requested.
     */
    jobId?: string;
    /**
     * API output details.
     */
    outputs?: Array<JobOutputDetails>;
    _links?: JobStatusLink;
};

/**
 * Photoshop Job response.
 */
export type PsJobResponse = ManifestJobApiResponse | PsJobApiResponse;

/**
 * DocumentManifestRequest
 */
export type DocumentManifestRequest = {
    /**
     * An array of input objects. Each input object represents a file to be processed.
     */
    inputs: Array<StorageDetails>;
    options?: DocumentManifestOptions & unknown;
};

/**
 * LayerPosition
 */
export type LayerPosition = {
    insertAbove?: LayerReference;
    insertBelow?: LayerReference;
    insertInto?: LayerReference;
    insertTop?: boolean;
    insertBottom?: boolean;
};

/**
 * DeleteDetails
 *
 * Indicates you want to delete the layer, identified by the `id` or `name`. Note the object is currently empty but leaves room for further enhancements.
 */
export type DeleteDetails = {
    /**
     * Indicates that child layers are included when deleting a group layer.
     */
    includeChildren?: boolean;
    /**
     * The layer ID.
     */
    id?: number;
    /**
     * The layer name. You can identify a layer by id or name. That makes either id or name a required field.
     */
    name?: string;
};

/**
 * LayerReference
 *
 * A layer reference object.
 */
export type LayerReference = {
    /**
     * The id of the layer. Use either `id` OR `name`.
     */
    id?: number;
    /**
     * The name of the layer. Use either `id` OR `name`.
     */
    name?: string;
};

/**
 * CreateDocumentRequest
 */
export type CreateDocumentRequest = {
    /**
     * An array of output objects. Each output object represents a file to be created.
     */
    outputs: Array<PsOutputDetails>;
    options: DocumentCreateOptions;
};

/**
 * ModifyDocumentRequest
 */
export type ModifyDocumentRequest = {
    /**
     * An array of input objects. Each input object represents a file to be processed.
     */
    inputs: Array<StorageDetails>;
    /**
     * An array of output objects. Each output object represents a file to be created.
     */
    outputs: Array<PsOutputDetails>;
    options: DocumentOperationOptions;
};

/**
 * CreateRenditionRequest
 */
export type CreateRenditionRequest = {
    /**
     * An array of input objects. Only one input object is currently supported.
     */
    inputs: Array<StorageDetails>;
    /**
     * An array of output objects.
     */
    outputs: Array<PsOutputDetails>;
};

/**
 * ReplaceSmartObjectRequest
 */
export type ReplaceSmartObjectRequest = {
    /**
     * An array of input objects. Only one input object is currently supported.
     */
    inputs: Array<StorageDetails>;
    /**
     * An array of output objects.
     */
    outputs: Array<SmartObjectOutputDetails>;
    options: SmartObjectOptions;
};

/**
 * PlayPhotoshopActionsRequest
 */
export type PlayPhotoshopActionsRequest = {
    /**
     * An array of input objects. Only one input object is currently supported.
     */
    inputs: Array<StorageDetails>;
    /**
     * An array of output objects.
     */
    outputs: Array<ActionOutputDetails>;
    options: ActionOptions;
};

/**
 * PlayPhotoshopActionsJsonRequest
 */
export type PlayPhotoshopActionsJsonRequest = {
    /**
     * An array of input objects. Only one input object is currently supported.
     */
    inputs: Array<StorageDetails>;
    /**
     * An array of output objects.
     */
    outputs: Array<ActionOutputDetails>;
    options: ActionJsonOptions;
};

/**
 * ConvertToActionsJsonRequest
 */
export type ConvertToActionsJsonRequest = {
    /**
     * An array of input action sets in ATN format. Only one input object is currently supported.
     */
    inputs: Array<StorageDetails>;
    options?: ActionJsonCreateOptions;
};

/**
 * ApplyAutoCropRequest
 */
export type ApplyAutoCropRequest = {
    /**
     * An array of input objects. Only one input object is currently supported.
     */
    inputs: Array<StorageDetails>;
    /**
     * An array of output objects
     */
    outputs: Array<ActionOutputDetails>;
    options: CropOptions;
};

/**
 * ApplyDepthBlurRequest
 */
export type ApplyDepthBlurRequest = {
    /**
     * An array of input objects. We currently only support one input object
     */
    inputs: Array<StorageDetails>;
    /**
     * An array of output objects
     */
    outputs: Array<ActionOutputDetails>;
    options?: DepthBlurDetails;
};

/**
 * EditTextLayerRequest
 */
export type EditTextLayerRequest = {
    /**
     * An array of input objects. We currently only support one input object
     */
    inputs: Array<StorageDetails>;
    /**
     * An array of output objects
     */
    outputs: Array<ActionOutputDetails>;
    options: TextOptions;
};

/**
 * CreateArtboardRequest
 */
export type CreateArtboardRequest = {
    options: ArtboardDetails;
    /**
     * An array of output objects
     */
    outputs: Array<PsOutputDetails>;
};

/**
 * DocumentDetails
 */
export type DocumentDetails = {
    /**
     * In pixels
     */
    height: number;
    /**
     * In pixels
     */
    width: number;
    /**
     * In pixels per inch
     */
    resolution: number;
    fill: FillType;
    mode: ChannelModeType;
    depth?: DepthType;
};

/**
 * ManifestJobDocumentDetails
 */
export type ManifestJobDocumentDetails = {
    /**
     * The name of the document
     */
    name?: string;
    /**
     * In pixels
     */
    height?: number;
    /**
     * In pixels
     */
    width?: number;
    /**
     * The version of Photoshop used to create the document
     */
    photoshopBuild?: string;
    imageMode?: ImageModeType;
    bitDepth?: ChannelModeType;
    /**
     * The name of the ICC profile used for the document
     */
    iccProfileName?: string;
};

/**
 * ChildrenLayerDetails
 */
export type ChildrenLayerDetails = {
    /**
     * The layer ID. An ID of -1 is valid and indicates a PSD that only contains a background image and no layers.
     */
    id?: number;
    /**
     * The layer index.
     */
    index?: number;
    /**
     * If thumbnails were requested, a pre-signed GET URL to the thumbnail
     */
    thumbnail?: string;
    type?: LayerType;
    /**
     * The layer name.
     */
    name?: string;
    /**
     * Whether the layer is locked
     */
    locked?: boolean;
    /**
     * Whether the layer is visible
     */
    visible?: boolean;
    adjustments?: AdjustmentDetails;
    bounds?: Bounds;
    blendOptions?: BlendDetails;
    mask?: LayerMaskDetails;
    smartObject?: SmartObjectDetails;
    fill?: FillDetails;
    text?: TextLayerDetails;
};

/**
 * LayerDetails
 */
export type LayerDetails = {
    /**
     * The layer ID. An ID of -1 is valid and indicates a PSD that only contains a background image and no layers.
     */
    id?: number;
    /**
     * The layer index.
     */
    index?: number;
    /**
     * If thumbnails were requested, this is a pre-signed GET URL to the thumbnail.
     */
    thumbnail?: string;
    /**
     * An array of nested layer objects. Only layerSections (group layers) can include children.
     */
    children?: Array<ChildrenLayerDetails>;
    type?: LayerType;
    /**
     * The layer name.
     */
    name?: string;
    /**
     * Whether the layer is locked.
     */
    locked?: boolean;
    /**
     * Whether the layer is visible.
     */
    visible?: boolean;
    adjustments?: ManifestJobAdjustmentDetails;
    bounds?: Bounds;
    blendOptions?: BlendDetails;
    mask?: LayerMaskDetails;
    smartObject?: SmartObjectDetails;
    fill?: FillDetails;
    text?: TextLayerDetails;
};

/**
 * Action
 *
 * An object describing the input Photoshop Actions to play.
 */
export type Action = {
    storage?: StorageType & unknown;
    /**
     * Presigned GET URL
     */
    href?: string;
    /**
     * If you only want to execute a particular action, you may specify which action to play from the ActionSet
     */
    actionName?: string;
};

/**
 * ActionDetails
 *
 * Details of Actions from the ActionSet.
 */
export type ActionDetails = {
    /**
     * If you only want to execute a particular action, you may specify whcih action to convert from the ActionSet
     */
    actionName?: string;
};

/**
 * AdjustmentDetails
 *
 * Adjustment layer information.
 */
export type AdjustmentDetails = {
    brightnessContrast?: BrightnessContrast;
    exposure?: ExposureDetails;
    hueSaturation?: HueSaturation;
    colorBalance?: ColorBalance;
};

/**
 * ManifestJobAdjustmentDetails
 *
 * Adjustment layer information.
 */
export type ManifestJobAdjustmentDetails = {
    brightness_contrast?: BrightnessContrast;
    exposure?: ExposureDetails;
    hue_saturation?: HueSaturation;
    color_balance?: ColorBalance;
};

/**
 * BrightnessContrast
 *
 * Brightness and contrast settings.
 */
export type BrightnessContrast = {
    /**
     * The adjustment layer's brightness.
     */
    brightness?: number;
    /**
     * The adjustment layer's contrast.
     */
    contrast?: number;
};

/**
 * ExposureDetails
 *
 * Exposure settings.
 */
export type ExposureDetails = {
    /**
     * The layer's exposure.
     */
    exposure?: number;
    /**
     * The layer's offset.
     */
    offset?: number;
    /**
     * The layer's gamma correction.
     */
    gammaCorrection?: number;
};

/**
 * HueSaturation
 */
export type HueSaturation = {
    /**
     * Whether to colorize.
     */
    colorize?: boolean;
    /**
     * An array of hashes representing the 'master' channel (the remaining five channels of 'magentas', 'yellows', 'greens', etc. are not yet supported).
     */
    channels?: Array<ChannelDetails>;
};

/**
 * ColorBalance
 *
 * Color balance settings.
 */
export type ColorBalance = {
    /**
     * Whether to preserve luminosity.
     */
    preserveLuminosity?: boolean;
    /**
     * Shadow levels.
     */
    shadowLevels?: Array<number>;
    /**
     * Midtone levels.
     */
    midtoneLevels?: Array<number>;
    /**
     * Highlight levels.
     */
    highlightLevels?: Array<number>;
};

/**
 * Bounds
 *
 * The bounds of the layer.
 */
export type Bounds = {
    /**
     * The top position in pixels.
     */
    top?: number;
    /**
     * The left position in pixels.
     */
    left?: number;
    /**
     * The width in pixels.
     */
    width?: number;
    /**
     * The height in pixels.
     */
    height?: number;
};

/**
 * CharacterStyleDetails
 *
 * Character style settings.
 */
export type CharacterStyleDetails = {
    /**
     * The font size, in pixels.
     */
    size?: number;
    /**
     * The font's PostScript name to be used to set the font for this layer.
     */
    fontPostScriptName?: string;
    color?: ColorDetails;
    /**
     * The font's leading value, where leading is the distance between each line of text.
     */
    leading?: number;
    /**
     * The font's tracking value, where tracking is the horizontal spacing between a range of characters.
     */
    tracking?: number;
    baseline?: BaselineType;
    fontCaps?: FontCaps;
    autoKern?: AutoKernType;
    /**
     * Toggle strikethrough for selected text.
     */
    strikethrough?: boolean;
    /**
     * Toggle bold for selected text.
     */
    syntheticBold?: boolean;
    /**
     * Toggle italic for selected text.
     */
    syntheticItalic?: boolean;
    /**
     * Toggle underlining of text.
     */
    underline?: boolean;
    /**
     * Toggle text ligature, which are special characters in a font that combine two (or more).
     */
    ligature?: boolean;
    /**
     * Toggle automatic formatting of fractions: numbers separated by a slash (such as 1/2).
     */
    fractions?: boolean;
    /**
     * Toggle stylistic alternates, which formats stylized characters that create a purely aesthetic effect.
     */
    stylisticAlternates?: boolean;
    /**
     * The amount of vertical scaling to apply to the font.
     */
    verticalScale?: number;
    /**
     * The amount of horizontal scaling to apply to the font.
     */
    horizontalScale?: number;
};

/**
 * ParagraphStyleDetails
 *
 * Paragraph style settings.
 */
export type ParagraphStyleDetails = {
    alignment?: ParagraphStyleAlignmentType;
    /**
     * The amount of indent to add to the left margin.
     */
    startIndent?: number;
    /**
     * The amount of indent to add to the right margin.
     */
    endIndent?: number;
    /**
     * Toggle hyphenate for paragraph text.
     */
    hyphenate?: boolean;
    /**
     * The amount of indent to add to the first line of the paragraph.
     */
    firstLineIndent?: number;
    /**
     * The amount of space to add before the paragraph.
     */
    spaceBefore?: number;
    /**
     * The amount of space to add after the paragraph.
     */
    spaceAfter?: number;
};

/**
 * LayerMaskDetails
 *
 * An object describing the input mask replaced or added to the layer.
 */
export type LayerMaskDetails = {
    /**
     * Indicates if this is a clipped layer.
     */
    clip?: boolean;
    /**
     * Indicates whether a mask is enabled on that layer.
     */
    enabled?: boolean;
    /**
     * Indicates whether a mask is linked to the layer.
     */
    linked?: boolean;
    offset?: Offset;
};

/**
 * Offset
 *
 * Offset details.
 */
export type Offset = {
    /**
     * Offset to indicate horizontal move of the mask.
     */
    x?: number;
    /**
     * Offset to indicate vertical move of the mask.
     */
    y?: number;
};

/**
 * SmartObjectDetails
 *
 * Smart object details.
 */
export type SmartObjectDetails = {
    /**
     * Desired image format for the smart object.
     */
    type?: string;
    /**
     * Indicates if the smart object is linked. Currently we support embedded smart object only, which means "linked = false".
     */
    linked?: boolean;
    /**
     * Name of the embedded or linked smart object. Currently we support embedded smart object only.
     */
    name?: string;
    /**
     * Only for a linked smart object. Indicates the relative path for the linked smart object.
     */
    path?: string;
    /**
     * Only for an embedded smart object. Indicates the instance ID of the embedded smart object. This ID is unique and the value is derived from the RAW data of the document. `instanceId` may show a value as unknown, if the embedded smart object is generated using a non-Adobe application.
     */
    instanceId?: string;
};

/**
 * FillDetails
 */
export type FillDetails = {
    solidColor?: SolidColor;
};

/**
 * SolidColor
 */
export type SolidColor = {
    rgb: RgbColor;
};

/**
 * RgbColor
 *
 * An object describing the RGB color format in 8 bits.
 */
export type RgbColor = {
    red?: number;
    green?: number;
    blue?: number;
};

/**
 * FontColorRgb
 *
 * An object describing the RGB color format in 16 bits.
 */
export type FontColorRgb = {
    red?: number;
    green?: number;
    blue?: number;
};

/**
 * FontColorCmyk
 *
 * The font color settings for CMYK mode in 16-bit representation.
 */
export type FontColorCmyk = {
    cyan?: number;
    magenta?: number;
    yellowColor?: number;
    black?: number;
};

/**
 * FontColorGray
 *
 * The font color settings for gray mode in 16-bit representation.
 */
export type FontColorGray = {
    gray?: number;
};

/**
 * FontColorLab
 *
 * The font color settings for Lab mode in 16-bit representation.
 */
export type FontColorLab = {
    luminance?: number;
    a?: number;
    b?: number;
};

/**
 * TextLayerDetails
 *
 * Text settings.
 */
export type TextLayerDetails = {
    /**
     * The text string.
     */
    content?: string;
    /**
     * Character style settings. If the same supported attributes apply to all characters in the layer, then this will be an array of one item. Otherwise, each `characterStyle` object will have a 'from' and 'to' value indicating the range of characters that style applies to.
     */
    characterStyles?: Array<TextLayerCharacterStyleDetails>;
    /**
     * Paragraph style settings. If the same supported attributes apply to all characters in the layer then this will be an array of one item, otherwise each paragraph style object will have a 'from' and 'to' value indicating the range of characters that the style applies to.
     */
    paragraphStyles?: Array<TextLayerParagraphStyleDetails>;
};

/**
 * TextLayerCharacterStyleDetails
 */
export type TextLayerCharacterStyleDetails = {
    /**
     * The beginning of the range of characters that this character style applies to. Based on initial index of 0. For example a style applied to only the first two characters would be from=0 and to=1.
     */
    from?: number;
    /**
     * The ending of the range of characters that this character style applies to. Based on initial index of 0. For example a style applied to only the first two characters would be from=0 and to=1.
     */
    to?: number;
    /**
     * The font size in points.
     */
    fontSize?: number;
    /**
     * The font's PostScript name from the [list of supported fonts](../../getting_started/technical_usage_notes/index.md#photoshop-api-supported-fonts).
     */
    fontName?: string;
    orientation?: OrientationType;
    fontColor?: FontColorDetails;
};

/**
 * TextLayerParagraphStyleDetails
 *
 * If the same supported attributes apply to all characters in the layer then this will be an array of one item, otherwise each paragraph style object will have a 'from' and 'to' value indicating the range of characters that the style applies to.
 */
export type TextLayerParagraphStyleDetails = {
    /**
     * The beginning of the range of characters that this paragraph style applies to. Based on initial index of 0. For example a style applied to only the first two characters would be from=0 and to=1.
     */
    from?: number;
    /**
     * The ending of the range of characters that this paragraph style applies to. Based on initial index of 0. For example a style applied to only the first two characters would be from=0 and to=1.
     */
    to?: number;
    alignment?: AlignmentType;
};

/**
 * BlendDetails
 *
 * Blend options of a layer, including opacity and blend mode.
 */
export type BlendDetails = {
    /**
     * Indicates the opacity value of a layer.
     */
    opacity?: number;
    blendMode?: BlendModeType;
};

/**
 * AlignmentType
 *
 * The paragraph alignment.
 */
export type AlignmentType = 'left' | 'center' | 'right' | 'justify' | 'justifyLeft' | 'justifyCenter' | 'justifyRight';

/**
 * ParagraphStyleAlignmentType
 *
 * The paragraph alignment.
 */
export type ParagraphStyleAlignmentType = 'left' | 'center' | 'right' | 'justify' | 'justifyLeft' | 'justifyCenter' | 'justifyRight' | 'justifyAll';

/**
 * AntiAliasType
 *
 * The text's aliasing type which determines the smoothness of the jagged edges of the text.
 */
export type AntiAliasType = 'antiAliasNone' | 'antiAliasSharp' | 'antiAliasCrisp' | 'antiAliasStrong' | 'antiAliasSmooth' | 'antiAliasPlatformLCD' | 'antiAliasPlatformGray';

/**
 * AutoKernType
 *
 * The text's kerning setting. Optical: set based on the shape of the font. Metrics: uses kern pairs included in fonts.
 */
export type AutoKernType = 'opticalKern' | 'metricsKern';

/**
 * BasedOnType
 *
 * Based on type.
 */
export type BasedOnType = 'transparentPixels';

/**
 * BaselineType
 *
 * Indicates if the text is raised or lowered in relation to a font's baseline.
 */
export type BaselineType = 'subScript' | 'superScript';

/**
 * BlendModeType
 *
 * Blend mode of layer.
 */
export type BlendModeType = 'normal' | 'dissolve' | 'darken' | 'multiply' | 'colorBurn' | 'linearBurn' | 'darkerColor' | 'lighten' | 'screen' | 'colorDodge' | 'linearDodge' | 'lighterColor' | 'overlay' | 'softLight' | 'hardLight' | 'vividLight' | 'linearLight' | 'pinLight' | 'hardMix' | 'difference' | 'exclusion' | 'subtract' | 'divide' | 'hue' | 'saturation' | 'color' | 'luminosity';

/**
 * CanvasSize
 */
export type CanvasSize = {
    bounds: Bounds;
};

/**
 * ChannelDetails
 */
export type ChannelDetails = {
    channel?: ChannelType;
    hue?: number;
    saturation?: number;
    lightness?: number;
};

/**
 * ChannelType
 *
 * The channel type.
 */
export type ChannelType = 'master';

/**
 * ColorDetails
 *
 * Font color in RGB format.
 */
export type ColorDetails = {
    /**
     * The color red value.
     */
    red: number;
    /**
     * The color green value.
     */
    green: number;
    /**
     * The color blue value.
     */
    blue: number;
};

/**
 * CompressionType
 *
 * Desired PNG compression level.
 */
export type CompressionType = 'small' | 'medium' | 'large';

/**
 * DepthType
 *
 * Bit depth. This is either 8, 16 or 32 bit.
 */
export type DepthType = 8 | 16 | 32;

/**
 * OperationDocument
 */
export type OperationDocument = {
    canvasSize?: CanvasSize;
    imageSize?: ImageSize;
    trim?: Trim;
};

/**
 * EastAsianFeatures
 *
 * Text features specifically for East Asian languages.
 */
export type EastAsianFeatures = {
    textStyle?: TextStyleType & unknown;
};

/**
 * ErrorDetails
 *
 * Error details.
 */
export type ErrorDetails = {
    /**
     * The parameter name.
     */
    name?: string;
    /**
     * The error.
     */
    reason?: string;
};

/**
 * FillType
 *
 * Type of fill for the background layer.
 */
export type FillType = 'white' | 'backgroundColor' | 'transparent';

/**
 * FocalSelector
 *
 * Focal selector.
 */
export type FocalSelector = {
    /**
     * X coordinate.
     */
    x?: number;
    /**
     * Y coordinate.
     */
    y?: number;
};

/**
 * FontCaps
 *
 * The text's capitalization values.
 */
export type FontCaps = 'allCaps' | 'smallCaps';

/**
 * FontColorDetails
 */
export type FontColorDetails = {
    rgb?: FontColorRgb & unknown;
    cmyk?: FontColorCmyk & unknown;
    gray?: FontColorGray & unknown;
    lab?: FontColorLab & unknown;
};

/**
 * MaskFormatType
 *
 * Soft mask or binary mask.
 */
export type MaskFormatType = 'binary' | 'soft';

/**
 * ImageModeType
 *
 * The image mode.
 */
export type ImageModeType = 'grayscale' | 'rgb' | 'cmyk';

/**
 * ImageSize
 *
 * The size of the image
 */
export type ImageSize = {
    width: number;
    height: number;
};

/**
 * DocumentCreateLayer
 */
export type DocumentCreateLayer = {
    type: LayerType;
    input: StorageDetails & unknown;
    name?: string;
    /**
     * is the layer locked
     */
    locked?: boolean;
    /**
     * is the layer visible
     */
    visible?: boolean;
    adjustments?: AdjustmentDetails;
    bounds?: Bounds;
    children?: Array<ChildrenLayerDetails>;
    mask?: MaskDetails;
    smartObject?: SmartObject & unknown;
    fill?: FillDetails;
    text?: TextLayerDetails & unknown;
    blendOptions?: BlendDetails & unknown;
};

/**
 * DocumentOperationLayer
 */
export type DocumentOperationLayer = {
    /**
     * Indicates the layer to edit, by it's ID or name. Note the object is currently empty but leaves room for further enhancements. The layer block should contain changes from the original manifest. If you apply it to a group layer, you will be affecting the attributes of the group layer itself, not the child layers. This edit is supported for layer type `smartObject` and `fillLayer` only.
     */
    edit?: {
        [key: string]: unknown;
    };
    move?: MoveDetails;
    add?: LayerPosition;
    delete: DeleteDetails;
    /**
     * The layer ID.
     */
    id: number;
    /**
     * The layer index. Required when deleting a layer, otherwise not used.
     */
    index?: number;
    /**
     * A tree of layer objects representing the PSD layer structure extracted from the PSD document.
     */
    children?: Array<ChildrenLayerDetails>;
    type?: LayerType;
    input?: StorageDetails;
    name?: string;
    /**
     * is the layer locked
     */
    locked?: boolean;
    /**
     * is the layer visible
     */
    visible?: boolean;
    adjustments?: AdjustmentDetails;
    mask?: MaskDetails;
    bounds?: Bounds;
    smartObject?: SmartObject & unknown;
    fill?: FillDetails;
    text?: TextLayerDetails & unknown;
    blendOptions?: BlendDetails & unknown;
    horizontalAlign?: HorizontalAlignType;
    verticalAlign?: VerticalAlignType;
    /**
     * Indicates if the pixels need to proportionally fill into the entire canvas of the document.
     */
    fillToCanvas?: boolean;
};

/**
 * SmartObjectLayer
 */
export type SmartObjectLayer = {
    add?: LayerPosition;
    /**
     * the layer id
     */
    id?: number;
    name?: string;
    /**
     * is the layer locked
     */
    locked?: boolean;
    /**
     * is the layer visible
     */
    visible?: boolean;
    input: StorageDetails;
    bounds?: Bounds;
};

/**
 * TextOptionsLayer
 */
export type TextOptionsLayer = {
    /**
     * The name of the layer you want to insert. Use either ID or name.
     */
    name?: string;
    /**
     * The ID of the layer you want to insert. Use either ID or name.
     */
    id?: number;
    bounds?: Bounds;
    /**
     * Is the layer editable.
     */
    locked?: boolean;
    /**
     * Is the layer visible.
     */
    visible?: boolean;
    text?: TextDetails & unknown;
};

/**
 * RenditionLinks
 *
 * The rendition links.
 */
export type RenditionLinks = {
    /**
     * Array of rendition objects.
     */
    renditions?: Array<RenditionLinkDetails>;
};

/**
 * ManageMissingFonts
 *
 * Action to take if there are one or more missing fonts in the document. Using `fail` - the job will not succeed and the status will be set to `failed` with the details of the error provided in the `details` section in the status. Using `useDefault` - the job will succeed, however all the missing fonts will use the font: ArialMT.
 */
export type ManageMissingFonts = 'useDefault' | 'fail';

/**
 * MaskFormat
 */
export type MaskFormat = {
    format?: MaskFormatType;
};

/**
 * MaskDetails
 */
export type MaskDetails = {
    input?: StorageDetails;
    /**
     * Indicates if this is a clipped layer
     */
    clip?: boolean;
    /**
     * Indicates a mask is enabled on that layer or not
     */
    enabled?: boolean;
    /**
     * Indicates a mask is linked to the layer or not
     */
    linked?: boolean;
    offset?: Offset;
};

/**
 * ChannelModeType
 *
 * The document's bit/channel depth.
 */
export type ChannelModeType = 'bitmap' | 'greyscale' | 'indexed' | 'rgb' | 'cmyk' | 'hsl' | 'hsb' | 'multichannel' | 'duotone' | 'lab' | 'xyz';

/**
 * MoveDetails
 */
export type MoveDetails = {
    moveChildren?: boolean;
    insertAbove?: LayerReference;
    insertBelow?: LayerReference;
    insertInto?: LayerReference;
    insertTop?: boolean;
    insertBottom?: boolean;
};

/**
 * DocumentManifestOptions
 *
 * Available options to apply to all input files.
 */
export type DocumentManifestOptions = {
    thumbnails?: Thumbnails & unknown;
};

/**
 * DocumentCreateOptions
 */
export type DocumentCreateOptions = {
    manageMissingFonts?: ManageMissingFonts & unknown;
    /**
     * The PostScript name of the font to be used as the global default for the document. If this font is also missing, the option specified in `manageMissingFonts` will take effect.
     */
    globalFont?: string;
    /**
     * array of custom fonts needed in this document
     */
    fonts?: Array<StorageDetails>;
    document: DocumentDetails;
    /**
     * Array of layers to be created in the document.
     */
    layers?: Array<DocumentCreateLayer>;
};

/**
 * DocumentOperationOptions
 */
export type DocumentOperationOptions = {
    manageMissingFonts?: ManageMissingFonts & unknown;
    /**
     * The PostScript name of the font to be used as the global default. If this font is also missing, the option specified in `manageMissingFonts` will take effect
     */
    globalFont?: string;
    /**
     * array of custom fonts needed in this document
     */
    fonts?: Array<StorageDetails>;
    document?: OperationDocument;
    /**
     * Array of layers to be created in the document.
     */
    layers?: Array<DocumentOperationLayer>;
};

/**
 * SmartObjectOptions
 */
export type SmartObjectOptions = {
    /**
     * Array of Smart Object layers to be created in the document
     */
    layers: Array<SmartObjectLayer>;
};

/**
 * ActionOptions
 */
export type ActionOptions = {
    /**
     * Array of Photoshop Actions to play.
     */
    actions: Array<Action>;
    /**
     * array of custom pattern preset to be used in Photoshop Actions
     */
    patterns?: Array<StorageDetails>;
    /**
     * array of custom fonts needed in this document
     */
    fonts?: Array<StorageDetails>;
    /**
     * array of custom brushes needed in this document
     */
    brushes?: Array<StorageDetails>;
};

/**
 * ActionJsonOptions
 */
export type ActionJsonOptions = {
    /**
     * Array of Photoshop JSON-formatted Actions to play.
     */
    actionJSON: Array<{
        [key: string]: unknown;
    }>;
    /**
     * array of custom pattern preset to be used in Photoshop Actions
     */
    patterns?: Array<StorageDetails>;
    /**
     * array of custom fonts needed in this document
     */
    fonts?: Array<StorageDetails>;
    /**
     * array of custom brushes needed in this document
     */
    brushes?: Array<StorageDetails>;
    /**
     * Array of references to additional images, which can be referred by actionJson commands.
     */
    additionalImages?: Array<StorageDetails>;
};

/**
 * ActionJsonCreateOptions
 *
 * This block is needed only if you want to specify which action to convert from the ActionSet.
 */
export type ActionJsonCreateOptions = {
    /**
     * Array of action objects.
     */
    actions: [
        ActionDetails
    ];
};

/**
 * CropOptions
 */
export type CropOptions = {
    unit: UnitType & unknown;
    /**
     * The width to be added as padding.
     */
    width: number;
    /**
     * The height to be added as padding.
     */
    height: number;
};

/**
 * DepthBlurDetails
 */
export type DepthBlurDetails = {
    /**
     * The distance of the point to be in focus. 0 would be the nearest point, 100 would be the furthest point.
     */
    focalDistance?: number;
    /**
     * The range of the focal point.
     */
    focalRange?: number;
    focalSelector?: FocalSelector & unknown;
    /**
     * If enabled uses select subject to automatically select the prominent subject for focus. Also would override focalDistance.
     */
    focusSubject?: boolean;
    /**
     * The amount of blur to apply.
     */
    blurStrength?: number;
    /**
     * The amount of haze to apply.
     */
    haze?: number;
    /**
     * The value of the temperature to apply. -50 would be coldest and 50 would be the warmest setting.
     */
    temp?: number;
    /**
     * The amount of the tint to apply.
     */
    tint?: number;
    /**
     * The amount of the saturation to apply. -50 implies fully unsaturated colors and 50 will fully saturate the colors.
     */
    saturation?: number;
    /**
     * The amount of the brightness to apply.
     */
    brightness?: number;
    /**
     * The amount of the graining to add to the image.
     */
    grain?: number;
};

/**
 * TextOptions
 */
export type TextOptions = {
    manageMissingFonts?: ManageMissingFonts & unknown;
    /**
     * The PostScript name of the font to be used as the global default. If this font is also missing, the option specified in `manageMissingFonts` will take effect
     */
    globalFont?: string;
    /**
     * Array of text layer objects you wish to act upon.
     */
    layers: Array<TextOptionsLayer>;
    /**
     * Array of custom fonts needed in this document.
     */
    fonts?: Array<StorageDetails>;
};

/**
 * ArtboardDetails
 */
export type ArtboardDetails = {
    /**
     * An array of hashes describing the input files to edit. Each input object will be either 'external', 'adobe', 'azure' or 'dropbox'.
     */
    artboard: Array<StorageDetails>;
};

/**
 * OrientationType
 *
 * The text orientation.
 */
export type OrientationType = 'horizontal' | 'vertical';

/**
 * ManifestJobStatusOutputDetails
 */
export type ManifestJobStatusOutputDetails = {
    /**
     * the original input href
     */
    input?: string;
    /**
     * Created timestamp of the job (YYYY-DD-MMThh:mm:ss.mmmmmZ)
     */
    created?: string;
    /**
     * Modified timestamp of the job (YYYY-DD-MMThh:mm:ss.mmmmmZ)
     */
    modified?: string;
    status?: JobStatus;
    document?: ManifestJobDocumentDetails;
    /**
     * A tree of layer objects representing the PSD layer structure extracted from the PSD document.
     */
    layers?: Array<LayerDetails>;
};

/**
 * JobOutputDetails
 */
export type JobOutputDetails = {
    /**
     * the original input href
     */
    input?: string;
    /**
     * Created timestamp of the job (YYYY-DD-MMThh:mm:ss.mmmmmZ)
     */
    created?: string;
    /**
     * Modified timestamp of the job (YYYY-DD-MMThh:mm:ss.mmmmmZ)
     */
    modified?: string;
    status?: JobOutputStatus;
    _links?: RenditionLinks;
};

/**
 * ColorProfileType
 *
 * The name of the color profile.
 */
export type ColorProfileType = 'Adobe RGB (1998)' | 'Apple RGB' | 'ColorMatch RGB' | 'sRGB IEC61966-2.1' | 'Dot Gain 10%' | 'Dot Gain 15%' | 'Dot Gain 20%' | 'Dot Gain 25%' | 'Dot Gain 30%' | 'Gray Gamma 1.8' | 'Gray Gamma 2.2';

/**
 * SelfLink
 *
 * Self link.
 */
export type SelfLink = {
    /**
     * Job Status URL.
     */
    href?: string;
};

/**
 * SmartObject
 *
 * An object describing the attributes specific to creating or editing a smart object. `SmartObject` properties operate on the input smart object file. When creating a linked smart object, this is a required. When creating an embedded smart object, it is optional.
 */
export type SmartObject = {
    /**
     * Indicates if this Smart Object is linked. Currently we support Embedded Smart Object only which means "linked = false".
     */
    linked?: boolean;
};

/**
 * JobStatus
 *
 * Job status.
 */
export type JobStatus = 'pending' | 'running' | 'succeeded' | 'failed';

/**
 * JobOutputStatus
 *
 * The child job status. Using `pending` - the request has been accepted and is waiting to start. Using `running` - the child job is running. Using `uploading` - files have been generated and are uploading to destination. Using `succeeded` - the child job has succeeded. Using `failed` - the child job has failed.
 */
export type JobOutputStatus = 'pending' | 'running' | 'uploading' | 'succeeded' | 'failed';

/**
 * StorageType
 *
 * Storage platforms supported.
 */
export type StorageType = 'external' | 'azure' | 'dropbox';

/**
 * TextDetails
 *
 * Supported text layer attributes.
 */
export type TextDetails = {
    /**
     * The content of the text layer.
     */
    content?: string;
    orientation?: OrientationType;
    /**
     * The text's rotation in angle.
     */
    rotate?: number;
    antiAlias?: AntiAliasType & unknown;
    eastAsianFeatures?: EastAsianFeatures & unknown;
    /**
     * Array of character style objects. Any of the `characterStyles` property is required.
     */
    characterStyles?: Array<CharacterStyleDetails>;
    /**
     * Array of paragraph style objects. Any of the `paragraphStyles` properties is required.
     */
    paragraphStyles?: Array<ParagraphStyleDetails>;
    textType?: TextType & unknown;
};

/**
 * TextStyleType
 *
 * Base line direction for text style.
 */
export type TextStyleType = 'cross' | 'rotated' | 'withSream';

/**
 * TextType
 *
 * The type of text's contents, point or paragraph.
 */
export type TextType = 'point' | 'paragraph';

/**
 * Thumbnails
 *
 * Include pre-signed GET URLs to small preview thumbnails for any renderable layer.
 */
export type Thumbnails = {
    type?: ThumbnailType & unknown;
};

/**
 * Trim
 */
export type Trim = {
    basedOn: BasedOnType;
};

/**
 * TrimToCanvasType
 *
 * Use this if the renditions needs to be of Canvas size. Using `True` trims the renditions to Canvas size, while `False` makes the renditions Layer Size.
 */
export type TrimToCanvasType = true | false;

/**
 * ImageFormatType
 *
 * The desired image format. Using `image/vnd.adobe.photoshop` - create a new PSD file. Using `image/jpeg`, `image/png`, `image/tiff` - create a new JPEG, PNG or TIFF rendition. Certain image modes (RGB, CMYK, greyscale, etc.) must be converted to another image mode before a rendition can be created. With TIFF requested, Multichannel and Duotone will convert to RGB. With PNG requested, CMYK, HSL, HSB, Multichannel, Duotone, Lab and XYZ will convert to RGB.
 */
export type ImageFormatType = 'image/vnd.adobe.photoshop' | 'image/jpeg' | 'image/png' | 'image/tiff' | 'vnd.adobe.photoshop';

/**
 * LayerType
 *
 * The layer type. Using `layer` - a pixel layer. Using `textLayer` - a text layer. Using `adjustmentLayer` - an adjustment layer. Using `layerSection` - a grouping layer. Using `smartObject` - a smart object. Using `backgroundLayer` - a background layer. Using `fillLayer` - a fill layer.
 */
export type LayerType = 'layer' | 'textLayer' | 'adjustmentLayer' | 'smartObject' | 'fillLayer' | 'backgroundLayer' | 'layerSection';

/**
 * ThumbnailType
 *
 * Desired image format.
 */
export type ThumbnailType = 'image/jpeg' | 'image/png' | 'image/tiff';

/**
 * UnitType
 *
 * Unit for width and height.
 */
export type UnitType = 'Pixels' | 'Percent';

/**
 * HorizontalAlignType
 *
 * Indicates the relative horizontal position of the layer with respect to the canvas of the document.
 */
export type HorizontalAlignType = 'left' | 'center' | 'right';

/**
 * VerticalAlignType
 *
 * Indicates the relative vertical position of the layer with respect to the canvas of the document.
 */
export type VerticalAlignType = 'top' | 'center' | 'bottom';

export type UrlResource = {
    /**
     * The URL of the resource. Only these listed domains are accepted in the request:
     * <ul><li><code>amazonaws.com</code></li><li><code>windows.net</code></li><li><code>dropboxusercontent.com</code></li><li><code>assets.frame.io</code></li><li><code>storage.googleapis.com</code></li></ul>
     */
    url: string;
};

export type RemoveBgInputImage = {
    /**
     * The source path for the input image. Dimensions of the image should not be greater than 6000px X 6000px. The image media type must be `image/jpeg`, `image/png`, `image/webp`, or `image/tiff`.
     */
    source: UrlResource;
};

/**
 * The mode of background removal.
 */
export type RemoveBgMode = 'cutout' | 'mask' | 'psd';

/**
 * The media type of the output image. By default this will match the input source file format.
 */
export type RemoveBgOutputImageMediaType = 'image/jpeg' | 'image/png' | 'image/webp' | 'image/vnd.adobe.photoshop';

export type RemoveBgOutputImageOptions = {
    mediaType?: RemoveBgOutputImageMediaType;
};

export type RemoveBgColor = {
    /**
     * The red value of the color.
     */
    red: number;
    /**
     * The green value of the color.
     */
    green: number;
    /**
     * The blue value of the color.
     */
    blue: number;
    /**
     * The transparency value. 0 is fully transparent and 1 is fully opaque.
     */
    alpha: number;
};

export type RemoveBackgroundV2Request = {
    /**
     * The image to be processed.
     */
    image: RemoveBgInputImage;
    mode?: RemoveBgMode;
    /**
     * The options for the output image.
     */
    output?: RemoveBgOutputImageOptions;
    /**
     * If true, the image returned is cropped to the cutout border. Transparent pixels are removed.
     */
    trim?: boolean;
    /**
     * The background color.
     */
    backgroundColor?: RemoveBgColor;
    /**
     * If the value is greater than 0, automatically removes colored reflections that have been left on the main subject by the background.
     */
    colorDecontamination?: number;
};

export type JobLinkResponse = {
    /**
     * The job ID for the asynchronous job.
     */
    jobId: string;
    /**
     * The URL to check the status of the asynchronous job.
     */
    statusUrl: string;
};

export type JobStatusPollPayload = {
    status: JobStatus;
    /**
     * The job ID.
     */
    jobId: string;
};

/**
 * Succeeded
 */
export type JobStatusSucceededResponse = {
    status: 'succeeded';
    /**
     * The job ID.
     */
    jobId: string;
    result: {
        outputs?: Array<{
            destination?: {
                /**
                 * The output URL
                 */
                url?: string;
            };
            /**
             * The media type of the output
             */
            mediaType?: string;
        }>;
    };
};

export type FillMaskedAreasInputImage = {
    /**
     * The source of the input image. Dimensions of the image should not be greater than (4000px X 4000px).
     */
    source: UrlResource;
};

export type FillMaskedAreasRequest = {
    /**
     * The image to be processed.
     */
    image: FillMaskedAreasInputImage;
    /**
     * The areas of the image represented by this list of masks will be inpainted.
     */
    masks: Array<FillMaskedAreasInputImage>;
};

/**
 * The media type of the input image.
 */
export type MaskBodyPartsImageMediaType = 'image/jpeg' | 'image/png';

export type MaskBodyPartsInputImage = {
    /**
     * The source of the input image. Dimensions of the image should not be greater than (4000px X 4000px).
     */
    source: UrlResource;
};

/**
 * The media type of the mask.
 */
export type MaskBodyPartsMaskMediaType = 'image/png';

export type MaskBodyPartsInputMask = {
    /**
     * The URL of the mask. Dimensions of the mask should not be greater than (4000px X 4000px).
     */
    source: UrlResource;
};

export type MaskBodyPartsRequest = {
    /**
     * The input image.
     */
    image: MaskBodyPartsInputImage;
    /**
     * The mask of the subject in the input image.
     */
    mask: MaskBodyPartsInputMask;
};

/**
 * The media type of the input image.
 */
export type MaskObjectsInputImageMediaType = 'image/jpeg' | 'image/png';

export type MaskObjectsInputImage = {
    /**
     * The source of the input image. Dimensions of the image should not be greater than (4000px X 4000px).
     */
    source: UrlResource;
};

export type MaskObjectsRequest = {
    /**
     * The input image.
     */
    image: MaskObjectsInputImage;
};

/**
 * The media type of the input image.
 */
export type RefineMaskImageMediaType = 'image/jpeg' | 'image/png';

export type RefineMaskInputImage = {
    /**
     * The source of the input image. Dimensions of the image should not be greater than (4000px X 4000px).
     */
    source: UrlResource;
};

export type RefineMaskRequest = {
    /**
     * The input image.
     */
    image: RefineMaskInputImage;
    /**
     * The mask in the input image that needs to be refined.
     */
    mask: RefineMaskInputImage;
    /**
     * When `true`, this returns an RGBA image where the masked area has been further refined with color decontamination. A `false` value (default) means that the output will simply be the refined mask.
     */
    colorDecontamination?: boolean;
};

export type OutputImageDetails = {
    /**
     * Details of the location where the output image is located.
     */
    destination: UrlResource;
    /**
     * Media type of the output image.
     */
    mediaType: 'image/jpeg' | 'image/png';
};

export type FillMaskedAreasJobApiResponse = {
    status: JobStatus;
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * The output image.
     */
    image: OutputImageDetails;
};

export type ImageBoundingBox = {
    /**
     * The x coordinate of the upper-left corner of the bounding box. The origin (0,0) is at the upper-left corner of the image.
     */
    x: number;
    /**
     * The y coordinate of the upper-left corner of the bounding box. The origin (0,0) is at the upper-left corner of the image.
     */
    y: number;
    /**
     * The width of the bounding box, starting from the x coordinate.
     */
    width: number;
    /**
     * The height of the bounding box, starting from the y coordinate.
     */
    height: number;
};

export type MaskBodyPartsOutputImage = {
    /**
     * The label of the identified body part.
     */
    label: string;
    /**
     * The bounding box of the identified body part.
     */
    boundingBox: ImageBoundingBox;
    /**
     * The probability or confidence score of the match.
     */
    score: number;
    /**
     * Details of the location where the mask of the identified body part is located.
     */
    destination: UrlResource;
    /**
     * Media type of the mask of the identified body part.
     */
    mediaType: 'image/png';
};

export type MaskBodyPartsJobApiResponse = {
    status: JobStatus;
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * An array of output image masks.
     */
    masks: Array<MaskBodyPartsOutputImage>;
};

export type MaskObjectsOutputImage = {
    /**
     * The label of the identified object or area of interest.
     */
    label: string;
    /**
     * The bounding box of the object or area of interest.
     */
    boundingBox: ImageBoundingBox;
    /**
     * The probability or confidence score of the match.
     */
    score: number;
    /**
     * Details of the location where the mask is located.
     */
    destination: UrlResource;
    /**
     * Media type of the mask.
     */
    mediaType: 'image/png';
};

export type MaskObjectsJobApiResponse = {
    status: JobStatus;
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * List of masks representing foreground objects.
     */
    semanticMasks: Array<MaskObjectsOutputImage>;
    /**
     * List of masks representing background regions.
     */
    backgroundMasks: Array<MaskObjectsOutputImage>;
};

export type RefineMaskOutputImage = {
    /**
     * Details of the location where the refined mask or image is located.
     */
    destination: UrlResource;
    /**
     * Media type of the refined mask or image.
     */
    mediaType: 'image/jpeg' | 'image/png';
    /**
     * The bounding box of the refined mask or image.
     */
    boundingBox: ImageBoundingBox;
};

export type RefineMaskJobApiResponse = {
    status: JobStatus;
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * The refined mask. This will only be attached to the response when mask is specified as an input. Only applicable when colorDecontamination is false.
     */
    mask?: RefineMaskOutputImage;
    /**
     * The image with color decontamination. This will only be attached to the response when mask is specified as an input. Only applicable when colorDecontamination is true.
     */
    image?: RefineMaskOutputImage;
};

export type JobStatusResponse = {
    status: JobStatus;
    /**
     * The results of the job if completed.
     */
    results: {
        [key: string]: unknown;
    };
};

/**
 * Response when a job is currently being processed. The job has started but is not yet complete.
 */
export type JobStatusRunning = {
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * The status of the job.
     */
    status: 'running';
};

/**
 * Response when a job has completed successfully. In addition to the jobId and status, the response includes the results of the job which vary depending on the operation.
 */
export type JobStatusSucceeded = {
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * The status of the job.
     */
    status: 'succeeded';
};

/**
 * Response when a job has failed during processing. Contains error details explaining what went wrong.
 */
export type JobStatusFailed = {
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * The status of the job.
     */
    status: 'failed';
    /**
     * The error code.
     */
    error_code: string;
    /**
     * The error message.
     */
    message: string;
};

/**
 * Response when a job has been created but processing has not yet begun. This status indicates the job is queued and waiting to start.
 */
export type JobStatusNotStarted = {
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * The status of the job.
     */
    status: 'not_started';
};

export type SenseiJobStatusData = {
    body?: never;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events.
         */
        'x-gw-ims-org-id'?: string;
    };
    path: {
        /**
         * The job ID.
         */
        jobId: string;
    };
    query?: never;
    url: '/sensei/status/{jobId}';
};

export type SenseiJobStatusResponses = {
    /**
     * Job status
     */
    200: SenseiJobApiResponse;
};

export type SenseiJobStatusResponse = SenseiJobStatusResponses[keyof SenseiJobStatusResponses];

export type RemoveBackgroundAsyncData = {
    /**
     * The input image and the cutout mask parameters
     */
    body: RemoveBackgroundRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/sensei/cutout';
};

export type RemoveBackgroundAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Unauthorized
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Too many requests
     */
    429: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type RemoveBackgroundAsyncError = RemoveBackgroundAsyncErrors[keyof RemoveBackgroundAsyncErrors];

export type RemoveBackgroundAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type RemoveBackgroundAsyncResponse = RemoveBackgroundAsyncResponses[keyof RemoveBackgroundAsyncResponses];

export type RemoveBackgroundData = {
    body: RemoveBackgroundV2Request;
    headers: {
        /**
         * The bearer token for the user. This is the access token.
         */
        Authorization: string;
        /**
         * The API key/Client ID
         */
        'x-api-key': string;
        /**
         * The content type of the request. The value is `application/json`.
         */
        'Content-Type': string;
    };
    path?: never;
    query?: never;
    url: '/v2/remove-background';
};

export type RemoveBackgroundErrors = {
    /**
     * Unauthorized
     */
    401: JobError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Too Many Requests
     */
    429: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type RemoveBackgroundError = RemoveBackgroundErrors[keyof RemoveBackgroundErrors];

export type RemoveBackgroundResponses = {
    /**
     * Accepted
     */
    202: JobLinkResponse;
};

export type RemoveBackgroundResponse = RemoveBackgroundResponses[keyof RemoveBackgroundResponses];

export type FacadeJobStatusData = {
    body?: never;
    path: {
        /**
         * The job ID from the response of the Remove Background API call.
         */
        jobId: string;
    };
    query?: never;
    url: '/v2/status/{jobId}';
};

export type FacadeJobStatusErrors = {
    /**
     * Bad Request
     */
    400: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type FacadeJobStatusError = FacadeJobStatusErrors[keyof FacadeJobStatusErrors];

export type FacadeJobStatusResponses = {
    /**
     * Success
     */
    200: JobStatusPollPayload | JobStatusSucceededResponse;
};

export type FacadeJobStatusResponse = FacadeJobStatusResponses[keyof FacadeJobStatusResponses];

export type CreateMaskAsyncData = {
    /**
     * The input image and the mask parameters
     */
    body: CreateMaskRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/sensei/mask';
};

export type CreateMaskAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Unauthorized
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Too many requests
     */
    429: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type CreateMaskAsyncError = CreateMaskAsyncErrors[keyof CreateMaskAsyncErrors];

export type CreateMaskAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type CreateMaskAsyncResponse = CreateMaskAsyncResponses[keyof CreateMaskAsyncResponses];

export type PsJobStatusData = {
    body?: never;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events.
         */
        'x-gw-ims-org-id'?: string;
    };
    path: {
        /**
         * The job ID.
         */
        jobId: string;
    };
    query?: never;
    url: '/pie/psdService/status/{jobId}';
};

export type PsJobStatusResponses = {
    /**
     * Job Status
     */
    200: PsJobResponse;
};

export type PsJobStatusResponse = PsJobStatusResponses[keyof PsJobStatusResponses];

export type GetDocumentManifestAsyncData = {
    /**
     * The PSD file with the layer information you want to extract.
     */
    body: DocumentManifestRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/documentManifest';
};

export type GetDocumentManifestAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type GetDocumentManifestAsyncError = GetDocumentManifestAsyncErrors[keyof GetDocumentManifestAsyncErrors];

export type GetDocumentManifestAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type GetDocumentManifestAsyncResponse = GetDocumentManifestAsyncResponses[keyof GetDocumentManifestAsyncResponses];

export type CreateDocumentAsyncData = {
    /**
     * The input psd file to create a new psd from
     */
    body: CreateDocumentRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/documentCreate';
};

export type CreateDocumentAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type CreateDocumentAsyncError = CreateDocumentAsyncErrors[keyof CreateDocumentAsyncErrors];

export type CreateDocumentAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type CreateDocumentAsyncResponse = CreateDocumentAsyncResponses[keyof CreateDocumentAsyncResponses];

export type ModifyDocumentAsyncData = {
    /**
     * The input psd file to apply edits to and generate renditions and/or save as a new psd
     */
    body: ModifyDocumentRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/documentOperations';
};

export type ModifyDocumentAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type ModifyDocumentAsyncError = ModifyDocumentAsyncErrors[keyof ModifyDocumentAsyncErrors];

export type ModifyDocumentAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type ModifyDocumentAsyncResponse = ModifyDocumentAsyncResponses[keyof ModifyDocumentAsyncResponses];

export type CreateRenditionAsyncData = {
    /**
     * The input psd file to create renditions from
     */
    body: CreateRenditionRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/renditionCreate';
};

export type CreateRenditionAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type CreateRenditionAsyncError = CreateRenditionAsyncErrors[keyof CreateRenditionAsyncErrors];

export type CreateRenditionAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type CreateRenditionAsyncResponse = CreateRenditionAsyncResponses[keyof CreateRenditionAsyncResponses];

export type ReplaceSmartObjectAsyncData = {
    /**
     * The input psd file to apply edits for replacing embedded smart object to and generate renditions and/or save as a new psd
     */
    body: ReplaceSmartObjectRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/smartObject';
};

export type ReplaceSmartObjectAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type ReplaceSmartObjectAsyncError = ReplaceSmartObjectAsyncErrors[keyof ReplaceSmartObjectAsyncErrors];

export type ReplaceSmartObjectAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type ReplaceSmartObjectAsyncResponse = ReplaceSmartObjectAsyncResponses[keyof ReplaceSmartObjectAsyncResponses];

export type PlayPhotoshopActionsAsyncData = {
    /**
     * The input file to apply Photoshop Actions to and generate renditions and/or save as a new image
     */
    body: PlayPhotoshopActionsRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/photoshopActions';
};

export type PlayPhotoshopActionsAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type PlayPhotoshopActionsAsyncError = PlayPhotoshopActionsAsyncErrors[keyof PlayPhotoshopActionsAsyncErrors];

export type PlayPhotoshopActionsAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type PlayPhotoshopActionsAsyncResponse = PlayPhotoshopActionsAsyncResponses[keyof PlayPhotoshopActionsAsyncResponses];

export type PlayPhotoshopActionsJsonAsyncData = {
    /**
     * The input psd file to apply Photoshop actionJSON to and generate renditions and/or save as a new image
     */
    body: PlayPhotoshopActionsJsonRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/actionJSON';
};

export type PlayPhotoshopActionsJsonAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Too many requests
     */
    429: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type PlayPhotoshopActionsJsonAsyncError = PlayPhotoshopActionsJsonAsyncErrors[keyof PlayPhotoshopActionsJsonAsyncErrors];

export type PlayPhotoshopActionsJsonAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type PlayPhotoshopActionsJsonAsyncResponse = PlayPhotoshopActionsJsonAsyncResponses[keyof PlayPhotoshopActionsJsonAsyncResponses];

export type ConvertToActionsJsonAsyncData = {
    /**
     * The input ATN file to convert to actionJSON.
     */
    body: ConvertToActionsJsonRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/actionJsonCreate';
};

export type ConvertToActionsJsonAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type ConvertToActionsJsonAsyncError = ConvertToActionsJsonAsyncErrors[keyof ConvertToActionsJsonAsyncErrors];

export type ConvertToActionsJsonAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type ConvertToActionsJsonAsyncResponse = ConvertToActionsJsonAsyncResponses[keyof ConvertToActionsJsonAsyncResponses];

export type ApplyAutoCropAsyncData = {
    /**
     * The input image to apply product crop to.
     */
    body: ApplyAutoCropRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/productCrop';
};

export type ApplyAutoCropAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Too many requests
     */
    429: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type ApplyAutoCropAsyncError = ApplyAutoCropAsyncErrors[keyof ApplyAutoCropAsyncErrors];

export type ApplyAutoCropAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type ApplyAutoCropAsyncResponse = ApplyAutoCropAsyncResponses[keyof ApplyAutoCropAsyncResponses];

export type ApplyDepthBlurAsyncData = {
    /**
     * The input image to apply depth blur to.
     */
    body: ApplyDepthBlurRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events.
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/depthBlur';
};

export type ApplyDepthBlurAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Too many requests
     */
    429: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type ApplyDepthBlurAsyncError = ApplyDepthBlurAsyncErrors[keyof ApplyDepthBlurAsyncErrors];

export type ApplyDepthBlurAsyncResponses = {
    /**
     * Success
     */
    202: JobStatusLinkResponse;
};

export type ApplyDepthBlurAsyncResponse = ApplyDepthBlurAsyncResponses[keyof ApplyDepthBlurAsyncResponses];

export type EditTextLayerAsyncData = {
    /**
     * The input text to be edited.
     */
    body: EditTextLayerRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/text';
};

export type EditTextLayerAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Too many requests
     */
    429: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type EditTextLayerAsyncError = EditTextLayerAsyncErrors[keyof EditTextLayerAsyncErrors];

export type EditTextLayerAsyncResponses = {
    /**
     * success
     */
    202: JobStatusLinkResponse;
};

export type EditTextLayerAsyncResponse = EditTextLayerAsyncResponses[keyof EditTextLayerAsyncResponses];

export type CreateArtboardAsyncData = {
    /**
     * The input artboard to be created.
     */
    body: CreateArtboardRequest;
    headers?: {
        /**
         * The IMS organization ID. This only needs to be sent if you want to receive the job status through Adobe I/O Events
         */
        'x-gw-ims-org-id'?: string;
    };
    path?: never;
    query?: never;
    url: '/pie/psdService/artboardCreate';
};

export type CreateArtboardAsyncErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable to upload asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type CreateArtboardAsyncError = CreateArtboardAsyncErrors[keyof CreateArtboardAsyncErrors];

export type CreateArtboardAsyncResponses = {
    /**
     * success
     */
    202: JobStatusLinkResponse;
};

export type CreateArtboardAsyncResponse = CreateArtboardAsyncResponses[keyof CreateArtboardAsyncResponses];

export type MaskObjectsData = {
    body: MaskObjectsRequest;
    path?: never;
    query?: never;
    url: '/v1/mask-objects';
};

export type MaskObjectsErrors = {
    /**
     * Bad Request
     */
    400: InputValidationError;
    /**
     * Unauthorized
     */
    401: InputValidationError;
    /**
     * Forbidden
     */
    403: InputValidationError;
    /**
     * Resource Not Found
     */
    404: InputValidationError;
    /**
     * Too Many Requests
     */
    429: InputValidationError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type MaskObjectsError = MaskObjectsErrors[keyof MaskObjectsErrors];

export type MaskObjectsResponses = {
    /**
     * Accepted
     */
    202: JobLinkResponse;
};

export type MaskObjectsResponse = MaskObjectsResponses[keyof MaskObjectsResponses];

export type MaskBodyPartsData = {
    body: MaskBodyPartsRequest;
    path?: never;
    query?: never;
    url: '/v1/mask-body-parts';
};

export type MaskBodyPartsErrors = {
    /**
     * Bad Request
     */
    400: InputValidationError;
    /**
     * Unauthorized
     */
    401: InputValidationError;
    /**
     * Forbidden
     */
    403: InputValidationError;
    /**
     * Resource Not Found
     */
    404: InputValidationError;
    /**
     * Too Many Requests
     */
    429: InputValidationError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type MaskBodyPartsError = MaskBodyPartsErrors[keyof MaskBodyPartsErrors];

export type MaskBodyPartsResponses = {
    /**
     * Accepted
     */
    202: JobLinkResponse;
};

export type MaskBodyPartsResponse = MaskBodyPartsResponses[keyof MaskBodyPartsResponses];

export type RefineMaskData = {
    body: RefineMaskRequest;
    path?: never;
    query?: never;
    url: '/v1/refine-mask';
};

export type RefineMaskErrors = {
    /**
     * Bad Request
     */
    400: InputValidationError;
    /**
     * Unauthorized
     */
    401: InputValidationError;
    /**
     * Forbidden
     */
    403: InputValidationError;
    /**
     * Resource Not Found
     */
    404: InputValidationError;
    /**
     * Too Many Requests
     */
    429: InputValidationError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type RefineMaskError = RefineMaskErrors[keyof RefineMaskErrors];

export type RefineMaskResponses = {
    /**
     * Accepted
     */
    202: JobLinkResponse;
};

export type RefineMaskResponse = RefineMaskResponses[keyof RefineMaskResponses];

export type FillMaskedAreasData = {
    body: FillMaskedAreasRequest;
    path?: never;
    query?: never;
    url: '/v1/fill-masked-areas';
};

export type FillMaskedAreasErrors = {
    /**
     * Bad Request
     */
    400: InputValidationError;
    /**
     * Unauthorized
     */
    401: InputValidationError;
    /**
     * Forbidden
     */
    403: InputValidationError;
    /**
     * Resource Not Found
     */
    404: InputValidationError;
    /**
     * Too Many Requests
     */
    429: InputValidationError;
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type FillMaskedAreasError = FillMaskedAreasErrors[keyof FillMaskedAreasErrors];

export type FillMaskedAreasResponses = {
    /**
     * Accepted
     */
    202: JobLinkResponse;
};

export type FillMaskedAreasResponse = FillMaskedAreasResponses[keyof FillMaskedAreasResponses];

export type GetJobStatusData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/v1/status/{jobId}';
};

export type GetJobStatusErrors = {
    /**
     * Internal Server Error
     */
    500: JobError;
};

export type GetJobStatusError = GetJobStatusErrors[keyof GetJobStatusErrors];

export type GetJobStatusResponses = {
    /**
     * The schema of a 200 response varies depending on the status of the job. A job with a `succeeded` status will include the results in the response. Result objects vary depending on the operation.
     */
    200: ({
        status: 'not_started';
    } & JobStatusNotStarted) | ({
        status: 'running';
    } & JobStatusRunning) | ({
        status: 'succeeded';
    } & JobStatusSucceeded) | ({
        status: 'failed';
    } & JobStatusFailed);
};

export type GetJobStatusResponse = GetJobStatusResponses[keyof GetJobStatusResponses];
