/**
 * OpenAPI-derived MCP tool definitions.
 * @generated by scripts/generate-openapi-mcp-tools.mjs — do not edit.
 * @see https://github.com/harsha-iiiv/openapi-mcp-generator
 */
export const openapiMcpTools = [
  {
    "name": "taggedDocuments",
    "description": "This API retrieves a list of tagged documents that users can access, including those they own or those shared with them, along with relevant metadata. It supports pagination and sorting, allowing users to specify the starting point, define the number of documents to return, and choose the order in which to list them. The response includes the requested documents and their metadata.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "start": {
          "type": "number",
          "description": "Pagination start index. Default is 0."
        },
        "limit": {
          "type": "number",
          "description": "Pagination limit. Default is 10 and maximum value allowed is 25."
        },
        "sortBy": {
          "description": "Use `sortBy` to sort the response.",
          "enum": [
            "+modifiedDate",
            "+name",
            "-modifiedDate",
            "-name",
            "-relevance",
            "modifiedDate",
            "name",
            "relevance"
          ],
          "type": "string"
        }
      }
    },
    "method": "get",
    "pathTemplate": "/beta/tagged-documents",
    "parameters": [
      {
        "name": "start",
        "in": "query",
        "required": false,
        "description": "Pagination start index. Default is 0.",
        "schema": {
          "type": "integer"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "description": "Pagination limit. Default is 10 and maximum value allowed is 25.",
        "schema": {
          "type": "integer"
        }
      },
      {
        "name": "sortBy",
        "in": "query",
        "required": false,
        "description": "Use `sortBy` to sort the response.",
        "schema": {
          "description": "Represents the sortBy field enum for tagged documents.",
          "enum": [
            "+modifiedDate",
            "+name",
            "-modifiedDate",
            "-name",
            "-relevance",
            "modifiedDate",
            "name",
            "relevance"
          ],
          "type": "string"
        }
      }
    ],
    "executionParameters": [
      {
        "name": "start",
        "in": "query"
      },
      {
        "name": "limit",
        "in": "query"
      },
      {
        "name": "sortBy",
        "in": "query"
      }
    ],
    "securityRequirements": [
      {
        "apiKey": [],
        "Authorization": []
      }
    ],
    "operationId": "taggedDocuments",
    "baseUrl": "https://express-api.adobe.io"
  },
  {
    "name": "taggedDocumentDetails",
    "description": "This API retrieves details of the pages and tagged elements within a specified document. It returns a paginated list of the document's pages and metadata about each page. If the document has tagged elements, the API includes their respective details, such as size and position. If the document does not have tagged elements, it returns an empty array. The response includes pagination information to help users navigate the document’s pages. A maximum of 10 pages can be returned in 1 API call.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "documentId": {
          "type": "string",
          "description": "The unique identifier of the document."
        },
        "start": {
          "type": "number",
          "description": "Specifies the starting document page number from which details need to be fetched. Default is 1."
        }
      },
      "required": [
        "documentId"
      ]
    },
    "method": "get",
    "pathTemplate": "/beta/tagged-documents/{documentId}",
    "parameters": [
      {
        "name": "documentId",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "The unique identifier of the document."
      },
      {
        "name": "start",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer"
        },
        "description": "Specifies the starting document page number from which details need to be fetched. Default is 1."
      }
    ],
    "executionParameters": [
      {
        "name": "documentId",
        "in": "path"
      },
      {
        "name": "start",
        "in": "query"
      }
    ],
    "securityRequirements": [
      {
        "apiKey": [],
        "Authorization": []
      }
    ],
    "operationId": "taggedDocumentDetails",
    "baseUrl": "https://express-api.adobe.io"
  },
  {
    "name": "generateVariation",
    "description": "This API creates a document variation based on provided input parameters. After processing, it temporarily stores the generated document and makes it available to the user within a designated folder. The document remains accessible for 30 days, after which the system automatically removes it.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "requestBody": {
          "description": "Generate variation of a tagged document. One single variation can be generated at a time.",
          "type": "object",
          "properties": {
            "id": {
              "description": "The identifier of the tagged document.",
              "type": "string"
            },
            "variationDetails": {
              "description": "Specify the details required to generate the requested variation.",
              "type": "object",
              "properties": {
                "tagMappings": {
                  "description": "A key-value pair where each key represents the unique identifier of a tag element, and the value represents the corresponding element's content. The value type varies by element type: for text elements, it is a plain string; for image or video elements, it is a pre-signed URL pointing to the image or video resource. Allowed domains for pre-signed URLs are AWS, Dropbox and Azure (windows.net). The key is obtained from the response of `/tagged-documents/{documentId}` in `documentPages` -\\> `taggedElements` -\\> `name`.",
                  "type": "object",
                  "additionalProperties": {
                    "type": "string"
                  }
                },
                "pages": {
                  "description": "A comma-separated string of page numbers for which the variation request is made. For example, \"1,2,3\".\nPage ranges can also be specified. For example, \"1-3\" includes pages 1, 2, and 3.\nAnother example is \"1,3-5\", which includes pages 1, 3, 4, and 5.\n\"1-\" can be used to specify all pages, while \"5-\" indicates page 5 to the last page.\nIf not provided, all pages are considered by default. Page numbers start from 1.",
                  "type": "string"
                },
                "preferredDocumentName": {
                  "description": "The preferred name for the generated document. If you do not provide a name or the name is already in use, the system automatically generates a unique name.",
                  "type": "string"
                },
                "projectId": {
                  "description": "The identifier of the project where the variation is to be stored.",
                  "type": "string"
                }
              },
              "required": [
                "tagMappings"
              ]
            }
          },
          "required": [
            "id",
            "variationDetails"
          ]
        }
      },
      "required": [
        "requestBody"
      ]
    },
    "method": "post",
    "pathTemplate": "/beta/generate-variation",
    "parameters": [],
    "executionParameters": [],
    "requestBodyContentType": "application/json",
    "securityRequirements": [
      {
        "apiKey": [],
        "Authorization": []
      }
    ],
    "operationId": "generateVariation",
    "baseUrl": "https://express-api.adobe.io"
  },
  {
    "name": "exportRendition",
    "description": "Export one or more pages from an Adobe Express document in supported formats. This endpoint accepts an export request and returns pre-signed URLs for accessing the rendered files.\n\n**Supported formats:**\n- Image formats: `image/jpeg` (JPG), `image/png` (PNG)\n- Video format: `video/mp4` (MP4)\n- Document format: `application/pdf` (PDF)\n\n**Rendition availability:**\n- Image renditions: Valid for 4 hours, maximum size 8192px on the longest side\n- Video and PDF renditions: Valid for 24 hours, maximum size 4096px on the longest side\n\n**Asynchronous processing:**\nExport requests are processed asynchronously. The response includes a `jobId` and `statusUrl` that you can use to track the export progress and retrieve the final rendition URLs.\n\n**Restrictions:**\n\n| Condition | Behavior | Error |\n| --- | --- | --- |\n| Public templates (Adobe-owned documents not copied to the user account) | Export is not allowed | `400 bad_request` |\n| Document contains Adobe Stock–licensed assets | Export fails | `422 stock_content_detected` |",
    "inputSchema": {
      "type": "object",
      "properties": {
        "requestBody": {
          "description": "Payload for requesting rendition of a document.",
          "type": "object",
          "properties": {
            "id": {
              "description": "The identifier of the document that needs to be rendered.",
              "type": "string"
            },
            "pages": {
              "description": "A comma-separated string of page numbers for which the rendition request is made. For example, \"1,2,3\".\nPage ranges can also be specified. For example, \"1-3\" includes pages 1, 2, and 3.\nAnother example is \"1,3-5\", which includes pages 1, 3, 4, and 5.\n\"1-\" can be used to specify all pages, while \"5-\" indicates page 5 to the last page.\nIf not provided, the first page is considered by default. Page numbers start from 1.",
              "type": "string"
            },
            "options": {
              "description": "Options for the requested rendition.",
              "anyOf": [
                {
                  "description": "Options for the image rendition request.",
                  "type": "object",
                  "properties": {
                    "format": {
                      "description": "Image rendition format",
                      "enum": [
                        "image/jpeg",
                        "image/png"
                      ],
                      "type": "string"
                    },
                    "size": {
                      "description": "The size of the \"image\" rendition on the longest side. The aspect ratio is maintained.\nFor image the minimum size supported is 1px and maximum size supported is 8192px.\n\nIf not provided, the default size of page is considered.",
                      "type": "number"
                    }
                  },
                  "required": [
                    "format"
                  ]
                },
                {
                  "description": "Options for the video rendition request.",
                  "type": "object",
                  "properties": {
                    "format": {
                      "description": "video rendition format",
                      "type": "string",
                      "enum": [
                        "video/mp4"
                      ]
                    },
                    "size": {
                      "description": "The size of the \"video\" rendition on the longest side. The aspect ratio is maintained.\nFor video the minimum size supported is 146px and maximum size supported is 4096px.\n\nIf not provided, the default size of page is considered.",
                      "type": "number"
                    }
                  },
                  "required": [
                    "format"
                  ]
                },
                {
                  "description": "Options for the requested PDF rendition.",
                  "type": "object",
                  "properties": {
                    "format": {
                      "description": "PDF rendition format",
                      "type": "string",
                      "enum": [
                        "application/pdf"
                      ]
                    },
                    "pdfType": {
                      "description": "The type of PDF rendition. Default is \"standard\".",
                      "enum": [
                        "print",
                        "standard"
                      ],
                      "type": "string"
                    },
                    "downloadIndividualPdfFiles": {
                      "description": "Controls whether pages are downloaded as separate PDF files.\nWhen true, each page is downloaded as its own PDF file.\nWhen false, all pages are combined into a single PDF file.\n\nDefaults to false.",
                      "type": "boolean"
                    },
                    "config": {
                      "description": "Configuration for the provided PDF type.",
                      "anyOf": [
                        {
                          "description": "Configuration options for print-ready PDF renditions.",
                          "type": "object",
                          "properties": {
                            "bleed": {
                              "description": "Controls whether to include bleed settings in the PDF.\nDefaults to false.",
                              "type": "boolean"
                            },
                            "bleedSettings": {
                              "description": "Configuration settings for bleed margins.\nOnly applies when bleed is true.\nDefault value is 0.125 <unit>.",
                              "type": "object",
                              "properties": {
                                "amount": {
                                  "description": "The amount of bleed or crop margin.\nIt can be a positive or negative value.",
                                  "type": "number"
                                },
                                "unit": {
                                  "description": "The unit of measurement for the bleed or crop margin.",
                                  "enum": [
                                    "in",
                                    "mm"
                                  ],
                                  "type": "string"
                                }
                              },
                              "required": [
                                "amount",
                                "unit"
                              ]
                            },
                            "cropMargins": {
                              "description": "Controls whether to include crop margins in the PDF.\nDefaults to false.",
                              "type": "boolean"
                            },
                            "cropMarginsSettings": {
                              "description": "Configuration settings for crop margins.\nOnly applies when cropMargins is true.\nDefault value is 0.125 <unit>.",
                              "type": "object",
                              "properties": {
                                "amount": {
                                  "description": "The amount of bleed or crop margin.\nIt can be a positive or negative value.",
                                  "type": "number"
                                },
                                "unit": {
                                  "description": "The unit of measurement for the bleed or crop margin.",
                                  "enum": [
                                    "in",
                                    "mm"
                                  ],
                                  "type": "string"
                                }
                              },
                              "required": [
                                "amount",
                                "unit"
                              ]
                            }
                          }
                        },
                        {
                          "description": "Configuration settings for standard PDF rendition.",
                          "type": "object",
                          "properties": {
                            "accessibilityTags": {
                              "description": "Controls whether accessibility tags are included in the PDF.\nWhen true, accessibility tags will be embedded in the PDF.\nWhen false, accessibility tags will be omitted.\n\nDefaults to false.",
                              "type": "boolean"
                            }
                          }
                        }
                      ]
                    }
                  },
                  "required": [
                    "format"
                  ]
                }
              ]
            }
          },
          "required": [
            "id",
            "options"
          ]
        }
      },
      "required": [
        "requestBody"
      ]
    },
    "method": "post",
    "pathTemplate": "/beta/export-rendition",
    "parameters": [],
    "executionParameters": [],
    "requestBodyContentType": "application/json",
    "securityRequirements": [
      {
        "apiKey": [],
        "Authorization": []
      }
    ],
    "operationId": "exportRendition",
    "baseUrl": "https://express-api.adobe.io"
  },
  {
    "name": "getJobStatus",
    "description": "Retrieve a job's status by its `jobId`. Depending on the job type, the response may include job-specific details.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "jobId": {
          "type": "string",
          "description": "The unique identifier of the job."
        }
      },
      "required": [
        "jobId"
      ]
    },
    "method": "get",
    "pathTemplate": "/status/{jobId}",
    "parameters": [
      {
        "name": "jobId",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "The unique identifier of the job."
      }
    ],
    "executionParameters": [
      {
        "name": "jobId",
        "in": "path"
      }
    ],
    "securityRequirements": [
      {
        "apiKey": [],
        "Authorization": []
      }
    ],
    "operationId": "getJobStatus",
    "baseUrl": "https://express-api.adobe.io"
  }
] as const;

  export type OpenapiMcpTool = (typeof openapiMcpTools)[number];
  