// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateSpaceV1Data, CreateSpaceV1Errors, CreateSpaceV1Responses, V1CompositesComposeData, V1CompositesComposeErrors, V1CompositesComposeResponses, V1ScenesAssembleData, V1ScenesAssembleErrors, V1ScenesAssembleResponses, V1ScenesConvertData, V1ScenesConvertErrors, V1ScenesConvertResponses, V1ScenesDescribeData, V1ScenesDescribeErrors, V1ScenesDescribeResponses, V1ScenesRenderBasicData, V1ScenesRenderBasicErrors, V1ScenesRenderBasicResponses, V1ScenesRenderData, V1ScenesRenderErrors, V1ScenesRenderResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new Substance3Dsdk()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class Composites extends HeyApiClient {
    /**
     * Generate 3D object composite
     *
     * Generate a 3D Object Composite with the Substance 3D API.
     */
    public compose<ThrowOnError extends boolean = false>(options?: Options<V1CompositesComposeData, ThrowOnError>) {
        return (options?.client ?? this.client).post<V1CompositesComposeResponses, V1CompositesComposeErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/composites/compose',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}

export class Scenes extends HeyApiClient {
    /**
     * Create 3D scene
     *
     * Assemble a 3D scene with the Substance 3D API.
     */
    public assemble<ThrowOnError extends boolean = false>(options?: Options<V1ScenesAssembleData, ThrowOnError>) {
        return (options?.client ?? this.client).post<V1ScenesAssembleResponses, V1ScenesAssembleErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/scenes/assemble',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Convert 3D files
     *
     * Convert a 3D file into another 3D format with the Substance 3D API.
     */
    public convert<ThrowOnError extends boolean = false>(options?: Options<V1ScenesConvertData, ThrowOnError>) {
        return (options?.client ?? this.client).post<V1ScenesConvertResponses, V1ScenesConvertErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/scenes/convert',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Describe 3D scene
     *
     * Describe a 3D scene.
     */
    public describe<ThrowOnError extends boolean = false>(options?: Options<V1ScenesDescribeData, ThrowOnError>) {
        return (options?.client ?? this.client).post<V1ScenesDescribeResponses, V1ScenesDescribeErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/scenes/describe',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Render 3D object
     *
     * Render a 3D object with the Substance 3D API.
     */
    public render<ThrowOnError extends boolean = false>(options?: Options<V1ScenesRenderData, ThrowOnError>) {
        return (options?.client ?? this.client).post<V1ScenesRenderResponses, V1ScenesRenderErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/scenes/render',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Render 3D object (basic version)
     *
     * Render a 3D object (basic version) with the Substance 3D API.
     */
    public renderBasic<ThrowOnError extends boolean = false>(options?: Options<V1ScenesRenderBasicData, ThrowOnError>) {
        return (options?.client ?? this.client).post<V1ScenesRenderBasicResponses, V1ScenesRenderBasicErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/scenes/render-basic',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}

export class V1 extends HeyApiClient {
    private _composites?: Composites;
    get composites(): Composites {
        return this._composites ??= new Composites({ client: this.client });
    }
    
    private _scenes?: Scenes;
    get scenes(): Scenes {
        return this._scenes ??= new Scenes({ client: this.client });
    }
}

export class Substance3Dsdk extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<Substance3Dsdk>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        Substance3Dsdk.__registry.set(this, args?.key);
    }
    
    /**
     * Create Space
     *
     * Create a Space from 3D files.
     */
    public createSpaceV1<ThrowOnError extends boolean = false>(options: Options<CreateSpaceV1Data, ThrowOnError>) {
        return (options.client ?? this.client).post<CreateSpaceV1Responses, CreateSpaceV1Errors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/spaces',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    private _v1?: V1;
    get v1(): V1 {
        return this._v1 ??= new V1({ client: this.client });
    }
}
