// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://s3d.adobe.io' | (string & {});
};

/**
 * The error within the error response.
 */
export type FfapierrorsFfapiError = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * Associated error code.
     */
    error_code: string;
    /**
     * Optional list of individual error details.
     */
    error_details?: Array<unknown>;
    /**
     * Error message.
     */
    message?: string;
};

export type FfapierrorsFfapiErrorDetail = {
    /**
     * Error code.
     */
    error_code: string;
    /**
     * Additional context for the error.
     */
    error_context?: unknown;
    /**
     * Where the error occurred, indicated in dot notation (e.g., body.items[3].tags or path.thing-id).
     */
    loc: string;
    /**
     * Error message text.
     */
    msg: string;
};

export type RestBaseFileFrameIo = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Frame.io access token or Developer token. See https://developer.frame.io/docs/getting-started/authentication for obtaining a token.
     */
    accessToken: string;
    /**
     * Frame.io folder ID containing the assets. This should be the ID of the folder (not an asset ID). For best performance and to avoid [size limitations](/#what-is-the-maximum-size-of-assets-i-can-process), use the folder ID closest to your target assets. The system will retrieve all content from the specified folder, so choosing a parent folder with many subfolders may exceed the maximum retrieval size limit
     */
    folderId: string;
};

export type RestBaseFileNextFrameIo = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Frame.io access token. See https://developer.adobe.com/frameio/guides/Authentication/ for obtaining a token.
     */
    accessToken: string;
    /**
     * Frame.io account ID. This is the account identifier for the next.frame.io account owner. To find your account ID, log in to next.frame.io, navigate to your inbox, and extract the UUID from the URL (e.g., in https://next.frame.io/inbox/abcdefgh-1234-1234-1234-abcdefghijk, the account ID is abcdefgh-1234-1234-1234-abcdefghijk)
     */
    accountId: string;
    /**
     * Frame.io folder ID containing the assets. This should be the ID of the folder (not an asset ID). For best performance and to avoid [size limitations](/#what-is-the-maximum-size-of-assets-i-can-process), use the folder ID closest to your target assets. The system will retrieve all content from the specified folder, so choosing a parent folder with many subfolders may exceed the maximum retrieval size limit
     */
    folderId: string;
};

export type RestBaseFileUrl = {
    /**
     * The filename in the filepath overrides filename. If filepath is unset, will try to detect filename from content disposition header, then url itself. If a path is specified before the filename in the filepath, the file will be mounted at that location in the space.
     */
    filepath?: string;
    url: string;
};

export type RestBaseMountedSource = {
    /**
     * Fetch content from a Frame.io folder. ⚠️ All sources are exclusive.
     *
     * @deprecated
     */
    'frame.io'?: RestBaseSourceFrameIo;
    /**
     * Where to mount the content of the source in the virtual job working directory.
     */
    mountPoint?: string;
    /**
     * Fetch content from a next.frame.io folder. ⚠️ All sources are exclusive.
     */
    'next.frame.io'?: RestBaseSourceFrameIov4;
    /**
     * Read content from an existing space (can be another job's output, or uploaded manually with the space API). ⚠️ All sources are exclusive.'
     */
    space?: RestBaseSourceSpace;
    /**
     * Fetch content from a URL. ⚠️ All sources are exclusive.
     */
    url?: RestBaseSourceUrl;
};

export type RestBaseSourceFrameIo = {
    /**
     * Frame.io access token or Developer token. See https://developer.frame.io/docs/getting-started/authentication for obtaining a token.
     */
    accessToken: string;
    /**
     * Frame.io folder ID containing the assets. This should be the ID of the folder (not an asset ID). For best performance and to avoid [size limitations](/#what-is-the-maximum-size-of-assets-i-can-process), use the folder ID closest to your target assets. The system will retrieve all content from the specified folder, so choosing a parent folder with many subfolders may exceed the maximum retrieval size limit
     */
    folderId: string;
};

export type RestBaseSourceFrameIov4 = {
    /**
     * Frame.io access token. See https://developer.adobe.com/frameio/guides/Authentication/ for obtaining a token.
     */
    accessToken: string;
    /**
     * Frame.io account ID. This is the account identifier for the next.frame.io account owner. To find your account ID, log in to next.frame.io, navigate to your inbox, and extract the UUID from the URL (e.g., in https://next.frame.io/inbox/abcdefgh-1234-1234-1234-abcdefghijk, the account ID is abcdefgh-1234-1234-1234-abcdefghijk)
     */
    accountId: string;
    /**
     * Frame.io folder ID containing the assets. This should be the ID of the folder (not an asset ID). For best performance and to avoid [size limitations](/#what-is-the-maximum-size-of-assets-i-can-process), use the folder ID closest to your target assets. The system will retrieve all content from the specified folder, so choosing a parent folder with many subfolders may exceed the maximum retrieval size limit
     */
    folderId: string;
};

export type RestBaseSourceSpace = {
    /**
     * A space ID.
     */
    id: string;
};

export type RestBaseSourceUrl = {
    /**
     * Filename override. If unset, the service will try to detect the filename from the content disposition header, then the URL itself.
     */
    filename?: string;
    /**
     * URL to fetch content from.
     */
    url: string;
};

export type RestBaseSpace = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * time at which the space will be deleted
     */
    expiry: string;
    /**
     * List of all files contained in Space, ordered by name.
     */
    files: Array<RestBaseSpaceFile> | null;
    /**
     * Unique identifier of this Space.
     */
    id: string;
    /**
     * URL to the full description of this Space.
     */
    url: string;
    /**
     * URL to fetch the whole space as an archive (usually a ZIP file).
     */
    archiveUrl?: unknown;
};

export type RestBaseSpaceFile = {
    name: string;
    size: number;
    url: string;
};

export type Restv1ComposeSceneRequest = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of an existing camera in the source 3D scene. The camera has to be defined in the scene.
     */
    cameraName?: string;
    /**
     * Class of content to generate.
     */
    contentClass?: 'art' | 'photo';
    /**
     * ID of the custom model to be used for the generation. You can retrieve your custom model ID (assetId) with the Firefly retrieve custom model endpoint (https://developer.adobe.com/firefly-services/docs/firefly-api/api/#operation/getCustomModels).
     */
    customModelId?: string;
    /**
     * Enable the auto-generated ground plane under the hero asset. This is useful if the 3D scene contains only a hero asset, without additional elements.
     */
    enableGroundPlane?: boolean;
    /**
     * Optional environment settings used for all variations. If omitted, an environment will be generated based on the background. If set, the `lightingSeeds` parameter will be ignored.
     */
    environment?: TypesComposeEnvironment;
    /**
     * Exposure, in EV (0=neutral).
     */
    environmentExposure?: number;
    /**
     * Name of an existing 'hero asset' in the source 3D scene. The asset has to be defined in the scene.
     */
    heroAsset: string;
    /**
     * Optional seeds to be used to generate the lighting for the scene. The first seed will be used with the first seed of the background, the second one with the second seed of the background and so on. Background seeds must be defined and the number of lighting seeds should equal the number of background seeds. If not set, random seeds will be used. You will be able to retrieve the seeds used for the generation in the output details of the job.
     */
    lightingSeeds?: Array<number>;
    /**
     * Model version to be used to generate the background image with Adobe Firefly.
     */
    modelVersion?: 'image3_fast' | 'image4_standard' | 'image4_ultra';
    /**
     * The number of variations to generate. `numVariations` will default to the number of seeds, or to 1 if `seeds` is not specified.
     */
    numVariations?: number;
    /**
     * Prompt to be used to generate the background image with Adobe Firefly.
     */
    prompt: string;
    /**
     * Optional scene-level details, such as a custom camera.
     */
    scene?: TypesComposeSceneSceneDetails;
    /**
     * The path of the scene file in `sources`. If value is null, the first found scene file will be used.
     */
    sceneFile?: string;
    /**
     * Optional seed value to be used to generate the background image with Adobe Firefly. A seed ensures consistent background image generation. If `seed` is not set, a random seed will be used. Retrieve the seed used for the generation in the output details of the job. If specified with `numVariations`, the number of seeds must be the equal to `numVariations`.
     */
    seeds?: Array<number>;
    /**
     * The size of the image generations. The supported dimensions for image generations are:
     * | Dimensions | Description |
     * | -----------| ----- |
     * | { "width": 2048, "height": 2048} | Square (1:1) |
     * | { "width": 2304, "height": 1792 } | Landscape (4:3) |
     * | { "width": 1792, "height": 2304 } | Portrait (3:4) |
     * | { "width": 2688, "height": 1536 } | Widescreen (16:9) |
     * | { "width": 1344, "height": 768 } |(7:4) |
     * |{ "width": 1152, "height": 896 } |(9:7) |
     * |{ "width": 896, "height": 1152 } |(7:9) |
     * | { "width": 1024, "height": 1024} | Square (1:1) |
     */
    size?: TypesOutputSize;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
    /**
     * Optional 'style image' to be used to generate the background. The style image has to be present in `sources`.
     */
    styleImage?: string;
};

export type Restv1BetaComposeOutput = {
    backgroundImage: Restv1BetaComposeOutputImage;
    image: Restv1BetaComposeOutputImage;
    lightingSeed: number;
    maskImage: Restv1BetaComposeOutputImage;
    seed: number;
};

export type Restv1BetaComposeOutputImage = {
    url: string;
};

export type Restv1BetaComposeSceneJobResult = {
    outputSpace: RestBaseSpace;
    outputs: Array<Restv1BetaComposeOutput>;
    promptHasBlockedArtists: boolean;
    promptHasDeniedWords: boolean;
    warnings?: Array<TypesWarning> | null;
};

export type Restv1BetaComposeSceneRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of an existing camera in the 3D scene (must be defined in the scene). Mutually exclusive with 'scene.camera'.
     */
    cameraName?: string;
    /**
     * Class of content to generate: 'photo' for photorealistic images or 'art' for artistic renditions. Defaults to 'photo'.
     */
    contentClass?: 'art' | 'photo';
    /**
     * ID of the custom model to be used for the generation. You can retrieve your custom model ID (assetId) with the Firefly retrieve custom model endpoint (https://developer.adobe.com/firefly-services/docs/firefly-api/api/#operation/getCustomModels).
     */
    customModelId?: string;
    /**
     * Allow to enable the auto-generated ground plane under the hero asset. Useful if the 3D scene contains only a hero asset without additional elements. Disabled by default.
     */
    enableGroundPlane?: boolean;
    /**
     * Optional environment settings used for all variations. If omitted, an environment will be generated based on the background. If set, the `lightingSeeds` parameter will be ignored.
     */
    environment?: TypesComposeEnvironment;
    /**
     * Exposure, in EV (0=neutral).
     */
    environmentExposure?: number;
    /**
     * Name of an existing 'hero asset' in the source 3D scene (the asset has to be defined in the scene).
     */
    heroAsset: string;
    /**
     * LightingSeeds defines optional, fixed random seeds for reproducible Image-Based Lighting (IBL) when generating AI backgrounds. It is only used when 'environment' is not provided. Each lighting seed maps to the corresponding background seed by index (first lighting seed with first background seed, etc.) when 'seeds' is specified. If the number of lighting seeds does not match the number of background seeds, the slice is automatically truncated or padded with random values. When omitted or set to nil, random lighting seeds are generated. The actual seeds used are returned in the response payload.
     */
    lightingSeeds?: Array<number>;
    /**
     * Model version to be used to generate the background image with Adobe Firefly. If omitted, defaults to 'image3_fast'.
     */
    modelVersion?: 'image3_fast' | 'image4_standard' | 'image4_ultra';
    /**
     * The number of variations to generate. `numVariations` will default to the number of seeds, or to 1 if `seeds` is not specified.
     */
    numVariations?: number;
    /**
     * Prompt to be used to generate the background image with Adobe Firefly.
     */
    prompt: string;
    /**
     * Optional scene-level details, such as a custom camera.
     */
    scene?: TypesComposeSceneSceneDetails;
    /**
     * The path of the scene file in `sources`. If value is null, the first found scene file will be used.
     */
    sceneFile?: string;
    /**
     * Optional seed to be used to generate the background image with Adobe Firefly. Seed ensures consistent background image generation. If `seed` is not set, a random seed will be used. You will be able to retrieve the seed used for the generation in the output details of the job. If specified alongside `numVariations`, the number of seeds must be equal to `numVariations`.
     */
    seeds?: Array<number>;
    /**
     * Output image dimensions. Supported resolutions:
     * | Dimensions | Description |
     * | -----------| ----- |
     * | { "width": 2048, "height": 2048} | Square (1:1) |
     * | { "width": 2304, "height": 1792 } | Landscape (4:3) |
     * | { "width": 1792, "height": 2304 } | Portrait (3:4) |
     * | { "width": 2688, "height": 1536 } | Widescreen (16:9) |
     */
    size?: TypesOutputSize;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
    /**
     * Optional reference image to influence the visual style and aesthetics of the generated background. Must be provided in sources.
     */
    styleImage?: string;
};

export type Restv1BetaComposeSceneResponse = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaComposeSceneJobResult;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for job result in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaCreateSceneJobResult = {
    outputSpace: RestBaseSpace;
    /**
     * URL for the created scene.
     */
    sceneUrl: string;
};

export type Restv1BetaCreateSceneRequest = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * Encoding output format.
     */
    encoding: 'glb' | 'gltf' | 'fbx' | 'usdz' | 'usda' | 'usdc' | 'obj';
    /**
     * Output filename.
     */
    fileBaseName: string;
    scene: TypesSceneDescription;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaCreateSceneResponse = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaCreateSceneJobResult;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaModelConvertJobResult = {
    outputSpace: RestBaseSpace;
};

export type Restv1BetaModelConvertRequest = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * Output format.
     */
    format: 'glb' | 'gltf' | 'fbx' | 'usdz' | 'usda' | 'usdc' | 'obj';
    /**
     * Conversion usually takes the first file that's considered a valid 3D model. Define this entry point to disambiguate when there are multiple options.
     */
    modelEntrypoint?: string;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaModelConvertResponse = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaModelConvertJobResult;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaRenderModelRequest = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * Options related to auto-framing.
     */
    autoFraming?: TypesAutoFramingOptions;
    /**
     * Options related to the background.
     */
    background?: TypesBackgroundOptions;
    /**
     * If set, this camera is used to perform the render. The camera has to be defined in the scene.
     */
    cameraName?: string;
    /**
     * Request additional outputs from the renderer.
     */
    extraOutputs?: TypesRenderExtraOutputs;
    /**
     * Options related to the ground plane.
     */
    groundPlane?: TypesGroundPlaneOptions;
    /**
     * Define rendering scene primitives.
     */
    scene: TypesSimpleSceneDescription;
    /**
     * Options related to the render size.
     */
    size?: TypesSizeOptions;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaRenderModelResponse = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaRenderSceneJobResult;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaRenderModelTurntableRequest = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * Auto-framing related options.
     */
    autoFraming?: TypesAutoFramingOptions;
    /**
     * Background related options.
     */
    background?: TypesBackgroundOptions;
    /**
     * If set, this camera is used to perform the render. The camera has to be defined in the scene.
     */
    cameraName?: string;
    /**
     * Whether to export individual frames along with the turntable product.
     */
    exportFrames?: boolean;
    framerate?: number;
    /**
     * Ground plane related options.
     */
    groundPlane?: TypesGroundPlaneOptions;
    /**
     * Set the rotation mode. Options are `rotate_camera` (camera rotates around model), `rotate_model` (model rotates), or `rotate_environment` (environment rotates).
     */
    mode?: 'rotate_camera' | 'rotate_model' | 'rotate_environment';
    /**
     * Set the rotation direction of the turntable.
     */
    rotationDirection?: 'clockwise' | 'counter_clockwise';
    /**
     * Define rendering scene primitives.
     */
    scene: TypesSimpleSceneDescription;
    seconds?: number;
    /**
     * Render size related options.
     */
    size?: TypesSizeOptions;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
    /**
     * Set to true to use a very fast rendering technique but with less accurate lighting.
     */
    useRasterizer?: boolean;
};

export type Restv1BetaRenderModelTurntableResponse = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaRenderSceneTurntableJobResult;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaRenderSceneJobResult = {
    /**
     * URL to the distance-to-camera map in NumPy .npy format, present when exportDistanceToCamera was requested
     */
    distanceToCameraUrl?: string;
    materialIds?: TypesIdsMapData;
    materialMasks?: Array<TypesMaskNameToFileBinding>;
    /**
     * URL to the matte grayscale image, present when exportMatte was requested
     */
    matteUrl?: string;
    objectIds?: TypesIdsMapData;
    objectMasks?: Array<TypesMaskNameToFileBinding>;
    outputSpace: RestBaseSpace;
    /**
     * URL to the rendered scene.
     */
    renderUrl: string;
    warnings?: Array<TypesWarning> | null;
};

export type Restv1BetaRenderSceneRequest = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * Auto-framing related options.
     */
    autoFraming?: TypesAutoFramingOptions;
    /**
     * Background related options.
     */
    background?: TypesBackgroundOptions;
    /**
     * If set, this camera is used to perform the render. The camera has to be defined in the scene.
     */
    cameraName?: string;
    /**
     * Request additional outputs from the renderer.
     */
    extraOutputs?: TypesRenderExtraOutputs;
    /**
     * Options related to the ground plane.
     */
    groundPlane?: TypesGroundPlaneOptions;
    /**
     * Define rendering scene primitives.
     */
    scene: TypesSceneDescription;
    /**
     * Render size related options.
     */
    size?: TypesSizeOptions;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaRenderSceneResponse = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaRenderSceneJobResult;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaRenderSceneTurntableJobResult = {
    /**
     * List of URLs to the rendered frames. The rendered frames are ordered by frame number.
     */
    framesUrls: Array<string>;
    outputSpace: RestBaseSpace;
    /**
     * URL to the rendered scene.
     */
    renderUrl: string;
    warnings?: Array<TypesWarning> | null;
};

export type Restv1BetaSceneDescJobResult = {
    stats: TypesSceneStatsInfo;
};

export type Restv1BetaSceneDescRequest = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * Path to the scene file in `sources`. If the value is `null`, the first found scene file will be used.
     */
    sceneFile?: string;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaSceneDescResponse = {
    /**
     * A URL to the JSON schema for this object.
     */
    readonly $schema?: string;
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaSceneDescJobResult;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type TypesAutoFramingOptions = {
    algorithm?: 'auto' | 'bounding_cylinder' | 'frustum_fit';
    /**
     * A value of 1 indicates tight framing. Less than 1 is a zoom-out. Greater than 1 is a zoom-in.
     */
    zoomFactor?: number;
};

export type TypesAzimuthAltitude = {
    /**
     * Altitude, in degrees, from -90 to 90 degrees.
     */
    altitude: number;
    /**
     * Rotation around the vertical axis, in degrees.
     */
    azimuth: number;
    /**
     * Look at point coordinates.
     */
    lookAt: [
        number,
        number,
        number
    ] | null;
    /**
     * Distance to the `lookAt` point.
     */
    radius: number;
};

export type TypesBackgroundOptions = {
    /**
     * RGBA background color. Has an effect only if `showEnvironment` is `false`. Each component has to be in the [0,1] range.
     */
    backgroundColor?: [
        number,
        number,
        number,
        number
    ] | null;
    /**
     * Path to a background image. If set, will be used as the background.
     */
    backgroundImage?: string;
    /**
     * Show the environment map as the background.
     */
    showEnvironment?: boolean;
};

export type TypesCameraStats = {
    aspectRatio: number;
    fStop: number;
    focalLength: number;
    focusDistance: number;
    horizontalAperture: number;
    horizontalApertureOffset: number;
    name: string;
    projection: string;
    verticalAperture: number;
    verticalApertureOffset: number;
};

export type TypesComposeEnvironment = {
    /**
     * Path of environment file in `sources`. If value is null, the environment file will be generated.
     */
    file: string;
    /**
     * Controls the orientation of the environment map.
     */
    rotation?: TypesRotation;
};

export type TypesComposeSceneSceneDetails = {
    /**
     * Custom camera definition for the scene render. Mutually exclusive with 'cameraName' at the top level. Use this to define camera parameters programmatically instead of referencing a named camera from the 3D scene.
     */
    camera?: TypesSceneCamera;
};

export type TypesExportMasksOptions = {
    /**
     * The list of masks to be exported, accepts glob expressions. If empty, all masks will be exported.
     */
    selection?: Array<string> | null;
};

export type TypesFormatOptions = {
    /**
     * options specific to USD file format
     */
    usd: TypesUsdOptions;
};

export type TypesGroundPlaneOptions = {
    /**
     * Automatically position the scene on the ground plane. Moves the scene along the vertical axis.
     */
    autoGroundScene?: boolean;
    /**
     * Enable/disable the ground plane.
     */
    enable?: boolean;
    /**
     * Enable/disable reflections onto the ground plane.
     */
    reflections?: boolean;
    /**
     * Controls the opacity of the reflections. Useful for compositing purposes.
     */
    reflectionsOpacity?: number;
    /**
     * Controls the roughness of the reflections. Useful for compositing purposes.
     */
    reflectionsRoughness?: number;
    /**
     * Controls whether the ground plane catches shadows or not.
     */
    shadows?: boolean;
    /**
     * Controls the opacity of cast shadows. Only has effect if shadows are enabled.
     */
    shadowsOpacity?: number;
};

export type TypesIdsMapData = {
    /**
     * The Ids map file name.
     */
    fileName: string;
    /**
     * List of name to color bindings.
     */
    ids: Array<TypesNameToColorBinding> | null;
};

export type TypesMaskNameToFileBinding = {
    /**
     * The file name.
     */
    fileName: string;
    /**
     * The name in the 3D scene.
     */
    name: string;
};

export type TypesMaterial = {
    /**
     * The PBR material definition.
     */
    sbs?: TypesSbsMaterial;
    /**
     * The solid color material definition.
     */
    solidColor?: TypesSolidColorMaterial;
};

export type TypesMaterialAssign = {
    /**
     * The material definition.
     */
    material: TypesMaterial;
    /**
     * Desired material name, it will be sanitized to make a valid USD prim name.
     */
    materialName: string;
    /**
     * List of nodes under which geometric primitives will have this material assigned. Each entry can be a full node name or a glob expression.
     */
    nodeList: Array<string> | null;
    /**
     * Set to true to assign this material by default to all geometric primitives.
     */
    assignByDefault?: unknown;
    /**
     * List of nodes to exclude from default assignment.
     */
    excludeFromDefault?: unknown;
};

export type TypesMaterialOverride = {
    /**
     * RGB float color value, for example white is [1.0,1.0,1.0].
     */
    absorptionColorFactor?: [
        number,
        number,
        number
    ];
    absorptionColorTexture?: string;
    absorptionDistanceFactor?: number;
    absorptionDistanceTexture?: string;
    /**
     * RGB float color value, for example white is [1.0,1.0,1.0].
     */
    baseColorFactor?: [
        number,
        number,
        number
    ];
    baseColorTexture?: string;
    /**
     * RGB float color value, for example white is [1.0,1.0,1.0].
     */
    coatColorFactor?: [
        number,
        number,
        number
    ];
    coatColorTexture?: string;
    coatOpacityFactor?: number;
    coatOpacityTexture?: string;
    coatRoughnessFactor?: number;
    coatRoughnessTexture?: string;
    materialName: string;
    metallicFactor?: number;
    metallicTexture?: string;
    normalFactor?: [
        number,
        number,
        number
    ];
    normalTexture?: string;
    opacityFactor?: number;
    opacityTexture?: string;
    pbrMaterial?: TypesSbsMaterial;
    roughnessFactor?: number;
    roughnessTexture?: string;
    translucencyFactor?: number;
    translucencyTexture?: string;
    volumeThicknessFactor?: number;
    volumeThicknessTexture?: string;
};

export type TypesNameToColorBinding = {
    /**
     * Corresponding color in the ID map.
     */
    color: string;
    /**
     * Name in 3D scene.
     */
    name: string;
};

export type TypesOutputSize = {
    height: number;
    width: number;
};

export type TypesRenderExtraOutputExportMatte = {
    /**
     * Nodes to be included into the matte, the list can contain glob patterns. If empty, the matte will contain all scene objects.
     */
    includeNodes: Array<string> | null;
};

export type TypesRenderExtraOutputs = {
    /**
     * export a distance-to-camera map as a NumPy .npy file (float32 2D array)
     */
    exportDistanceToCamera?: boolean;
    /**
     * Export an image with one color per material.
     */
    exportMaterialIds?: boolean;
    /**
     * Export one mask per material.
     */
    exportMaterialMasks?: TypesExportMasksOptions;
    /**
     * export compositing matte for a selection of objects
     */
    exportMatte?: TypesRenderExtraOutputExportMatte;
    /**
     * Export an image with one color per object.
     */
    exportObjectIds?: boolean;
    /**
     * Export one mask per object.
     */
    exportObjectMasks?: TypesExportMasksOptions;
};

export type TypesRendererConfig = {
    /**
     * Renderer to use. 'ssca' is the default path-tracing renderer; 'rtx' uses NVidia RTX renderer.
     */
    type: 'ssca' | 'rtx';
};

export type TypesRotation = {
    /**
     * Euler angles in degrees.
     */
    euler?: [
        number,
        number,
        number
    ];
    /**
     * In W,X,Y,Z order.
     */
    quaternion?: [
        number,
        number,
        number,
        number
    ];
};

export type TypesSbsMaterial = {
    /**
     * Select a preset to be used for the substance material rendering.
     */
    preset?: string;
    /**
     * Substance material render resolution. This should be a power of two.
     */
    resolution?: 16 | 32 | 64 | 128 | 256 | 512 | 1024 | 2048 | 4096;
    /**
     * Texture space rotation.
     */
    rotation?: number;
    /**
     * Path to a substance material; if not set, the first substance 3D material found in sources will be used.
     */
    sbsar?: string;
    /**
     * Texture space scale.
     */
    scale?: [
        number,
        number
    ];
    /**
     * Texture space translation.
     */
    translation?: [
        number,
        number
    ];
};

export type TypesSceneBaseFile = {
    /**
     * Path to the scene file in `sources`.
     */
    file: string;
    /**
     * Define root node for models in scene graph. If not found, the node which is parent of all models in the scene will be used. If this node doesn't exist, a new node will be created under global root.
     */
    modelsRootNodeName?: string;
};

export type TypesSceneCamera = {
    /**
     * Camera focal length, in mm.
     */
    focal?: number;
    /**
     * Camera sensor width, in mm.
     */
    sensorWidth?: number;
    /**
     * Controls the position and angle of the camera.
     */
    transform?: TypesTransform;
};

export type TypesSceneDescription = {
    /**
     * Define a scene from a file. If value is `null`, an empty scene will be created.
     */
    baseFile?: TypesSceneBaseFile;
    /**
     * Define a new camera for the scene.
     */
    camera?: TypesSceneCamera;
    /**
     * Define the environment for the scene. Override the previous existing environment.
     */
    environment?: TypesSceneEnvironment;
    /**
     * define options specific for model file format
     */
    formatOptions?: TypesFormatOptions;
    /**
     * Assign new materials to geometric primitives.
     */
    materials?: Array<TypesMaterialAssign> | null;
    /**
     * Length of a scene unit, in meters. Defaults to `baseFile` meters per unit if any, or 0.01 (centimeters) otherwise.
     */
    metersPerUnit?: number;
    /**
     * Define additional models for the scene.
     */
    models?: TypesSceneModels;
};

export type TypesSceneEnvironment = {
    /**
     * Exposure, in EV (0=neutral).
     */
    exposure?: number;
    /**
     * Path to the environment file in `sources`. If the value is `null`, the first found environment file will be used.
     */
    file?: string;
    /**
     * A scene may contain 3D lights, like area lights or spot lights. By default, all those lights are removed when a new environment is set. Set this option to `true` to preserve the scene 3D lights.
     */
    preserveLights?: boolean;
    /**
     * Controls the orientation of the environment map.
     */
    rotation?: TypesRotation;
};

export type TypesSceneModel = {
    /**
     * Node name in scene graph which used as parent for the model. If anchor is not found, a node with the anchor name will be generated under models root node. And If value is `null`, a node will be generated under models root node.
     */
    anchorName?: string;
    /**
     * Path to the model file in `sources`. If the value is `null`, the first found model file will be used.
     */
    file?: string;
    /**
     * Define options specific for the model file format.
     */
    formatOptions?: TypesFormatOptions;
    /**
     * Define material overrides.
     */
    materialOverrides?: Array<TypesMaterialOverride> | null;
    /**
     * Transform applied on the anchor node. Overrides the previous value, if it exists.
     */
    transform?: TypesTransform;
};

export type TypesSceneModels = {
    /**
     * List of model import definitions.
     */
    imports?: Array<TypesSceneModel> | null;
    /**
     * Global transformation applied on the models root node defined in the scene. Overrides the previous value, if it exists.
     */
    modelsRootNodeTransform?: TypesTransform;
};

export type TypesSceneStatsBoundingBox = {
    max: Array<number> | null;
    min: Array<number> | null;
};

export type TypesSceneStatsInfo = {
    cameraNames: Array<string> | null;
    materialNames: Array<string> | null;
    metersPerSceneUnit: number;
    nodesHierarchy: TypesSceneStatsNode;
    numEquivalentTriangles: number;
    numExtraPolygons: number;
    numFaces: number;
    numLines: number;
    numMeshes: number;
    numPoints: number;
    numQuads: number;
    numSubMeshes: number;
    numTextures: number;
    numTriangles: number;
    numVertices: number;
    sceneUpAxis: string;
};

export type TypesSceneStatsNode = {
    assignedMaterialName?: string;
    cameraStats?: TypesCameraStats;
    children?: Array<TypesSceneStatsNode> | null;
    name: string;
    type: string;
    variants?: Array<TypesSceneStatsNodeVariant> | null;
    worldSpaceBoundingBox?: TypesSceneStatsBoundingBox;
};

export type TypesSceneStatsNodeVariant = {
    currentValue: string;
    name: string;
    values: Array<string> | null;
};

export type TypesShadowCatchingMaterial = {
    reflectionOpacity: number;
    roughness: number;
    shadowOpacity: number;
};

export type TypesSimpleSceneDescription = {
    /**
     * Define a new camera for the scene.
     */
    camera?: TypesSceneCamera;
    /**
     * Define the environment for the scene. Override the previous existing environment.
     */
    environment?: TypesSceneEnvironment;
    /**
     * Define options specific for the model file format.
     */
    formatOptions?: TypesFormatOptions;
    /**
     * Define material overrides.
     */
    materialOverrides?: Array<TypesMaterialOverride> | null;
    /**
     * Assign new materials to geometric primitives.
     */
    materials?: Array<TypesMaterialAssign> | null;
    /**
     * Length of a scene unit, in meters. Defaults to 0.01 (centimeters).
     */
    metersPerUnit?: number;
    /**
     * Path to the model file in `sources`. If the value is `null`, the first found model file will be used.
     */
    modelFile?: string;
    /**
     * Transform applied on the model.
     */
    modelTransform?: TypesTransform;
};

export type TypesSizeOptions = {
    /**
     * Render height.
     */
    height: number;
    /**
     * Render width.
     */
    width: number;
};

export type TypesSolidColorMaterial = {
    /**
     * RGB color of the solid material, each component has to be in the [0,1] range.
     */
    color: [
        number,
        number,
        number
    ] | null;
    /**
     * Metallic factor of the solid material, has to be in the [0,1] range.
     */
    metallicFactor?: number;
    /**
     * Roughness factor of the solid material, has to be in the [0,1] range.
     */
    roughnessFactor?: number;
};

export type TypesTrs = {
    rotation: TypesRotation;
    scale: [
        number,
        number,
        number
    ] | null;
    translation: [
        number,
        number,
        number
    ] | null;
};

export type TypesTransform = {
    /**
     * Transform is defined by azimuth, altitude and radius terms. If set, do not set `matrix` or `trs`.
     */
    azimuthAltitude?: TypesAzimuthAltitude;
    /**
     * Transform is defined as a matrix. If set, do not set `trs` or `azimuthAltitude`.
     */
    matrix?: [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number
    ];
    /**
     * Transform is defined by translation, rotation and scale terms. If set, do not set `matrix` or `azimuthAltitude`.
     */
    trs?: TypesTrs;
};

export type TypesUsdOptions = {
    /**
     * List of USD variants definition applied on USD primitives.
     */
    variants: Array<TypesUsdVariant> | null;
};

export type TypesUsdVariant = {
    /**
     * name of the USD prim on which the variant is defined
     */
    primName: string;
    /**
     * name of the variant option to apply from the variant set
     */
    variant: string;
    /**
     * name of the variant set to select from
     */
    variantSet: string;
};

export type TypesWarning = {
    context: string;
    message: string;
};

/**
 * The error within the error response.
 */
export type FfapierrorsFfapiErrorWritable = {
    /**
     * Associated error code.
     */
    error_code: string;
    /**
     * Optional list of individual error details.
     */
    error_details?: Array<unknown>;
    /**
     * Error message.
     */
    message?: string;
};

export type RestBaseFileFrameIoWritable = {
    /**
     * Frame.io access token or Developer token. See https://developer.frame.io/docs/getting-started/authentication for obtaining a token.
     */
    accessToken: string;
    /**
     * Frame.io folder ID containing the assets. This should be the ID of the folder (not an asset ID). For best performance and to avoid [size limitations](/#what-is-the-maximum-size-of-assets-i-can-process), use the folder ID closest to your target assets. The system will retrieve all content from the specified folder, so choosing a parent folder with many subfolders may exceed the maximum retrieval size limit
     */
    folderId: string;
};

export type RestBaseFileNextFrameIoWritable = {
    /**
     * Frame.io access token. See https://developer.adobe.com/frameio/guides/Authentication/ for obtaining a token.
     */
    accessToken: string;
    /**
     * Frame.io account ID. This is the account identifier for the next.frame.io account owner. To find your account ID, log in to next.frame.io, navigate to your inbox, and extract the UUID from the URL (e.g., in https://next.frame.io/inbox/abcdefgh-1234-1234-1234-abcdefghijk, the account ID is abcdefgh-1234-1234-1234-abcdefghijk)
     */
    accountId: string;
    /**
     * Frame.io folder ID containing the assets. This should be the ID of the folder (not an asset ID). For best performance and to avoid [size limitations](/#what-is-the-maximum-size-of-assets-i-can-process), use the folder ID closest to your target assets. The system will retrieve all content from the specified folder, so choosing a parent folder with many subfolders may exceed the maximum retrieval size limit
     */
    folderId: string;
};

export type RestBaseSpaceWritable = {
    /**
     * time at which the space will be deleted
     */
    expiry: string;
    /**
     * List of all files contained in Space, ordered by name.
     */
    files: Array<RestBaseSpaceFile> | null;
    /**
     * Unique identifier of this Space.
     */
    id: string;
    /**
     * URL to the full description of this Space.
     */
    url: string;
    /**
     * URL to fetch the whole space as an archive (usually a ZIP file).
     */
    archiveUrl?: unknown;
};

export type Restv1ComposeSceneRequestWritable = {
    /**
     * Name of an existing camera in the source 3D scene. The camera has to be defined in the scene.
     */
    cameraName?: string;
    /**
     * Class of content to generate.
     */
    contentClass?: 'art' | 'photo';
    /**
     * ID of the custom model to be used for the generation. You can retrieve your custom model ID (assetId) with the Firefly retrieve custom model endpoint (https://developer.adobe.com/firefly-services/docs/firefly-api/api/#operation/getCustomModels).
     */
    customModelId?: string;
    /**
     * Enable the auto-generated ground plane under the hero asset. This is useful if the 3D scene contains only a hero asset, without additional elements.
     */
    enableGroundPlane?: boolean;
    /**
     * Optional environment settings used for all variations. If omitted, an environment will be generated based on the background. If set, the `lightingSeeds` parameter will be ignored.
     */
    environment?: TypesComposeEnvironment;
    /**
     * Exposure, in EV (0=neutral).
     */
    environmentExposure?: number;
    /**
     * Name of an existing 'hero asset' in the source 3D scene. The asset has to be defined in the scene.
     */
    heroAsset: string;
    /**
     * Optional seeds to be used to generate the lighting for the scene. The first seed will be used with the first seed of the background, the second one with the second seed of the background and so on. Background seeds must be defined and the number of lighting seeds should equal the number of background seeds. If not set, random seeds will be used. You will be able to retrieve the seeds used for the generation in the output details of the job.
     */
    lightingSeeds?: Array<number>;
    /**
     * Model version to be used to generate the background image with Adobe Firefly.
     */
    modelVersion?: 'image3_fast' | 'image4_standard' | 'image4_ultra';
    /**
     * The number of variations to generate. `numVariations` will default to the number of seeds, or to 1 if `seeds` is not specified.
     */
    numVariations?: number;
    /**
     * Prompt to be used to generate the background image with Adobe Firefly.
     */
    prompt: string;
    /**
     * Optional scene-level details, such as a custom camera.
     */
    scene?: TypesComposeSceneSceneDetails;
    /**
     * The path of the scene file in `sources`. If value is null, the first found scene file will be used.
     */
    sceneFile?: string;
    /**
     * Optional seed value to be used to generate the background image with Adobe Firefly. A seed ensures consistent background image generation. If `seed` is not set, a random seed will be used. Retrieve the seed used for the generation in the output details of the job. If specified with `numVariations`, the number of seeds must be the equal to `numVariations`.
     */
    seeds?: Array<number>;
    /**
     * The size of the image generations. The supported dimensions for image generations are:
     * | Dimensions | Description |
     * | -----------| ----- |
     * | { "width": 2048, "height": 2048} | Square (1:1) |
     * | { "width": 2304, "height": 1792 } | Landscape (4:3) |
     * | { "width": 1792, "height": 2304 } | Portrait (3:4) |
     * | { "width": 2688, "height": 1536 } | Widescreen (16:9) |
     * | { "width": 1344, "height": 768 } |(7:4) |
     * |{ "width": 1152, "height": 896 } |(9:7) |
     * |{ "width": 896, "height": 1152 } |(7:9) |
     * | { "width": 1024, "height": 1024} | Square (1:1) |
     */
    size?: TypesOutputSize;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
    /**
     * Optional 'style image' to be used to generate the background. The style image has to be present in `sources`.
     */
    styleImage?: string;
};

export type Restv1BetaComposeSceneJobResultWritable = {
    outputSpace: RestBaseSpaceWritable;
    outputs: Array<Restv1BetaComposeOutput>;
    promptHasBlockedArtists: boolean;
    promptHasDeniedWords: boolean;
    warnings?: Array<TypesWarning> | null;
};

export type Restv1BetaComposeSceneRequestWritable = {
    /**
     * Name of an existing camera in the 3D scene (must be defined in the scene). Mutually exclusive with 'scene.camera'.
     */
    cameraName?: string;
    /**
     * Class of content to generate: 'photo' for photorealistic images or 'art' for artistic renditions. Defaults to 'photo'.
     */
    contentClass?: 'art' | 'photo';
    /**
     * ID of the custom model to be used for the generation. You can retrieve your custom model ID (assetId) with the Firefly retrieve custom model endpoint (https://developer.adobe.com/firefly-services/docs/firefly-api/api/#operation/getCustomModels).
     */
    customModelId?: string;
    /**
     * Allow to enable the auto-generated ground plane under the hero asset. Useful if the 3D scene contains only a hero asset without additional elements. Disabled by default.
     */
    enableGroundPlane?: boolean;
    /**
     * Optional environment settings used for all variations. If omitted, an environment will be generated based on the background. If set, the `lightingSeeds` parameter will be ignored.
     */
    environment?: TypesComposeEnvironment;
    /**
     * Exposure, in EV (0=neutral).
     */
    environmentExposure?: number;
    /**
     * Name of an existing 'hero asset' in the source 3D scene (the asset has to be defined in the scene).
     */
    heroAsset: string;
    /**
     * LightingSeeds defines optional, fixed random seeds for reproducible Image-Based Lighting (IBL) when generating AI backgrounds. It is only used when 'environment' is not provided. Each lighting seed maps to the corresponding background seed by index (first lighting seed with first background seed, etc.) when 'seeds' is specified. If the number of lighting seeds does not match the number of background seeds, the slice is automatically truncated or padded with random values. When omitted or set to nil, random lighting seeds are generated. The actual seeds used are returned in the response payload.
     */
    lightingSeeds?: Array<number>;
    /**
     * Model version to be used to generate the background image with Adobe Firefly. If omitted, defaults to 'image3_fast'.
     */
    modelVersion?: 'image3_fast' | 'image4_standard' | 'image4_ultra';
    /**
     * The number of variations to generate. `numVariations` will default to the number of seeds, or to 1 if `seeds` is not specified.
     */
    numVariations?: number;
    /**
     * Prompt to be used to generate the background image with Adobe Firefly.
     */
    prompt: string;
    /**
     * Optional scene-level details, such as a custom camera.
     */
    scene?: TypesComposeSceneSceneDetails;
    /**
     * The path of the scene file in `sources`. If value is null, the first found scene file will be used.
     */
    sceneFile?: string;
    /**
     * Optional seed to be used to generate the background image with Adobe Firefly. Seed ensures consistent background image generation. If `seed` is not set, a random seed will be used. You will be able to retrieve the seed used for the generation in the output details of the job. If specified alongside `numVariations`, the number of seeds must be equal to `numVariations`.
     */
    seeds?: Array<number>;
    /**
     * Output image dimensions. Supported resolutions:
     * | Dimensions | Description |
     * | -----------| ----- |
     * | { "width": 2048, "height": 2048} | Square (1:1) |
     * | { "width": 2304, "height": 1792 } | Landscape (4:3) |
     * | { "width": 1792, "height": 2304 } | Portrait (3:4) |
     * | { "width": 2688, "height": 1536 } | Widescreen (16:9) |
     */
    size?: TypesOutputSize;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
    /**
     * Optional reference image to influence the visual style and aesthetics of the generated background. Must be provided in sources.
     */
    styleImage?: string;
};

export type Restv1BetaComposeSceneResponseWritable = {
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaComposeSceneJobResultWritable;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for job result in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaCreateSceneJobResultWritable = {
    outputSpace: RestBaseSpaceWritable;
    /**
     * URL for the created scene.
     */
    sceneUrl: string;
};

export type Restv1BetaCreateSceneRequestWritable = {
    /**
     * Encoding output format.
     */
    encoding: 'glb' | 'gltf' | 'fbx' | 'usdz' | 'usda' | 'usdc' | 'obj';
    /**
     * Output filename.
     */
    fileBaseName: string;
    scene: TypesSceneDescription;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaCreateSceneResponseWritable = {
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaCreateSceneJobResultWritable;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaModelConvertJobResultWritable = {
    outputSpace: RestBaseSpaceWritable;
};

export type Restv1BetaModelConvertRequestWritable = {
    /**
     * Output format.
     */
    format: 'glb' | 'gltf' | 'fbx' | 'usdz' | 'usda' | 'usdc' | 'obj';
    /**
     * Conversion usually takes the first file that's considered a valid 3D model. Define this entry point to disambiguate when there are multiple options.
     */
    modelEntrypoint?: string;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaModelConvertResponseWritable = {
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaModelConvertJobResultWritable;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaRenderModelRequestWritable = {
    /**
     * Options related to auto-framing.
     */
    autoFraming?: TypesAutoFramingOptions;
    /**
     * Options related to the background.
     */
    background?: TypesBackgroundOptions;
    /**
     * If set, this camera is used to perform the render. The camera has to be defined in the scene.
     */
    cameraName?: string;
    /**
     * Request additional outputs from the renderer.
     */
    extraOutputs?: TypesRenderExtraOutputs;
    /**
     * Options related to the ground plane.
     */
    groundPlane?: TypesGroundPlaneOptions;
    /**
     * Define rendering scene primitives.
     */
    scene: TypesSimpleSceneDescription;
    /**
     * Options related to the render size.
     */
    size?: TypesSizeOptions;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaRenderModelResponseWritable = {
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaRenderSceneJobResultWritable;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaRenderModelTurntableRequestWritable = {
    /**
     * Auto-framing related options.
     */
    autoFraming?: TypesAutoFramingOptions;
    /**
     * Background related options.
     */
    background?: TypesBackgroundOptions;
    /**
     * If set, this camera is used to perform the render. The camera has to be defined in the scene.
     */
    cameraName?: string;
    /**
     * Whether to export individual frames along with the turntable product.
     */
    exportFrames?: boolean;
    framerate?: number;
    /**
     * Ground plane related options.
     */
    groundPlane?: TypesGroundPlaneOptions;
    /**
     * Set the rotation mode. Options are `rotate_camera` (camera rotates around model), `rotate_model` (model rotates), or `rotate_environment` (environment rotates).
     */
    mode?: 'rotate_camera' | 'rotate_model' | 'rotate_environment';
    /**
     * Set the rotation direction of the turntable.
     */
    rotationDirection?: 'clockwise' | 'counter_clockwise';
    /**
     * Define rendering scene primitives.
     */
    scene: TypesSimpleSceneDescription;
    seconds?: number;
    /**
     * Render size related options.
     */
    size?: TypesSizeOptions;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
    /**
     * Set to true to use a very fast rendering technique but with less accurate lighting.
     */
    useRasterizer?: boolean;
};

export type Restv1BetaRenderModelTurntableResponseWritable = {
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaRenderSceneTurntableJobResultWritable;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaRenderSceneJobResultWritable = {
    /**
     * URL to the distance-to-camera map in NumPy .npy format, present when exportDistanceToCamera was requested
     */
    distanceToCameraUrl?: string;
    materialIds?: TypesIdsMapData;
    materialMasks?: Array<TypesMaskNameToFileBinding>;
    /**
     * URL to the matte grayscale image, present when exportMatte was requested
     */
    matteUrl?: string;
    objectIds?: TypesIdsMapData;
    objectMasks?: Array<TypesMaskNameToFileBinding>;
    outputSpace: RestBaseSpaceWritable;
    /**
     * URL to the rendered scene.
     */
    renderUrl: string;
    warnings?: Array<TypesWarning> | null;
};

export type Restv1BetaRenderSceneRequestWritable = {
    /**
     * Auto-framing related options.
     */
    autoFraming?: TypesAutoFramingOptions;
    /**
     * Background related options.
     */
    background?: TypesBackgroundOptions;
    /**
     * If set, this camera is used to perform the render. The camera has to be defined in the scene.
     */
    cameraName?: string;
    /**
     * Request additional outputs from the renderer.
     */
    extraOutputs?: TypesRenderExtraOutputs;
    /**
     * Options related to the ground plane.
     */
    groundPlane?: TypesGroundPlaneOptions;
    /**
     * Define rendering scene primitives.
     */
    scene: TypesSceneDescription;
    /**
     * Render size related options.
     */
    size?: TypesSizeOptions;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaRenderSceneResponseWritable = {
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaRenderSceneJobResultWritable;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type Restv1BetaRenderSceneTurntableJobResultWritable = {
    /**
     * List of URLs to the rendered frames. The rendered frames are ordered by frame number.
     */
    framesUrls: Array<string>;
    outputSpace: RestBaseSpaceWritable;
    /**
     * URL to the rendered scene.
     */
    renderUrl: string;
    warnings?: Array<TypesWarning> | null;
};

export type Restv1BetaSceneDescRequestWritable = {
    /**
     * Path to the scene file in `sources`. If the value is `null`, the first found scene file will be used.
     */
    sceneFile?: string;
    /**
     * List of sources to aggregate and run the job against.
     */
    sources: Array<RestBaseMountedSource>;
};

export type Restv1BetaSceneDescResponseWritable = {
    /**
     * URL to report a bug about this job.
     */
    bugReportUrl: string;
    /**
     * Potential error that happened during the job processing.
     */
    error?: string;
    /**
     * Unique identifier of the job.
     */
    id: string;
    /**
     * Result when the job is successfully finished.
     */
    result?: Restv1BetaSceneDescJobResult;
    /**
     * Status of the job. Can be `not_started`, `running`, `succeeded`, or `failed`.
     */
    status: string;
    /**
     * URL to fetch/poll for the job result, in case the job is not finished yet.
     */
    url: string;
};

export type V1CompositesComposeData = {
    body: Restv1ComposeSceneRequestWritable;
    headers?: {
        /**
         * A user token referencing the user's individual account, obtained using their credentials.
         */
        'X-User-Token'?: string;
    };
    path?: never;
    query?: {
        /**
         * Blocking mode (acts like a synchronous API call). Wait for the result before returning. ⚠️ Some operations are long, please be sure to configure your client timeout settings accordingly.
         */
        wait?: boolean;
    };
    url: '/v1/composites/compose';
};

export type V1CompositesComposeErrors = {
    /**
     * Bad Request
     */
    400: FfapierrorsFfapiError;
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Unsupported Media Type
     */
    415: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type V1CompositesComposeError = V1CompositesComposeErrors[keyof V1CompositesComposeErrors];

export type V1CompositesComposeResponses = {
    /**
     * Accepted
     */
    202: Restv1BetaComposeSceneResponse;
};

export type V1CompositesComposeResponse = V1CompositesComposeResponses[keyof V1CompositesComposeResponses];

export type V1ScenesAssembleData = {
    body: Restv1BetaCreateSceneRequestWritable;
    path?: never;
    query?: {
        /**
         * Blocking mode (acts like a synchronous API call). Wait for the result before returning. ⚠️ Some operations are long, please be sure to configure your client timeout settings accordingly.
         */
        wait?: boolean;
    };
    url: '/v1/scenes/assemble';
};

export type V1ScenesAssembleErrors = {
    /**
     * Bad Request
     */
    400: FfapierrorsFfapiError;
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Unsupported Media Type
     */
    415: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type V1ScenesAssembleError = V1ScenesAssembleErrors[keyof V1ScenesAssembleErrors];

export type V1ScenesAssembleResponses = {
    /**
     * Accepted
     */
    202: Restv1BetaCreateSceneResponse;
};

export type V1ScenesAssembleResponse = V1ScenesAssembleResponses[keyof V1ScenesAssembleResponses];

export type V1ScenesConvertData = {
    body: Restv1BetaModelConvertRequestWritable;
    path?: never;
    query?: {
        /**
         * Blocking mode (acts like a synchronous API call). Wait for the result before returning. ⚠️ Some operations are long, please be sure to configure your client timeout settings accordingly.
         */
        wait?: boolean;
    };
    url: '/v1/scenes/convert';
};

export type V1ScenesConvertErrors = {
    /**
     * Bad Request
     */
    400: FfapierrorsFfapiError;
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Unsupported Media Type
     */
    415: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type V1ScenesConvertError = V1ScenesConvertErrors[keyof V1ScenesConvertErrors];

export type V1ScenesConvertResponses = {
    /**
     * Accepted
     */
    202: Restv1BetaModelConvertResponse;
};

export type V1ScenesConvertResponse = V1ScenesConvertResponses[keyof V1ScenesConvertResponses];

export type V1ScenesDescribeData = {
    body: Restv1BetaSceneDescRequestWritable;
    path?: never;
    query?: {
        /**
         * Blocking mode (acts like a synchronous API call). Wait for the result before returning. ⚠️ Some operations are long, please be sure to configure your client timeout settings accordingly.
         */
        wait?: boolean;
    };
    url: '/v1/scenes/describe';
};

export type V1ScenesDescribeErrors = {
    /**
     * Bad Request
     */
    400: FfapierrorsFfapiError;
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Unsupported Media Type
     */
    415: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type V1ScenesDescribeError = V1ScenesDescribeErrors[keyof V1ScenesDescribeErrors];

export type V1ScenesDescribeResponses = {
    /**
     * Accepted
     */
    202: Restv1BetaSceneDescResponse;
};

export type V1ScenesDescribeResponse = V1ScenesDescribeResponses[keyof V1ScenesDescribeResponses];

export type V1ScenesRenderData = {
    body: Restv1BetaRenderSceneRequestWritable;
    path?: never;
    query?: {
        /**
         * Blocking mode (acts like a synchronous API call). Wait for the result before returning. ⚠️ Some operations are long, please be sure to configure your client timeout settings accordingly.
         */
        wait?: boolean;
    };
    url: '/v1/scenes/render';
};

export type V1ScenesRenderErrors = {
    /**
     * Bad Request
     */
    400: FfapierrorsFfapiError;
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Unsupported Media Type
     */
    415: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type V1ScenesRenderError = V1ScenesRenderErrors[keyof V1ScenesRenderErrors];

export type V1ScenesRenderResponses = {
    /**
     * Accepted
     */
    202: Restv1BetaRenderSceneResponse;
};

export type V1ScenesRenderResponse = V1ScenesRenderResponses[keyof V1ScenesRenderResponses];

export type V1ScenesRenderBasicData = {
    body: Restv1BetaRenderModelRequestWritable;
    path?: never;
    query?: {
        /**
         * Blocking mode (acts like a synchronous API call). Wait for the result before returning. ⚠️ Some operations are long, please be sure to configure your client timeout settings accordingly.
         */
        wait?: boolean;
    };
    url: '/v1/scenes/render-basic';
};

export type V1ScenesRenderBasicErrors = {
    /**
     * Bad Request
     */
    400: FfapierrorsFfapiError;
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Unsupported Media Type
     */
    415: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type V1ScenesRenderBasicError = V1ScenesRenderBasicErrors[keyof V1ScenesRenderBasicErrors];

export type V1ScenesRenderBasicResponses = {
    /**
     * Accepted
     */
    202: Restv1BetaRenderModelResponse;
};

export type V1ScenesRenderBasicResponse = V1ScenesRenderBasicResponses[keyof V1ScenesRenderBasicResponses];

export type CreateSpaceV1Data = {
    body: {
        /**
         * Filename of the file being uploaded.
         */
        filename?: Blob | File;
        /**
         * General purpose name for multipart form value.
         */
        name?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/spaces';
};

export type CreateSpaceV1Errors = {
    /**
     * Bad Request
     */
    400: FfapierrorsFfapiError;
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Request Entity Too Large
     */
    413: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type CreateSpaceV1Error = CreateSpaceV1Errors[keyof CreateSpaceV1Errors];

export type CreateSpaceV1Responses = {
    /**
     * Created
     */
    201: RestBaseSpace;
};

export type CreateSpaceV1Response = CreateSpaceV1Responses[keyof CreateSpaceV1Responses];

export type CreateSpaceV2Data = {
    body: {
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/v2/spaces';
};

export type CreateSpaceV2Errors = {
    /**
     * Bad Request
     */
    400: FfapierrorsFfapiError;
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Request Entity Too Large
     */
    413: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type CreateSpaceV2Error = CreateSpaceV2Errors[keyof CreateSpaceV2Errors];

export type CreateSpaceV2Responses = {
    /**
     * Created
     */
    201: RestBaseSpace;
};

export type CreateSpaceV2Response = CreateSpaceV2Responses[keyof CreateSpaceV2Responses];

export type CreateSpaceFromFrameIoV2Data = {
    body: RestBaseFileFrameIoWritable;
    path?: never;
    query?: never;
    url: '/v2/spacesFrameIO';
};

export type CreateSpaceFromFrameIoV2Errors = {
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Request Entity Too Large
     */
    413: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type CreateSpaceFromFrameIoV2Error = CreateSpaceFromFrameIoV2Errors[keyof CreateSpaceFromFrameIoV2Errors];

export type CreateSpaceFromFrameIoV2Responses = {
    /**
     * Created
     */
    201: RestBaseSpace;
};

export type CreateSpaceFromFrameIoV2Response = CreateSpaceFromFrameIoV2Responses[keyof CreateSpaceFromFrameIoV2Responses];

export type CreateSpaceFromNextFrameIoV2Data = {
    body: RestBaseFileNextFrameIoWritable;
    path?: never;
    query?: never;
    url: '/v2/spacesNextFrameIO';
};

export type CreateSpaceFromNextFrameIoV2Errors = {
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Request Entity Too Large
     */
    413: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type CreateSpaceFromNextFrameIoV2Error = CreateSpaceFromNextFrameIoV2Errors[keyof CreateSpaceFromNextFrameIoV2Errors];

export type CreateSpaceFromNextFrameIoV2Responses = {
    /**
     * Created
     */
    201: RestBaseSpace;
};

export type CreateSpaceFromNextFrameIoV2Response = CreateSpaceFromNextFrameIoV2Responses[keyof CreateSpaceFromNextFrameIoV2Responses];

export type CreateSpaceUrlV2Data = {
    body: Array<RestBaseFileUrl> | null;
    path?: never;
    query?: never;
    url: '/v2/spacesURL';
};

export type CreateSpaceUrlV2Errors = {
    /**
     * Forbidden
     */
    403: FfapierrorsFfapiError;
    /**
     * Request Timeout
     */
    408: FfapierrorsFfapiError;
    /**
     * Request Entity Too Large
     */
    413: FfapierrorsFfapiError;
    /**
     * Unprocessable Entity
     */
    422: FfapierrorsFfapiError;
    /**
     * Too Many Requests
     */
    429: FfapierrorsFfapiError;
    /**
     * Internal Server Error
     */
    500: FfapierrorsFfapiError;
};

export type CreateSpaceUrlV2Error = CreateSpaceUrlV2Errors[keyof CreateSpaceUrlV2Errors];

export type CreateSpaceUrlV2Responses = {
    /**
     * Created
     */
    201: RestBaseSpace;
};

export type CreateSpaceUrlV2Response = CreateSpaceUrlV2Responses[keyof CreateSpaceUrlV2Responses];
