// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { ApplyAutoToneData, ApplyAutoToneErrors, ApplyAutoToneResponses, ApplyEditsData, ApplyEditsErrors, ApplyEditsResponses, ApplyPresetData, ApplyPresetErrors, ApplyPresetFromXmpContentData, ApplyPresetFromXmpContentErrors, ApplyPresetFromXmpContentResponses, ApplyPresetResponses, AutoStraightenImageData, AutoStraightenImageErrors, AutoStraightenImageResponses, LrJobStatusData, LrJobStatusResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Auto-straighten
 *
 * Auto-straighten an image by applying the Auto Upright transformation.
 */
export const autoStraightenImage = <ThrowOnError extends boolean = false>(options: Options<AutoStraightenImageData, ThrowOnError>) => (options.client ?? client).post<AutoStraightenImageResponses, AutoStraightenImageErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
    url: '/lrService/autoStraighten',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Auto-tone
 *
 * Automatically correct exposure, contrast, sharpness, and saturation on an image.
 */
export const applyAutoTone = <ThrowOnError extends boolean = false>(options: Options<ApplyAutoToneData, ThrowOnError>) => (options.client ?? client).post<ApplyAutoToneResponses, ApplyAutoToneErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
    url: '/lrService/autoTone',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Apply Lightroom edits
 *
 * Apply one or more Lightroom edits (exposure, contrast, sharpness, saturation) to an image.
 */
export const applyEdits = <ThrowOnError extends boolean = false>(options: Options<ApplyEditsData, ThrowOnError>) => (options.client ?? client).post<ApplyEditsResponses, ApplyEditsErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
    url: '/lrService/edit',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Apply Lightroom presets
 *
 * Apply one or more XMP Lightroom presets to the given image, by using the given preset XMP file(s).
 */
export const applyPreset = <ThrowOnError extends boolean = false>(options: Options<ApplyPresetData, ThrowOnError>) => (options.client ?? client).post<ApplyPresetResponses, ApplyPresetErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
    url: '/lrService/presets',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add XMP to image
 *
 * Apply XMP-based Lightroom preset to an image. XMP content is passed inline to the API.
 */
export const applyPresetFromXmpContent = <ThrowOnError extends boolean = false>(options: Options<ApplyPresetFromXmpContentData, ThrowOnError>) => (options.client ?? client).post<ApplyPresetFromXmpContentResponses, ApplyPresetFromXmpContentErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
    url: '/lrService/xmp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get status
 *
 * Get job status of a Lightroom job.
 */
export const lrJobStatus = <ThrowOnError extends boolean = false>(options: Options<LrJobStatusData, ThrowOnError>) => (options.client ?? client).get<LrJobStatusResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }, { scheme: 'bearer', type: 'http' }],
    url: '/lrService/status/{jobId}',
    ...options
});
