// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://image.adobe.io' | (string & {});
};

/**
 * JobError
 *
 * Any errors reported for the requested output.
 */
export type JobError = {
    /**
     * Type of the error.
     */
    type?: string;
    /**
     * The error code.
     */
    code?: string;
    /**
     * Description of the error.
     */
    title?: string;
    /**
     * Details of the error returned.
     */
    details?: Array<ErrorDetails>;
};

/**
 * InputValidationError
 *
 * Any errors reported for the requested output.
 */
export type InputValidationError = {
    /**
     * Type of the error.
     */
    type?: string;
    /**
     * The error code.
     */
    code?: string;
    /**
     * Description of the error.
     */
    title?: string;
    /**
     * Details of the error returned.
     */
    details?: Array<InputValidationErrorDetails>;
};

/**
 * TrialLimitExceededError
 *
 * Any errors reported for the requested output.
 */
export type TrialLimitExceededError = {
    /**
     * Type of the error.
     */
    type?: string;
    /**
     * The error code.
     */
    code?: string;
    /**
     * Description of the error.
     */
    title?: string;
    /**
     * Details of the error returned.
     */
    details?: string;
};

/**
 * InputValidationErrorDetails
 *
 * Details of the input validation error returned.
 */
export type InputValidationErrorDetails = {
    /**
     * Comma-separated list of allowed values for the input parameter.
     */
    allowedValues?: string;
    /**
     * Reason for the error.
     */
    reason?: string;
};

/**
 * StorageDetails
 *
 * File on Adobe's cloud or an external service (like AWS S3, Azure, Dropbox).
 */
export type StorageDetails = {
    /**
     * Pre-signed GET URL for the source asset.
     */
    href: string;
    storage: StorageType;
};

/**
 * Job Status Link
 */
export type JobStatusLink = {
    self?: SelfLink;
};

/**
 * JobStatusLinkResponse
 */
export type JobStatusLinkResponse = {
    _links?: JobStatusLink;
};

/**
 * LrOutputDetails
 */
export type LrOutputDetails = {
    /**
     * Pre-signed POST URL to the output file.
     */
    href: string;
    storage: StorageType;
    type: ImageFormatType;
    /**
     * Determines if the output file should be overwritten if it already exists. This flag is used only for Adobe cloud storage.
     */
    overwrite?: boolean;
    /**
     * Quality of the JPEG outputs (will be ignored for other output types). Ranges from 1 to 12, with 12 as the highest quality.
     */
    quality?: number;
};

/**
 * ImageFormatType
 *
 * Desired output image format.
 */
export type ImageFormatType = 'image/jpeg' | 'image/png' | 'image/x-adobe-dng' | 'application/rdf+xml';

/**
 * Lightroom Job Status Response
 */
export type LrJobApiResponse = {
    /**
     * The job's ID requested.
     */
    jobId?: string;
    /**
     * Created timestamp of the job.
     */
    created?: string;
    /**
     * Modified timestamp of the job.
     */
    modified?: string;
    /**
     * Output parameters for the job.
     */
    outputs?: Array<JobOutputDetails>;
    _links?: JobStatusLink;
};

/**
 * AutoStraightenImageRequest
 */
export type AutoStraightenImageRequest = {
    inputs: StorageDetails;
    options?: AutoStraightOptions;
    /**
     * Only a single output is supported currently.
     */
    outputs: Array<LrOutputDetails>;
};

/**
 * ApplyAutoToneRequest
 */
export type ApplyAutoToneRequest = {
    inputs: StorageDetails;
    /**
     * Only a single output is supported currently.
     */
    outputs: Array<LrOutputDetails>;
};

/**
 * ApplyEditsRequest
 */
export type ApplyEditsRequest = {
    /**
     * A hash describing an input image to edit. The input object will be one of 'external', 'azure', or 'dropbox'.
     */
    inputs: {
        source: StorageDetails;
    };
    options: EditOptions;
    /**
     * Edit photo output parameters.
     */
    outputs: Array<LrOutputDetails>;
};

/**
 * ApplyPresetRequest
 */
export type ApplyPresetRequest = {
    inputs: ApplyPresetInput;
    /**
     * Apply preset output parameters.
     */
    outputs: Array<LrOutputDetails>;
};

/**
 * ApplyPresetFromXmpContentRequest
 */
export type ApplyPresetFromXmpContentRequest = {
    inputs: ApplyPresetXmpInput;
    options: ApplyPresetXmpOptions;
    /**
     * Apply preset XMP output parameters.
     */
    outputs: Array<LrOutputDetails>;
};

/**
 * ApplyPresetXmpInput
 */
export type ApplyPresetXmpInput = {
    source: StorageDetails;
};

/**
 * ErrorDetails
 *
 * Details of the error returned.
 */
export type ErrorDetails = {
    /**
     * Parameter name.
     */
    name?: string;
    /**
     * Reason for the error.
     */
    reason?: string;
};

/**
 * ApplyPresetInput
 */
export type ApplyPresetInput = {
    source: StorageDetails;
    /**
     * An array describing the list of presets to apply. The preset objects will be one of 'external', 'azure', or 'dropbox'.
     */
    presets: Array<StorageDetails>;
};

/**
 * Links
 */
export type Links = {
    self?: StorageDetails;
};

/**
 * AutoStraightOptions
 */
export type AutoStraightOptions = {
    uprightMode: UprightMode;
    /**
     * If the straightened image should be constrained and cropped to remove all blank edges around an image.
     */
    constrainCrop?: boolean;
};

/**
 * EditOptions
 */
export type EditOptions = {
    Contrast?: number;
    Saturation?: number;
    VignetteAmount?: number;
    Vibrance?: number;
    Highlights?: number;
    Shadows?: number;
    Whites?: number;
    Blacks?: number;
    Clarity?: number;
    Dehaze?: number;
    Texture?: number;
    Sharpness?: number;
    ColorNoiseReduction?: number;
    NoiseReduction?: number;
    SharpenDetail?: number;
    SharpenEdgeMasking?: number;
    Exposure?: number;
    SharpenRadius?: number;
    WhiteBalance?: WhiteBalance;
};

/**
 * ApplyPresetXmpOptions
 *
 * Options for applying a preset XMP to an image.
 */
export type ApplyPresetXmpOptions = {
    /**
     * The XMP to apply.
     */
    xmp: string;
    /**
     * The combination of flip and/or rotate to apply.
     */
    orientation?: number;
};

/**
 * JobOutputDetails
 */
export type JobOutputDetails = {
    /**
     * The original input file path.
     */
    input?: string;
    status?: JobStatus;
    _links?: Links;
    /**
     * Description of the exact error that is reported by the requested job. Will appear in the response only if there is an error.
     */
    details?: string;
};

/**
 * SelfLink
 *
 * Self link for the job status.
 */
export type SelfLink = {
    /**
     * Job Status URL.
     */
    href?: string;
};

/**
 * JobStatus
 *
 * Status of the job.
 */
export type JobStatus = 'pending' | 'running' | 'succeeded' | 'failed';

/**
 * StorageType
 *
 * Storage location.
 */
export type StorageType = 'external' | 'azure' | 'dropbox';

/**
 * UprightMode
 *
 * The upright mode to use. If you have the options block, then this is a required field. If options block is not specified, then the appropriate upright mode will automatically be selected.
 */
export type UprightMode = 'auto' | 'full' | 'level' | 'vertical';

/**
 * WhiteBalance
 *
 * White balance settings.
 */
export type WhiteBalance = 'As Shot' | 'Auto' | 'Cloudy' | 'Custom' | 'Daylight' | 'Flash' | 'Fluorescent' | 'Shade' | 'Tungsten';

export type AutoStraightenImageData = {
    /**
     * Request body for the auto straighten operation.
     */
    body: AutoStraightenImageRequest;
    path?: never;
    query?: never;
    url: '/lrService/autoStraighten';
};

export type AutoStraightenImageErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable To Upload Asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
};

export type AutoStraightenImageError = AutoStraightenImageErrors[keyof AutoStraightenImageErrors];

export type AutoStraightenImageResponses = {
    /**
     * Accepted
     */
    202: JobStatusLinkResponse;
};

export type AutoStraightenImageResponse = AutoStraightenImageResponses[keyof AutoStraightenImageResponses];

export type ApplyAutoToneData = {
    /**
     * Request body for the auto tone operation.
     */
    body: ApplyAutoToneRequest;
    path?: never;
    query?: never;
    url: '/lrService/autoTone';
};

export type ApplyAutoToneErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable To Upload Asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
};

export type ApplyAutoToneError = ApplyAutoToneErrors[keyof ApplyAutoToneErrors];

export type ApplyAutoToneResponses = {
    /**
     * Accepted
     */
    202: JobStatusLinkResponse;
};

export type ApplyAutoToneResponse = ApplyAutoToneResponses[keyof ApplyAutoToneResponses];

export type ApplyEditsData = {
    /**
     * Request body for the edit operation.
     */
    body: ApplyEditsRequest;
    path?: never;
    query?: never;
    url: '/lrService/edit';
};

export type ApplyEditsErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable To Upload Asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
};

export type ApplyEditsError = ApplyEditsErrors[keyof ApplyEditsErrors];

export type ApplyEditsResponses = {
    /**
     * Accepted
     */
    202: JobStatusLinkResponse;
};

export type ApplyEditsResponse = ApplyEditsResponses[keyof ApplyEditsResponses];

export type ApplyPresetData = {
    /**
     * Request body for the presets operation.
     */
    body: ApplyPresetRequest;
    path?: never;
    query?: never;
    url: '/lrService/presets';
};

export type ApplyPresetErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable To Upload Asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
};

export type ApplyPresetError = ApplyPresetErrors[keyof ApplyPresetErrors];

export type ApplyPresetResponses = {
    /**
     * Accepted
     */
    202: JobStatusLinkResponse;
};

export type ApplyPresetResponse = ApplyPresetResponses[keyof ApplyPresetResponses];

export type ApplyPresetFromXmpContentData = {
    /**
     * Request body for the XMP operation.
     */
    body: ApplyPresetFromXmpContentRequest;
    path?: never;
    query?: never;
    url: '/lrService/xmp';
};

export type ApplyPresetFromXmpContentErrors = {
    /**
     * Input Validation Error
     */
    400: InputValidationError;
    /**
     * Trial Limit Exceeded Error
     */
    402: TrialLimitExceededError;
    /**
     * Forbidden
     */
    403: JobError;
    /**
     * Requested Resource Was Not Found
     */
    404: JobError;
    /**
     * Unable To Upload Asset
     */
    409: JobError;
    /**
     * Asset Link Invalid
     */
    410: JobError;
};

export type ApplyPresetFromXmpContentError = ApplyPresetFromXmpContentErrors[keyof ApplyPresetFromXmpContentErrors];

export type ApplyPresetFromXmpContentResponses = {
    /**
     * Accepted
     */
    202: JobStatusLinkResponse;
};

export type ApplyPresetFromXmpContentResponse = ApplyPresetFromXmpContentResponses[keyof ApplyPresetFromXmpContentResponses];

export type LrJobStatusData = {
    body?: never;
    path: {
        /**
         * Identifier of the job to get status for.
         */
        jobId: string;
    };
    query?: never;
    url: '/lrService/status/{jobId}';
};

export type LrJobStatusResponses = {
    /**
     * Job Status
     */
    202: LrJobApiResponse;
};

export type LrJobStatusResponse = LrJobStatusResponses[keyof LrJobStatusResponses];
