/**
 * OpenAPI-derived MCP tool definitions.
 * @generated by scripts/generate-openapi-mcp-tools.mjs — do not edit.
 * @see https://github.com/harsha-iiiv/openapi-mcp-generator
 */
export const openapiMcpTools = [
  {
    "name": "autoStraightenImage",
    "description": "Auto-straighten an image by applying the Auto Upright transformation.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "requestBody": {
          "title": "AutoStraightenImageRequest",
          "type": "object",
          "required": [
            "inputs",
            "outputs"
          ],
          "properties": {
            "inputs": {
              "title": "StorageDetails",
              "type": "object",
              "required": [
                "href",
                "storage"
              ],
              "properties": {
                "href": {
                  "type": "string",
                  "description": "Pre-signed GET URL for the source asset."
                },
                "storage": {
                  "title": "StorageType",
                  "enum": [
                    "external",
                    "azure",
                    "dropbox"
                  ],
                  "type": "string",
                  "description": "Storage location."
                }
              },
              "description": "File on Adobe's cloud or an external service (like AWS S3, Azure, Dropbox)."
            },
            "options": {
              "title": "AutoStraightOptions",
              "required": [
                "uprightMode"
              ],
              "type": "object",
              "properties": {
                "uprightMode": {
                  "title": "UprightMode",
                  "enum": [
                    "auto",
                    "full",
                    "level",
                    "vertical"
                  ],
                  "type": "string",
                  "description": "The upright mode to use. If you have the options block, then this is a required field. If options block is not specified, then the appropriate upright mode will automatically be selected."
                },
                "constrainCrop": {
                  "type": "boolean",
                  "description": "If the straightened image should be constrained and cropped to remove all blank edges around an image.",
                  "default": true
                }
              }
            },
            "outputs": {
              "type": "array",
              "items": {
                "title": "LrOutputDetails",
                "type": "object",
                "required": [
                  "href",
                  "storage",
                  "type"
                ],
                "properties": {
                  "href": {
                    "type": "string",
                    "description": "Pre-signed POST URL to the output file."
                  },
                  "storage": {
                    "title": "StorageType",
                    "enum": [
                      "external",
                      "azure",
                      "dropbox"
                    ],
                    "type": "string",
                    "description": "Storage location."
                  },
                  "type": {
                    "title": "ImageFormatType",
                    "enum": [
                      "image/jpeg",
                      "image/png",
                      "image/x-adobe-dng",
                      "application/rdf+xml"
                    ],
                    "type": "string",
                    "description": "Desired output image format."
                  },
                  "overwrite": {
                    "type": "boolean",
                    "default": true,
                    "description": "Determines if the output file should be overwritten if it already exists. This flag is used only for Adobe cloud storage."
                  },
                  "quality": {
                    "maximum": 12,
                    "minimum": 1,
                    "type": "number",
                    "default": 12,
                    "description": "Quality of the JPEG outputs (will be ignored for other output types). Ranges from 1 to 12, with 12 as the highest quality."
                  }
                }
              },
              "description": "Only a single output is supported currently."
            }
          },
          "description": "Request body for the auto straighten operation."
        }
      },
      "required": [
        "requestBody"
      ]
    },
    "method": "post",
    "pathTemplate": "/lrService/autoStraighten",
    "parameters": [],
    "executionParameters": [],
    "requestBodyContentType": "application/json",
    "securityRequirements": [
      {
        "ApiKeyAuth": []
      },
      {
        "BearerAuth": []
      }
    ],
    "operationId": "autoStraightenImage",
    "baseUrl": "https://image.adobe.io"
  },
  {
    "name": "applyAutoTone",
    "description": "Automatically correct exposure, contrast, sharpness, and saturation on an image.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "requestBody": {
          "title": "ApplyAutoToneRequest",
          "type": "object",
          "required": [
            "inputs",
            "outputs"
          ],
          "properties": {
            "inputs": {
              "title": "StorageDetails",
              "type": "object",
              "required": [
                "href",
                "storage"
              ],
              "properties": {
                "href": {
                  "type": "string",
                  "description": "Pre-signed GET URL for the source asset."
                },
                "storage": {
                  "title": "StorageType",
                  "enum": [
                    "external",
                    "azure",
                    "dropbox"
                  ],
                  "type": "string",
                  "description": "Storage location."
                }
              },
              "description": "File on Adobe's cloud or an external service (like AWS S3, Azure, Dropbox)."
            },
            "outputs": {
              "type": "array",
              "items": {
                "title": "LrOutputDetails",
                "type": "object",
                "required": [
                  "href",
                  "storage",
                  "type"
                ],
                "properties": {
                  "href": {
                    "type": "string",
                    "description": "Pre-signed POST URL to the output file."
                  },
                  "storage": {
                    "title": "StorageType",
                    "enum": [
                      "external",
                      "azure",
                      "dropbox"
                    ],
                    "type": "string",
                    "description": "Storage location."
                  },
                  "type": {
                    "title": "ImageFormatType",
                    "enum": [
                      "image/jpeg",
                      "image/png",
                      "image/x-adobe-dng",
                      "application/rdf+xml"
                    ],
                    "type": "string",
                    "description": "Desired output image format."
                  },
                  "overwrite": {
                    "type": "boolean",
                    "default": true,
                    "description": "Determines if the output file should be overwritten if it already exists. This flag is used only for Adobe cloud storage."
                  },
                  "quality": {
                    "maximum": 12,
                    "minimum": 1,
                    "type": "number",
                    "default": 12,
                    "description": "Quality of the JPEG outputs (will be ignored for other output types). Ranges from 1 to 12, with 12 as the highest quality."
                  }
                }
              },
              "description": "Only a single output is supported currently."
            }
          },
          "description": "Request body for the auto tone operation."
        }
      },
      "required": [
        "requestBody"
      ]
    },
    "method": "post",
    "pathTemplate": "/lrService/autoTone",
    "parameters": [],
    "executionParameters": [],
    "requestBodyContentType": "application/json",
    "securityRequirements": [
      {
        "ApiKeyAuth": []
      },
      {
        "BearerAuth": []
      }
    ],
    "operationId": "applyAutoTone",
    "baseUrl": "https://image.adobe.io"
  },
  {
    "name": "applyEdits",
    "description": "Apply one or more Lightroom edits (exposure, contrast, sharpness, saturation) to an image.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "requestBody": {
          "title": "ApplyEditsRequest",
          "type": "object",
          "required": [
            "inputs",
            "options",
            "outputs"
          ],
          "properties": {
            "inputs": {
              "type": "object",
              "description": "A hash describing an input image to edit. The input object will be one of 'external', 'azure', or 'dropbox'.",
              "required": [
                "source"
              ],
              "properties": {
                "source": {
                  "title": "StorageDetails",
                  "type": "object",
                  "required": [
                    "href",
                    "storage"
                  ],
                  "properties": {
                    "href": {
                      "type": "string",
                      "description": "Pre-signed GET URL for the source asset."
                    },
                    "storage": {
                      "title": "StorageType",
                      "enum": [
                        "external",
                        "azure",
                        "dropbox"
                      ],
                      "type": "string",
                      "description": "Storage location."
                    }
                  },
                  "description": "File on Adobe's cloud or an external service (like AWS S3, Azure, Dropbox)."
                }
              }
            },
            "options": {
              "title": "EditOptions",
              "type": "object",
              "properties": {
                "Contrast": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Saturation": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "VignetteAmount": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Vibrance": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Highlights": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Shadows": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Whites": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Blacks": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Clarity": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Dehaze": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Texture": {
                  "maximum": 100,
                  "minimum": -100,
                  "type": "number",
                  "format": "int32"
                },
                "Sharpness": {
                  "maximum": 150,
                  "minimum": 0,
                  "type": "number",
                  "format": "int32"
                },
                "ColorNoiseReduction": {
                  "maximum": 100,
                  "minimum": 0,
                  "type": "number",
                  "format": "int32"
                },
                "NoiseReduction": {
                  "maximum": 100,
                  "minimum": 0,
                  "type": "number",
                  "format": "int32"
                },
                "SharpenDetail": {
                  "maximum": 100,
                  "minimum": 0,
                  "type": "number",
                  "format": "int32"
                },
                "SharpenEdgeMasking": {
                  "maximum": 10,
                  "minimum": 0,
                  "type": "number",
                  "format": "int32"
                },
                "Exposure": {
                  "maximum": 5,
                  "minimum": -5,
                  "type": "number"
                },
                "SharpenRadius": {
                  "maximum": 3,
                  "minimum": 0.5,
                  "type": "number"
                },
                "WhiteBalance": {
                  "title": "WhiteBalance",
                  "description": "White balance settings.",
                  "enum": [
                    "As Shot",
                    "Auto",
                    "Cloudy",
                    "Custom",
                    "Daylight",
                    "Flash",
                    "Fluorescent",
                    "Shade",
                    "Tungsten"
                  ],
                  "type": "string"
                }
              }
            },
            "outputs": {
              "type": "array",
              "items": {
                "title": "LrOutputDetails",
                "type": "object",
                "required": [
                  "href",
                  "storage",
                  "type"
                ],
                "properties": {
                  "href": {
                    "type": "string",
                    "description": "Pre-signed POST URL to the output file."
                  },
                  "storage": {
                    "title": "StorageType",
                    "enum": [
                      "external",
                      "azure",
                      "dropbox"
                    ],
                    "type": "string",
                    "description": "Storage location."
                  },
                  "type": {
                    "title": "ImageFormatType",
                    "enum": [
                      "image/jpeg",
                      "image/png",
                      "image/x-adobe-dng",
                      "application/rdf+xml"
                    ],
                    "type": "string",
                    "description": "Desired output image format."
                  },
                  "overwrite": {
                    "type": "boolean",
                    "default": true,
                    "description": "Determines if the output file should be overwritten if it already exists. This flag is used only for Adobe cloud storage."
                  },
                  "quality": {
                    "maximum": 12,
                    "minimum": 1,
                    "type": "number",
                    "default": 12,
                    "description": "Quality of the JPEG outputs (will be ignored for other output types). Ranges from 1 to 12, with 12 as the highest quality."
                  }
                }
              },
              "description": "Edit photo output parameters."
            }
          },
          "description": "Request body for the edit operation."
        }
      },
      "required": [
        "requestBody"
      ]
    },
    "method": "post",
    "pathTemplate": "/lrService/edit",
    "parameters": [],
    "executionParameters": [],
    "requestBodyContentType": "application/json",
    "securityRequirements": [
      {
        "ApiKeyAuth": []
      },
      {
        "BearerAuth": []
      }
    ],
    "operationId": "applyEdits",
    "baseUrl": "https://image.adobe.io"
  },
  {
    "name": "applyPreset",
    "description": "Apply one or more XMP Lightroom presets to the given image, by using the given preset XMP file(s).",
    "inputSchema": {
      "type": "object",
      "properties": {
        "requestBody": {
          "title": "ApplyPresetRequest",
          "type": "object",
          "required": [
            "inputs",
            "outputs"
          ],
          "properties": {
            "inputs": {
              "title": "ApplyPresetInput",
              "type": "object",
              "required": [
                "source",
                "presets"
              ],
              "properties": {
                "source": {
                  "title": "StorageDetails",
                  "type": "object",
                  "required": [
                    "href",
                    "storage"
                  ],
                  "properties": {
                    "href": {
                      "type": "string",
                      "description": "Pre-signed GET URL for the source asset."
                    },
                    "storage": {
                      "title": "StorageType",
                      "enum": [
                        "external",
                        "azure",
                        "dropbox"
                      ],
                      "type": "string",
                      "description": "Storage location."
                    }
                  },
                  "description": "File on Adobe's cloud or an external service (like AWS S3, Azure, Dropbox)."
                },
                "presets": {
                  "type": "array",
                  "items": {
                    "title": "StorageDetails",
                    "type": "object",
                    "required": [
                      "href",
                      "storage"
                    ],
                    "properties": {
                      "href": {
                        "type": "string",
                        "description": "Pre-signed GET URL for the source asset."
                      },
                      "storage": {
                        "title": "StorageType",
                        "enum": [
                          "external",
                          "azure",
                          "dropbox"
                        ],
                        "type": "string",
                        "description": "Storage location."
                      }
                    },
                    "description": "File on Adobe's cloud or an external service (like AWS S3, Azure, Dropbox)."
                  },
                  "description": "An array describing the list of presets to apply. The preset objects will be one of 'external', 'azure', or 'dropbox'."
                }
              }
            },
            "outputs": {
              "type": "array",
              "items": {
                "title": "LrOutputDetails",
                "type": "object",
                "required": [
                  "href",
                  "storage",
                  "type"
                ],
                "properties": {
                  "href": {
                    "type": "string",
                    "description": "Pre-signed POST URL to the output file."
                  },
                  "storage": {
                    "title": "StorageType",
                    "enum": [
                      "external",
                      "azure",
                      "dropbox"
                    ],
                    "type": "string",
                    "description": "Storage location."
                  },
                  "type": {
                    "title": "ImageFormatType",
                    "enum": [
                      "image/jpeg",
                      "image/png",
                      "image/x-adobe-dng",
                      "application/rdf+xml"
                    ],
                    "type": "string",
                    "description": "Desired output image format."
                  },
                  "overwrite": {
                    "type": "boolean",
                    "default": true,
                    "description": "Determines if the output file should be overwritten if it already exists. This flag is used only for Adobe cloud storage."
                  },
                  "quality": {
                    "maximum": 12,
                    "minimum": 1,
                    "type": "number",
                    "default": 12,
                    "description": "Quality of the JPEG outputs (will be ignored for other output types). Ranges from 1 to 12, with 12 as the highest quality."
                  }
                }
              },
              "description": "Apply preset output parameters."
            }
          },
          "description": "Request body for the presets operation."
        }
      },
      "required": [
        "requestBody"
      ]
    },
    "method": "post",
    "pathTemplate": "/lrService/presets",
    "parameters": [],
    "executionParameters": [],
    "requestBodyContentType": "application/json",
    "securityRequirements": [
      {
        "ApiKeyAuth": []
      },
      {
        "BearerAuth": []
      }
    ],
    "operationId": "applyPreset",
    "baseUrl": "https://image.adobe.io"
  },
  {
    "name": "applyPresetFromXmpContent",
    "description": "Apply XMP-based Lightroom preset to an image. XMP content is passed inline to the API.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "requestBody": {
          "title": "ApplyPresetFromXmpContentRequest",
          "type": "object",
          "required": [
            "inputs",
            "options",
            "outputs"
          ],
          "properties": {
            "inputs": {
              "title": "ApplyPresetXmpInput",
              "type": "object",
              "required": [
                "source"
              ],
              "properties": {
                "source": {
                  "title": "StorageDetails",
                  "type": "object",
                  "required": [
                    "href",
                    "storage"
                  ],
                  "properties": {
                    "href": {
                      "type": "string",
                      "description": "Pre-signed GET URL for the source asset."
                    },
                    "storage": {
                      "title": "StorageType",
                      "enum": [
                        "external",
                        "azure",
                        "dropbox"
                      ],
                      "type": "string",
                      "description": "Storage location."
                    }
                  },
                  "description": "File on Adobe's cloud or an external service (like AWS S3, Azure, Dropbox)."
                }
              }
            },
            "options": {
              "title": "ApplyPresetXmpOptions",
              "description": "Options for applying a preset XMP to an image.",
              "type": "object",
              "required": [
                "xmp"
              ],
              "properties": {
                "xmp": {
                  "type": "string",
                  "description": "The XMP to apply."
                },
                "orientation": {
                  "maximum": 8,
                  "minimum": 1,
                  "type": "number",
                  "description": "The combination of flip and/or rotate to apply."
                }
              }
            },
            "outputs": {
              "type": "array",
              "items": {
                "title": "LrOutputDetails",
                "type": "object",
                "required": [
                  "href",
                  "storage",
                  "type"
                ],
                "properties": {
                  "href": {
                    "type": "string",
                    "description": "Pre-signed POST URL to the output file."
                  },
                  "storage": {
                    "title": "StorageType",
                    "enum": [
                      "external",
                      "azure",
                      "dropbox"
                    ],
                    "type": "string",
                    "description": "Storage location."
                  },
                  "type": {
                    "title": "ImageFormatType",
                    "enum": [
                      "image/jpeg",
                      "image/png",
                      "image/x-adobe-dng",
                      "application/rdf+xml"
                    ],
                    "type": "string",
                    "description": "Desired output image format."
                  },
                  "overwrite": {
                    "type": "boolean",
                    "default": true,
                    "description": "Determines if the output file should be overwritten if it already exists. This flag is used only for Adobe cloud storage."
                  },
                  "quality": {
                    "maximum": 12,
                    "minimum": 1,
                    "type": "number",
                    "default": 12,
                    "description": "Quality of the JPEG outputs (will be ignored for other output types). Ranges from 1 to 12, with 12 as the highest quality."
                  }
                }
              },
              "description": "Apply preset XMP output parameters."
            }
          },
          "description": "Request body for the XMP operation."
        }
      },
      "required": [
        "requestBody"
      ]
    },
    "method": "post",
    "pathTemplate": "/lrService/xmp",
    "parameters": [],
    "executionParameters": [],
    "requestBodyContentType": "application/json",
    "securityRequirements": [
      {
        "ApiKeyAuth": []
      },
      {
        "BearerAuth": []
      }
    ],
    "operationId": "applyPresetFromXmpContent",
    "baseUrl": "https://image.adobe.io"
  },
  {
    "name": "lrJobStatus",
    "description": "Get job status of a Lightroom job.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "jobId": {
          "type": "string",
          "description": "Identifier of the job to get status for."
        }
      },
      "required": [
        "jobId"
      ]
    },
    "method": "get",
    "pathTemplate": "/lrService/status/{jobId}",
    "parameters": [
      {
        "name": "jobId",
        "in": "path",
        "description": "Identifier of the job to get status for.",
        "required": true,
        "schema": {
          "type": "string"
        }
      }
    ],
    "executionParameters": [
      {
        "name": "jobId",
        "in": "path"
      }
    ],
    "securityRequirements": [
      {
        "ApiKeyAuth": []
      },
      {
        "BearerAuth": []
      }
    ],
    "operationId": "lrJobStatus",
    "baseUrl": "https://image.adobe.io"
  }
] as const;

  export type OpenapiMcpTool = (typeof openapiMcpTools)[number];
  