// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://firefly-api.adobe.io' | (string & {});
};

/**
 * AlignmentHorizontal
 *
 * An enumeration.
 */
export type AlignmentHorizontal = 'center' | 'left' | 'right';

/**
 * AlignmentVertical
 *
 * An enumeration.
 */
export type AlignmentVertical = 'center' | 'top' | 'bottom';

/**
 * ApiError
 *
 * The error within the error response.
 */
export type ApiError = {
    error_code: ColligoErrorCodeAsyncV3;
    /**
     * Message
     */
    message?: string;
    /**
     * Stack Trace
     */
    stack_trace?: Array<string>;
    /**
     * Validation Errors
     */
    validation_errors?: Array<ValidationErrorMessage>;
};

/**
 * AspectRatio
 */
export type AspectRatio = '1:1' | '4:3' | '3:4' | '16:9' | '9:16';

/**
 * ApiErrorGeneric
 *
 * The error within the error response for non-400 failure responses.
 */
export type ApiErrorGeneric = {
    /**
     * The error code.
     */
    error_code?: string;
    /**
     * Message
     *
     * A human-readable error message.
     */
    message?: string;
};

export type AdaptiveCompositeRequest = {
    /**
     * Background image and fill area mask.
     */
    background: BackgroundInput;
    /**
     * Object image and optional mask.
     */
    object: AdaptiveObjectInput;
    /**
     * Number of output variations to generate.
     */
    numVariations?: number;
    /**
     * Array of seed image IDs. These reference images help ensure consistent image generation across multiple API calls. If specified alongside numVariations, the number of seeds must equal numVariations. Defaults: 1 variation → [333], 2 → [333, 222], 3 → [333, 222, 111].
     */
    seeds?: Array<number>;
    /**
     * Controls how much the object's colors and lighting are adjusted to match the background scene.
     */
    harmonization?: number;
    /**
     * Controls shadow intensity in the composited result. Lower values reduce shadow.
     */
    shadowIntensity?: number;
    /**
     * When true, preserves original background details within the masked area during compositing.
     */
    preserveBackground?: boolean;
    /**
     * Output format specification.
     */
    output?: OutputSpec;
};

export type AdaptiveObjectInput = {
    /**
     * Object image to be composited onto the background.
     */
    image: ImageRef;
    /**
     * Optional object mask.
     */
    mask?: ImageRef;
};

export type AsyncJobResponse = {
    /**
     * Current status of the job.
     */
    status?: string;
    /**
     * Job URN identifier.
     */
    jobId?: string;
    /**
     * URL to poll for job status.
     */
    statusUrl?: string;
    /**
     * URL to cancel the job.
     */
    cancelUrl?: string;
};

export type BackgroundInput = {
    /**
     * Background image on which the object will be placed.
     */
    image: ImageRef;
    /**
     * Mask defining where the object should be placed on the background.
     */
    fillAreaMask: ImageRef;
};

export type ImageRef = {
    source: ImageSource;
};

/**
 * The image source. Exactly one of `url` or `uploadId` must be provided in the request.
 */
export type ImageSource = {
    /**
     * If this object represents a file in our S3 temp storage system, the ID for that file.
     */
    uploadId?: string;
    /**
     * Pre-signed URL of the image from a supported domain. [See Allowed storage domains](https://github.com/your-repo/your-project/blob/main/src/pages/getting-started/usage-notes/index.md#allowed-storage-domains) for the current list.
     */
    url?: string;
};

export type ObjectInput = {
    /**
     * Object image to be composited onto the background.
     */
    image: ImageRef;
};

export type OutputSpec = {
    /**
     * MIME type for the output image.
     */
    mediaType?: 'image/png' | 'image/jpeg' | 'image/webp' | 'image/jxl';
};

export type PreciseCompositeRequest = {
    /**
     * Background image and fill area mask specifying object placement.
     */
    background: BackgroundInput;
    /**
     * Object image to be placed on the background.
     */
    object: ObjectInput;
    /**
     * Number of output variations to generate.
     */
    numVariations?: number;
    /**
     * Random seeds for each variation. Count must match numVariations if both are provided. Defaults: 1 variation → [333], 2 → [333, 222], 3 → [333, 222, 111].
     */
    seeds?: Array<number>;
    /**
     * Controls blend between harmonized and original object appearance (0.0 = fully harmonized, 1.0 = original preserved).
     */
    blend?: number;
    /**
     * Output format specification.
     */
    output?: OutputSpec;
};

export type ValidationErrorDetail = {
    /**
     * Path to the field that caused the error.
     */
    loc?: Array<string | number>;
    /**
     * Human-readable error message.
     */
    msg?: string;
    /**
     * Error type identifier.
     */
    type?: string;
    /**
     * Additional context about the error.
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ValidationErrorCode422
 *
 * Error code for HTTP 422 responses (request validation only).
 */
export type ValidationErrorCode422 = 'validation_error' | 'cai_assertion_violation_error';

/**
 * ValidationErrorResponse
 *
 * Error response body for HTTP 422 (validation failures).
 */
export type ValidationErrorResponse = {
    error_code: ValidationErrorCode422;
    /**
     * Human-readable error description.
     */
    message?: string;
    /**
     * List of field-level validation errors.
     */
    validation_errors?: Array<ValidationErrorDetail>;
};

/**
 * ContentPolicyErrorCode451
 *
 * Error code for HTTP 451 responses (content policy, legal, or safety).
 */
export type ContentPolicyErrorCode451 = 'legal_error' | 'prompt_unsafe' | 'prompt_entity_denied' | 'image_unsafe' | 'video_unsafe' | 'reference_image_unsafe_error' | 'input_media_unsafe';

/**
 * ContentPolicyErrorResponse
 *
 * Error response body for HTTP 451 (content policy, legal, or safety).
 */
export type ContentPolicyErrorResponse = {
    error_code: ContentPolicyErrorCode451;
    /**
     * Human-readable error description.
     */
    message?: string;
};

/**
 * JobOutput
 *
 * A single output entry from the job.
 */
export type JobOutput = {
    /**
     * Random seed used for generation.
     */
    seed: number;
    /**
     * The generated output image.
     */
    image: PublicBinaryOutput;
};

/**
 * JobPollPayload
 *
 * Returned when the job is pending, running, failed, cancelled, cancel_pending, or timeout.
 */
export type JobPollPayload = {
    /**
     * Current non-succeeded job status.
     */
    status: 'pending' | 'running' | 'failed' | 'cancelled' | 'cancel_pending' | 'timeout';
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * Error code present when status is failed, cancelled, cancel_pending, or timeout.
     */
    error_code?: string;
    /**
     * Human-readable string describing the error or status.
     */
    message?: string;
};

/**
 * JobResult
 *
 * Contains output data returned by a successfully completed job.
 */
export type JobResult = {
    /**
     * List of generated outputs.
     */
    outputs: Array<JobOutput>;
};

/**
 * JobResponse
 *
 * Represents the job response, which may be either in progress or completed.
 */
export type JobResponse = ({
    status: 'succeeded';
} & JobSucceededPayload) | ({
    status: 'running' | 'failed' | 'cancelled' | 'cancel_pending' | 'timeout';
} & JobPollPayload);

/**
 * JobSucceededPayload
 *
 * Returned when the job has completed successfully.
 */
export type JobSucceededPayload = {
    /**
     * Indicates that the job has succeeded.
     */
    status: 'succeeded';
    /**
     * The job ID.
     */
    jobId: string;
    /**
     * The result of the completed job. The schema depends on the async operation (for example generation, composite, or upscale).
     */
    result: JobResult | CreativeUpsamplerResponse;
};

/**
 * PublicBinary-Output
 *
 * Represents binary output (e.g., image, mesh, etc.) with pre-signed URL or storage ID.
 */
export type PublicBinaryOutput = {
    /**
     * Temporary pre-signed URL to access the output file.
     */
    url: string;
};

/**
 * AsyncAcceptResponseV3
 */
export type AsyncAcceptResponseV3 = {
    /**
     * Cancel URL
     *
     * The URL to cancel the job.
     */
    cancelUrl: string;
    /**
     * Job ID
     *
     * The ID of the job.
     */
    jobId: string;
    /**
     * Status URL
     *
     * The URL to check the status of the job.
     */
    statusUrl: string;
};

/**
 * AsyncApiErrorV3
 *
 * The error within the error response.
 */
export type AsyncApiErrorV3 = {
    /**
     * Error Code
     */
    error_code?: string | ColligoErrorCodeAsyncV3 | ColliogAsyncStatusErrorCodeV3 | ColligoAsyncCancelErrorCodeV3;
    /**
     * Job ID
     */
    jobId?: string;
    /**
     * Message
     */
    message?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Validation Errors
     */
    validation_errors?: Array<ValidationErrorMessage>;
};

/**
 * AsyncTaskLink
 */
export type AsyncTaskLink = {
    /**
     * Href
     */
    href: string;
};

/**
 * AsyncTaskLinkType
 */
export type AsyncTaskLinkType = 'cancel' | 'result';

/**
 * AsyncTaskResponse
 *
 * Response type for async requests.
 */
export type AsyncTaskResponse = {
    /**
     * Links
     */
    links: {
        [key in AsyncTaskLinkType]?: AsyncTaskLink;
    };
    /**
     * Progress
     */
    progress?: number;
};

/**
 * AsyncTaskResponseV3
 */
export type AsyncTaskResponseV3 = {
    /**
     * Job ID
     *
     * The ID of the async job.
     */
    jobId: string;
    /**
     * Progress
     */
    progress?: number;
    /**
     * Result
     *
     * The result of the job, if the job has completed.
     */
    result?: GenerateImagesResponseV3 | GenerateSimilarImagesResponseV3 | ExpandImageResponseV3 | FillImageResponseV3 | GenerateObjectCompositeResponseV3;
    /**
     * Status of the job
     *
     * The status of the job.
     */
    status: 'pending' | 'running' | 'succeeded' | 'failed' | 'canceled';
};

/**
 * BaseInputImageV3
 */
export type BaseInputImageV3 = {
    /**
     * Source image that Firefly expands, fills, uses to generate similar images, or upscales (beta).
     */
    source: PublicBinaryInputV3;
};

/**
 * CreativeUpscaleAcceptResponseV3
 *
 * Response for async upscale requests (beta). Use links.result.href to poll for status and links.cancel.href to cancel.
 */
export type CreativeUpscaleAcceptResponseV3 = {
    /**
     * Links to cancel and to fetch the job status or result.
     */
    links: {
        [key: string]: CreativeUpscaleTaskLink;
    };
    /**
     * Progress percentage when available (for example when polling status).
     */
    progress?: number;
};

/**
 * CreativeUpscaleTaskLink
 */
export type CreativeUpscaleTaskLink = {
    /**
     * URL for the cancel or result endpoint.
     */
    href: string;
};

/**
 * CreativeUpsamplerRequestV3
 *
 * Request body for upscaling an image (beta). Provide the input image via uploadId from storage or a presigned URL. Seeds are required for reproducible results.
 */
export type CreativeUpsamplerRequestV3 = {
    /**
     * The input image for the upsampler (source uploadId or url).
     */
    image: BaseInputImageV3;
    /**
     * The seed for each variation. Provide one seed per output (1–4 seeds).
     */
    seeds: Array<number>;
    /**
     * The upscale factor (2, 3, 4, or 6). Output dimensions are input dimensions multiplied by this factor.
     */
    upscaleFactor?: UpsampleFactor;
};

/**
 * CreativeUpsamplerResponse
 *
 * Upscale result (beta). Each item in outputs is a storage reference for an upscaled image.
 */
export type CreativeUpsamplerResponse = {
    /**
     * The list of upscaled images (storage items).
     */
    outputs: Array<UpscaleBinaryOutput>;
    /**
     * The version of the upscale feature.
     */
    version: string;
};

/**
 * Supported upscale factors. Output size equals input size multiplied by this factor.
 */
export type UpsampleFactor = 2 | 3 | 4 | 6;

/**
 * UpscaleBinaryOutput
 *
 * Reference to output binary (for example an upscaled image). Use id in subsequent API calls or the presigned URL to download.
 */
export type UpscaleBinaryOutput = {
    /**
     * The internal ID for a storage item.
     */
    id?: string;
    /**
     * URL to download the file. Expires in one hour.
     */
    presignedUrl?: string;
    /**
     * Optional ID of the file in ACP. Must be an ACP File asset ID.
     */
    creativeCloudFileId?: string;
    /**
     * Optional ID of the component in ACP. Must be an ACP Component asset ID.
     */
    creativeCloudComponentId?: string;
    /**
     * Optional name for the item (for example for lookup in multipart responses).
     */
    name?: string;
};

/**
 * BaseInputMaskV3
 */
export type BaseInputMaskV3 = {
    /**
     * Original mask image.
     */
    source?: PublicBinaryInputV3;
};

/**
 * Body_expandImagesV3Async
 */
export type BodyExpandImagesV3Async = {
    /**
     * Files
     */
    files: Array<Blob | File>;
    request: ExpandImageRequestV3;
};

/**
 * Body_fillImagesV3Async
 */
export type BodyFillImagesV3Async = {
    /**
     * Files
     */
    files: Array<Blob | File>;
    request: FillImageRequestV3;
};

/**
 * Body_generateImagesV3Async
 */
export type BodyGenerateImagesV3Async = {
    /**
     * Files
     */
    files: Array<Blob | File>;
    request: GenerateImagesRequestV3;
};

/**
 * Body_generateObjectCompositeV3Async
 */
export type BodyGenerateObjectCompositeV3Async = {
    /**
     * Files
     */
    files: Array<Blob | File>;
    request: GenerateObjectCompositeRequestV3;
};

/**
 * Body_generateSimilarImagesV3Async
 */
export type BodyGenerateSimilarImagesV3Async = {
    /**
     * Files
     */
    files: Array<Blob | File>;
    request: GenerateSimilarImagesRequestV3;
};

/**
 * ColligoAsyncCancelErrorCodeV3
 *
 * An enumeration.
 */
export type ColligoAsyncCancelErrorCodeV3 = 'job_timeout' | 'job_completed' | 'unknown_job_id' | 'job_already_canceled' | 'job_cancel_failed';

/**
 * An enumeration.
 */
export type ColligoErrorCodeAsyncV3 = 'validation_error' | 'runtime_error' | 'timeout_error' | 'rate_limited' | 'access_error' | 'invalid_content_type' | 'empty_input_body' | 'bad_request';

/**
 * An enumeration.
 */
export type ColliogAsyncStatusErrorCodeV3 = 'unknown_job_id';

/**
 * The content class of the image.
 */
export type ContentClassV3 = 'photo' | 'art';

/**
 * Images expand payload
 */
export type ExpandImageRequestV3 = {
    /**
     * The image to expand. Use a URL or an <code>uploadID</code> as the source for the image. Firefly only allows these listed domains for input URLs in the request: <ul> <li><code>amazonaws.com</code></li> <li><code>windows.net</code></li> <li><code>dropboxusercontent.com</code></li> <li><code>storage.googleapis.com</code></li> </ul>.
     */
    image: InputImageV3;
    /**
     * Mask image which will be used to expand the given image.
     */
    mask?: InputMaskV3;
    /**
     * The number of variations to generate
     *
     * Generate this number of variations. <code>numVariations</code> defaults to the number of seed images, or to 1 if you do not specify seeds.
     */
    numVariations?: number;
    /**
     * The position of the source image after Firefly resizes it. The value describes the horizontal and vertical placement and dimensions of the image in the output. Note you cannot use placement for source images when you also apply a mask image.
     */
    placement?: Placement;
    /**
     * The prompt
     *
     * An optional text prompt up to 1024 characters. The longer the prompt the better Firefly performs.
     */
    prompt?: string;
    /**
     * The seed image for each variation
     *
     * Array of seed image IDs. These reference images help ensure consistent image generation across multiple API calls. For example, you can use the same seed to generate a similar image with different styles. If specified along with <code>numVariations</code>, the number of seeds must equal <code>numVariations</code>.
     */
    seeds?: Array<number>;
    /**
     * The size
     *
     * The desired width and height for the final expanded image in pixels. The maximum size for the output images is 3999px by 3999px.
     */
    size?: Size;
};

/**
 * Images expand response
 */
export type ExpandImageResponseV3 = {
    /**
     * The list of images
     *
     * Each image ID.
     */
    outputs: Array<OutputImageV3>;
    /**
     * When you provide size as input, this value is the same.
     */
    size: Size;
};

/**
 * Fill images payload
 */
export type FillImageRequestV3 = {
    /**
     * The image to expand. Use a URL or an <code>uploadID</code> as the source for the image. Firefly only allows these listed domains for input URLs in the request: <ul> <li><code>amazonaws.com</code></li> <li><code>windows.net</code></li> <li><code>dropboxusercontent.com</code></li> <li><code>storage.googleapis.com</code></li> </ul>.
     */
    image: InputImageV3;
    /**
     * Required. Selected areas of a background image that Firefly uses to fill the source image.
     */
    mask: InputMaskV3;
    /**
     * Avoid prompt
     *
     * An optional text prompt up to 1024 characters. Avoid these characteristics in the generated image. Not supported for Firefly Custom Models on Image Model 3 or Firefly Custom Models on Image Model 4.
     */
    negativePrompt?: string;
    /**
     * The number of variations
     *
     * Generate this number of variations. <code>numVariations</code> defaults to the number of seed images, or to 1 if you do not specify seeds.
     */
    numVariations?: number;
    /**
     * The prompt
     *
     * An optional text prompt up to 1024 characters. The longer the prompt the better Firefly performs.
     */
    prompt?: string;
    /**
     * The locale used to generate an image
     *
     * A hyphen-separated string combining the ISO 639-1 language code and the ISO 3166-1 region, such as en-US. When a locale is set, the prompt will be biased to generate more relevant content for that region. The locale will be auto-detected if not specified based on your profile and the accepted language header.
     */
    promptBiasingLocaleCode?: string;
    /**
     * The seed of each variation
     *
     * Array of seed image IDs. These reference images help ensure consistent image generation across multiple API calls. For example, you can use the same seed to generate a similar image with different styles. If specified along with <code>numVariations</code>, the number of seeds must equal <code>numVariations</code>.
     */
    seeds?: Array<number>;
    /**
     * The size
     *
     * The desired width and height for the final expanded image in pixels. The supported sizes for the output images are: <ul> <li>Square (1:1) - width 2048px, height 2048px </li> <li>Square (1:1) - width 1024px, height 1024px </li> <li>Landscape (4:3)  - width 2304px, height 1792px </li> <li>Portrait (3:4)  - width 1792px, height 2304px</li> <li>Widescreen (16:9) - width 2688px, height 1536px </li> <li>(7:4)  - width 1344px, height 768px </li> <li>(9:7) - width 1152px, height 896px </li> <li>(7:9) - width 896px, height 1152px</li> </ul>.
     */
    size?: Size;
};

/**
 * Fill images response.
 */
export type FillImageResponseV3 = {
    /**
     * The list of images
     *
     * Each image ID.
     */
    outputs: Array<OutputImageV3>;
    /**
     * When you provide size as input, this value is the same.
     */
    size: Size;
};

/**
 * FireflyModelId
 */
export type FireflyModelId = 'firefly_image';

/**
 * Generating images from prompt
 */
export type GenerateImagesRequestV3 = {
    /**
     * Directs the style of a generated image to be photographic or like fine art.
     */
    contentClass?: ContentClassV3;
    /**
     * Include the specific custom model ID when a custom model type is designated in the `x-model-version` header parameter.
     */
    customModelId?: string;
    /**
     * A negative prompt of things Firefly will try to avoid generating in the image. Not supported for Firefly Custom Models on Image Model 3 or Firefly Custom Models on Image Model 4.
     */
    negativePrompt?: string;
    /**
     * The number of variations to generate. <code>numVariations</code> defaults to the number of seed images, or to 1 if you do not specify `seeds`.
     */
    numVariations?: number;
    /**
     * A text prompt to support the generation of an image. The longer the prompt the better Firefly performs.
     */
    prompt: string;
    /**
     * A hyphen-separated string combining the ISO 639-1 language code and the ISO 3166-1 region (like en-US). When a locale is set, the prompt will be biased to generate more relevant content for that region. If not specified, the locale will be auto-detected based on your profile and the accepted language header.
     */
    promptBiasingLocaleCode?: string;
    /**
     * An array of seed image IDs. These reference images help ensure consistent image generation across multiple API calls. For example, use the same seed to generate a similar image in different styles. If specified along with <code>numVariations</code>, the number of seeds provided must equal <code>numVariations</code>.
     */
    seeds?: Array<number>;
    /**
     * The desired width and height for the final image, in pixels. Supported sizes for the output images with `image3` are: <ul> <li>Square (1:1) - width 2048px, height 2048px </li> <li>Square (1:1) - width 1024px, height 1024px </li> <li>Landscape (4:3)  - width 2304px, height 1792px </li> <li>Portrait (3:4)  - width 1792px, height 2304px</li>  <li>Widescreen (16:9) - width 2688px, height 1536px </li> <li>Widescreen (16:9) - width 2688px, height 1512px </li> <li>(7:4)  - width 1344px, height 768px </li> <li>(7:4)  - width 1344px, height 756px </li> <li>(9:7) - width 1152px, height 896px </li> <li>(7:9) - width 896px, height 1152px</li> </ul> Supported sizes for the output images with `image4` are: <ul> <li>(1:1) - width 2048px, height 2048px</li> <li>(4:3) - width 2304px, height 1792px</li> <li>(3:4) - width 1792px, height 2304px</li> <li>(16:9) - width 2688px, height 1536px</li> <li>(9:16) - width 1440px, height 2560px</li> </ul>.
     */
    size?: Size;
    /**
     * An object with the reference image details for structure.
     */
    structure?: StructureReferenceV3;
    /**
     * An object with the reference image details for style.
     */
    style?: StylesV3;
    /**
     * Only supported with the model version `image4_custom`. The `default` setting upscales generated images to 2k. The `low_creativity` setting refines the image generation by removing distortions, smoothing textures, and sometimes adding details (like freckles to faces in close-up). This setting is recommended for generating images with human subjects.
     */
    upsamplerType?: 'default' | 'low_creativity';
    /**
     * Adjust the overall intensity of your photo's characteristics, such as contrast, shadow, and hue. This is not supported with the model version `image4_custom`.
     */
    visualIntensity?: number;
};

/**
 * ImageGenerateRequestV3
 */
export type ImageGenerateRequestV3 = {
    /**
     * The prompt
     *
     * The prompt used to generate the image. The longer the prompt, the better.
     */
    prompt: string;
    /**
     * The aspect ratio of the requested generations. This controls the size of the generated image.
     */
    aspectRatio?: AspectRatio;
    /**
     * The specific model to use for image generation. Available options: 'firefly_image' for Firefly Image model.
     */
    modelId?: FireflyModelId;
    /**
     * Additional model-specific parameters for controlling the generation process.
     */
    modelSpecificPayload?: ModelSpecificPayloadV3;
    /**
     * The number of variations
     *
     * The number of image variations to generate. Greater than 1 is not supported. Only one image per variation is allowed. For multiple variations, send separate requests.
     */
    numVariations?: number;
    /**
     * Reference blobs
     *
     * List of reference blobs that will be used as additional input for the generation process. Only one reference image is supported. [Pre-signed URLs can be used from supported domains](https://developer.adobe.com/firefly-services/docs/firefly-api/getting-started/usage-notes/#image-api-usage).
     */
    referenceBlobs?: Array<ReferenceBlobV3>;
    /**
     * The seeds for the generations
     *
     * The seed value to vary the image generation. Only one seed per variation is allowed. If specified alongside with numVariations, the number of seeds must be equal to numVariations.
     */
    seeds?: Array<number>;
};

/**
 * ModelSpecificPayloadV3
 *
 * Model-specific payload parameters for V3 generation workflows.
 */
export type ModelSpecificPayloadV3 = {
    /**
     * The locale code used for image generations
     *
     * The locale code (following RFC 5646 format, e.g., 'en-US') will be used to generate content that is more relevant for user's country and language.
     */
    localeCode?: string;
};

/**
 * ReferenceBlobV3
 *
 * Reference blob for V3 API. Style Guide compliant: The 'source' property specifies the input location, and other properties like 'usage' are peers of 'source'.
 */
export type ReferenceBlobV3 = {
    /**
     * The source location of the reference image.
     */
    source: ReferenceBlobSourceV3;
    /**
     * The usage of the reference blob. Available options: 'general' for general reference.
     */
    usage?: ReferenceBlobUsageV3;
};

/**
 * ReferenceBlobSourceV3
 *
 * Source specification for a reference blob input asset. Input images must meet these requirements: file size must be 10 MB or less; image area must be between 512×512 and 2048×2048 pixels (inclusive); aspect ratio must be between 1:5 and 5:1 (inclusive).
 */
export type ReferenceBlobSourceV3 = {
    /**
     * Upload ID
     *
     * The ID of an asset previously uploaded to the Firefly Upload Image API.
     */
    uploadId?: string;
    /**
     * URL
     *
     * URL of the reference image. Presigned URLs are not supported for Image5; images must be uploaded to Adobe storage.
     */
    url?: string;
};

/**
 * ReferenceBlobUsageV3
 */
export type ReferenceBlobUsageV3 = 'general';

/**
 * Generating images from prompt
 */
export type GenerateImagesResponseV3 = {
    /**
     * Generate an image to being more photographic or more like art. Either <code>photo</code> or <code>art</code>.
     */
    contentClass?: ContentClassV3;
    /**
     * List of images
     *
     * Each image ID.
     */
    outputs: Array<OutputImageV3>;
    /**
     * The prompt had artists that were blocked
     *
     * The generated image does not comply with its full prompt if the prompt names artists that are blocked.
     */
    promptHasBlockedArtists?: boolean;
    /**
     * The prompt had denied words
     *
     * The generated image does not comply with its full prompt if the prompt contains blocked words or descriptions.
     */
    promptHasDeniedWords?: boolean;
    size: Size;
};

/**
 * Generate object composite from prompt request
 */
export type GenerateObjectCompositeRequestV3 = {
    contentClass?: ContentClassV3;
    /**
     * The image to expand. Use a URL or an <code>uploadID</code> as the source for the image. Firefly only allows these listed domains for input URLs in the request: <ul> <li><code>amazonaws.com</code></li> <li><code>windows.net</code></li> <li><code>dropboxusercontent.com</code></li> <li><code>storage.googleapis.com</code></li> </ul>.
     */
    image: InputImageV3;
    /**
     * Selected areas of a background image that Firefly uses to fill the source image.
     */
    mask?: BaseInputMaskV3;
    /**
     * The number of variations to generate
     *
     * Generate this number of variations. Defaults to the number of seed images, or to 1 if you do not specify seeds.
     */
    numVariations?: number;
    /**
     * The position of the source image after Firefly adjusts it. The value describes the horizontal and vertical placement and dimensions of the image in the output. Note you cannot use placement for source images when you also apply a mask image.
     */
    placement?: Placement;
    /**
     * The prompt
     *
     * A text prompt up to 1024 characters. The longer the prompt the better Firefly performs.
     */
    prompt: string;
    /**
     * The seed image for each variation
     *
     * Array of seed image IDs. These reference images help ensure consistent image generation across multiple API calls.
     *
     * If specified along with <code>numVariations</code>, the number of seeds must equal <code>numVariations</code>.
     */
    seeds?: Array<number>;
    /**
     * The size
     *
     * The desired width and height for the final image in pixels. The supported sizes for the output images are: <ul> <li>Square (1:1) - width 2048px, height 2048px </li> <li>Square (1:1) - width 1024px, height 1024px </li> <li>Landscape (4:3)  - width 2304px, height 1792px </li> <li>Portrait (3:4)  - width 1792px, height 2304px</li> <li>Widescreen (16:9) - width 2688px, height 1536px </li> <li>(7:4)  - width 1344px, height 768px </li> <li>(9:7) - width 1152px, height 896px </li> <li>(7:9) - width 896px, height 1152px</li> </ul>.
     */
    size?: Size;
    style?: StylesV3;
};

/**
 * Generate object composite from prompt response
 */
export type GenerateObjectCompositeResponseV3 = {
    contentClass?: ContentClassV3;
    /**
     * The list of images
     *
     * Each image ID.
     */
    outputs: Array<OutputImageV3>;
    /**
     * When you provide size as input, this value is the same.
     */
    size: Size;
};

/**
 * Generating similar images from a reference image
 */
export type GenerateSimilarImagesRequestV3 = {
    /**
     * Firefly will create similar variations. Use a URL or an <code>uploadID</code> as the source for the image. Firefly only allows these listed domains: <ul> <li><code>amazonaws.com</code></li> <li><code>windows.net</code></li> <li><code>dropboxusercontent.com</code></li> <li><code>storage.googleapis.com</code></li> </ul>.
     */
    image: BaseInputImageV3;
    /**
     * The number of variations
     *
     * Generate this number of variations. <code>numVariations</code> defaults to the number of seed images, or to 1 if you do not specify `seeds`.
     */
    numVariations?: number;
    /**
     * The seed image for each variation
     *
     * Array of seed image IDs. These reference images help ensure consistent image generation across multiple API calls. If specified along with <code>numVariations</code>, the number of seeds must equal <code>numVariations</code>.
     */
    seeds?: Array<number>;
    /**
     * The size
     *
     * The desired width and height for the final image in pixels. The supported sizes for the output images are: <ul> <li>Square (1:1) - width 2048px, height 2048px </li> <li>Square (1:1) - width 1024px, height 1024px </li> <li>Landscape (4:3)  - width 2304px, height 1792px </li> <li>Portrait (3:4)  - width 1792px, height 2304px</li> <li>Widescreen (16:9) - width 2688px, height 1536px </li> <li>(7:4)  - width 1344px, height 768px </li> <li>(9:7) - width 1152px, height 896px </li> <li>(7:9) - width 896px, height 1152px</li> </ul>.
     */
    size?: Size;
};

/**
 * Generating similar images response
 */
export type GenerateSimilarImagesResponseV3 = {
    /**
     * The list of images
     *
     * Each image ID.
     */
    outputs: Array<OutputImageV3>;
    /**
     * When you provide size as input, this value is the same.
     */
    size: Size;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InputImageV3
 */
export type InputImageV3 = {
    /**
     * Deprecated mask image
     *
     * This is a deprecated property. Use <code>mask</code> instead.
     *
     * @deprecated
     */
    mask?: PublicBinaryInputV3;
    /**
     * Source image that Firefly expands, fills, or uses to generate similar images.
     */
    source: PublicBinaryInputV3;
};

/**
 * InputMaskV3
 */
export type InputMaskV3 = {
    /**
     * Invert mask
     *
     * Invert mask is an optional boolen property, use <code>true</code> if you want take an image mask, invert it and apply it.
     */
    invert?: boolean;
    source: PublicBinaryInputV3;
};

/**
 * OutputImageV3
 */
export type OutputImageV3 = {
    image: PublicBinaryOutputV3;
    /**
     * Seed
     */
    seed: number;
};

/**
 * Placement
 */
export type Placement = {
    /**
     * Alignment
     *
     * Specify horizontal and vertical alignment. Possible values for horizontal=(center|left|right) and for vertical=(center|top|bottom).
     */
    alignment?: PlacementAlignment;
    /**
     * Margin values in target size
     *
     * Margin values in target size.
     */
    inset?: PlacementInset;
};

/**
 * PlacementAlignment
 */
export type PlacementAlignment = {
    horizontal?: AlignmentHorizontal;
    vertical?: AlignmentVertical;
};

/**
 * PlacementInset
 */
export type PlacementInset = {
    /**
     * Bottom Inset
     *
     * The space between bottom edge of the result image and bottom edge of the placed object image.
     */
    bottom?: number;
    /**
     * Left Inset
     *
     * The space between left edge of the result image and left edge of the placed object image.
     */
    left?: number;
    /**
     * Right Inset
     *
     * The space between right edge of the result image and right edge of the placed object image.
     */
    right?: number;
    /**
     * Top Inset
     *
     * The space between top edge of the result image and top edge of the placed object image.
     */
    top?: number;
};

/**
 * PublicBinaryInputV3
 */
export type PublicBinaryInputV3 = {
    /**
     * The upload ID
     *
     * The `uploadId` from the storage API response.
     */
    uploadId?: string;
    /**
     * The pre-signed URL
     *
     * The pre-signed URL of an uploaded file. Use a URL or an `uploadID` as the source for the image. Firefly only allows these listed domains in the request: <ul> <li><code>amazonaws.com</code></li> <li><code>windows.net</code></li> <li><code>dropboxusercontent.com</code></li> <li><code>storage.googleapis.com</code></li> </ul>.
     */
    url?: string;
};

/**
 * PublicBinaryOutputV3
 */
export type PublicBinaryOutputV3 = {
    /**
     * The pre-signed URL
     *
     * This URL expires in one hour.
     */
    url?: string;
};

export type Size = {
    height: number;
    width: number;
};

export type StructureImageReferenceV3 = {
    source?: PublicBinaryInputV3;
};

export type StructureReferenceV3 = {
    imageReference?: StructureImageReferenceV3;
    /**
     * Adherence Threshold
     *
     * Control how strictly Firefly adheres to the reference image when it generates the image variations. 0 means no adherence. 100 means full adherence.
     */
    strength?: number;
};

export type StylesImageReferenceV3 = {
    source?: PublicBinaryInputV3;
};

export type StylesV3 = {
    imageReference?: StylesImageReferenceV3;
    /**
     * The style presets. Specify an ID for a style of image to generate.
     */
    presets?: Array<string>;
    /**
     * How strictly Firefly should adhere to the style you provide. 0 means no adherence. 100 means full adherence.
     */
    strength?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ValidationErrorMessage
 */
export type ValidationErrorMessage = {
    /**
     * Ctx
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Loc
     */
    loc: Array<number | string>;
    /**
     * Msg
     */
    msg: string;
    /**
     * Type
     */
    type: string;
};

/**
 * Generating video from prompt
 */
export type GenerateVideoRequestV3 = {
    /**
     * The constant rate factor for encoding video. 0 indicates a lossless generation, with the highest quality and largest file size. 63 indicates the worst quality generation with the smallest file size. The suggested value range is 17-23.
     */
    bitRateFactor?: number;
    /**
     * The details of the image used as a keyframe for the generated video. Provided images are used as a first frame or final frame to guide the video generation.
     */
    image?: InputImageVideoV3;
    /**
     * The prompt used to generate the video. The longer the prompt, the better.
     */
    prompt?: string;
    /**
     * The seed reference value. Currently only 1 seed is supported.
     */
    seeds?: [
        number
    ];
    /**
     * The dimensions of the generated video.
     */
    sizes?: Array<ClinetoSize>;
    /**
     * The camera and shot control settings.
     */
    videoSettings?: VideoSettingsV3;
};

/**
 * ClinetoSize
 */
export type ClinetoSize = {
    /**
     * The height of the output video.
     */
    height: number;
    /**
     * The width of the output video.
     */
    width: number;
};

/**
 * InputImageVideoV3
 */
export type InputImageVideoV3 = {
    /**
     * The details about the keyframe images used for the video generation.
     */
    conditions?: Array<ImageConditionV3>;
};

/**
 * ImageConditionV3
 */
export type ImageConditionV3 = {
    /**
     * Details about the timeline placement of the image.
     */
    placement: PlacementStart;
    /**
     * The source details of the image.
     */
    source: PublicBinaryInputV3;
};

/**
 * PlacementStart
 */
export type PlacementStart = {
    /**
     * The position of the image on the timeline for the generated video, 0 being the first frame and 1 being the last frame.
     */
    position: number;
};

export type VideoSettingsV3 = {
    /**
     * The camera motion control.
     */
    cameraMotion?: CameraMotion;
    /**
     * The style of the generated video.
     */
    promptStyle?: VideoPromptStyle;
    /**
     * The shot angle control.
     */
    shotAngle?: ShotAngle;
    /**
     * The shot size control.
     */
    shotSize?: ShotSize;
};

/**
 * CameraMotion
 */
export type CameraMotion = 'camera pan left' | 'camera pan right' | 'camera zoom in' | 'camera zoom out' | 'camera tilt up' | 'camera tilt down' | 'camera locked down' | 'camera handheld';

/**
 * VideoPromptStyle
 */
export type VideoPromptStyle = 'anime' | '3d' | 'fantasy' | 'cinematic' | 'claymation' | 'line art' | 'stop motion' | '2d' | 'vector art' | 'black and white';

/**
 * ShotAngle
 */
export type ShotAngle = 'aerial shot' | 'eye_level shot' | 'high angle shot' | 'low angle shot' | 'top-down shot';

/**
 * ShotSize
 */
export type ShotSize = 'close-up shot' | 'extreme close-up' | 'medium shot' | 'long shot' | 'extreme long shot';

/**
 * VideoResult
 */
export type VideoResult = {
    /**
     * The pre-signed URL for the generated video file.
     */
    url: string;
};

/**
 * VideoOutput
 */
export type VideoOutput = {
    /**
     * The seed value used for generating this video output.
     */
    seed: number;
    video: VideoResult;
};

/**
 * AsyncResult
 */
export type AsyncResult = {
    size: ClinetoSize;
    /**
     * Array of generated video outputs.
     */
    outputs: Array<VideoOutput>;
};

/**
 * AsyncResponseV3
 */
export type AsyncResponseV3 = {
    /**
     * Cancel URL
     *
     * A URL to cancel the job.
     */
    cancelUrl?: string;
    /**
     * Job ID
     *
     * The ID for the asynchronous job.
     */
    jobId: string;
    /**
     * The progress of the running job. The value is the percentage of the job that has been completed.
     */
    progress?: number;
    /**
     * The result of the completed job.
     */
    result?: AsyncResult;
    /**
     * Status
     *
     * The status of the job.
     */
    status?: string;
    /**
     * Status URL
     *
     * A URL to show the status of the current job.
     */
    statusUrl?: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * The type of error that occurred.
     */
    reason?: string;
    /**
     * A message describing the error.
     */
    message?: string;
};

/**
 * CustomModelsFF3pInfo
 */
export type CustomModelsFf3pInfo = {
    /**
     * List of custom models.
     */
    custom_models?: Array<CustomModelFf3pInfo>;
    _links?: Links;
    /**
     * Total number of results for the query.
     */
    total_count?: number;
};

/**
 * CustomModelFF3pInfo
 *
 * Custom Model info.
 */
export type CustomModelFf3pInfo = {
    /**
     * Custom Model version.
     */
    version?: string;
    /**
     * Custom Model name.
     */
    assetName?: string;
    /**
     * The storage amount used.
     */
    size?: number;
    /**
     * An identifier for the specific version of the asset.
     */
    etag?: string;
    /**
     * The training mode of the model. When this is 'subject', the 'conceptId' must be mentioned in the prompt.
     */
    trainingMode?: 'subject' | 'style';
    /**
     * A unique identifier for the asset.
     */
    assetId?: string;
    /**
     * The media type specific to the asset.
     */
    mediaType?: string;
    createdDate?: string;
    modifiedDate?: string;
    /**
     * Status for the asset. The 'unpublished' value applies when an asset is published and then subsequently revoked.
     */
    publishedState?: 'never' | 'published' | 'unpublished';
    /**
     * The underlying GenAI model used to train the Custom Model.
     */
    baseModel?: BaseModel;
    /**
     * Example string provided by the custom model's trainer.
     */
    samplePrompt?: string;
    /**
     * The asset name provided by the user, mapped from the name of the training set library.
     */
    displayName?: string;
    /**
     * When 'trainingMode' is 'subject', this string specifies the subject for the prompt.
     */
    conceptId?: string;
};

/**
 * BaseModel
 */
export type BaseModel = {
    /**
     * The name of the base model.
     */
    name?: string;
    /**
     * The version of the base model.
     */
    version?: string;
};

/**
 * Links
 *
 * Collection of hypermedia links for pagination, navigation, etc.
 */
export type Links = {
    page?: Link;
    next?: Link;
};

/**
 * Link
 *
 * Standard representation of a hypermedia link.
 */
export type Link = {
    /**
     * Fully qualified URI or relative path for the link.
     */
    href?: string;
    /**
     * Describes the relationship or function of the link (e.g. `next`, `page`, `self`).
     */
    rel?: string;
    /**
     * Indicates whether or not the `href` supports URI template parameters.
     */
    templated?: boolean;
};

/**
 * PageSpec
 *
 * List Page.
 */
export type PageSpec = {
    /**
     * List order-by.
     */
    orderBy?: string;
    /**
     * List start position.
     */
    start?: string;
    /**
     * List next position.
     */
    next?: string;
    /**
     * List page size.
     */
    count?: number;
    /**
     * List page type.
     */
    type?: string;
    /**
     * List page property.
     */
    property?: string;
};

/**
 * StorageImageResponse
 *
 * Storage response.
 */
export type StorageImageResponse = {
    /**
     * Array of objects containing asset ID.
     */
    images?: Array<StorageImage>;
};

/**
 * StorageImage
 *
 * Source image.
 */
export type StorageImage = {
    /**
     * ID associated with the asset. The id will be valid for 7 days from the date of creation.
     */
    id: string;
};

/**
 * ErrorBody
 */
export type ErrorBody = {
    /**
     * Error message.
     */
    message?: string;
    /**
     * Associated error code.
     */
    error_code?: string;
};

export type GenerateImagesV3AsyncData = {
    body: GenerateImagesRequestV3;
    headers?: {
        /**
         * Specify the Firefly model version to use for the image generation. When a custom model is used, a `customModelId` must also be passed in the request body.
         */
        'x-model-version'?: 'image3' | 'image3_custom' | 'image4_standard' | 'image4_ultra' | 'image4_custom';
    };
    path?: never;
    query?: never;
    url: '/v3/images/generate-async';
};

export type GenerateImagesV3AsyncErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: ApiError;
    /**
     * Request Timeout
     */
    408: ApiError;
    /**
     * Request Entity Too Large
     */
    413: string;
    /**
     * Unsupported Media Type
     */
    415: ApiError;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiError;
    /**
     * Internal Server Error
     */
    500: ApiError;
};

export type GenerateImagesV3AsyncError = GenerateImagesV3AsyncErrors[keyof GenerateImagesV3AsyncErrors];

export type GenerateImagesV3AsyncResponses = {
    /**
     * Accepted
     */
    202: AsyncAcceptResponseV3;
};

export type GenerateImagesV3AsyncResponse = GenerateImagesV3AsyncResponses[keyof GenerateImagesV3AsyncResponses];

export type FireflyImageV5GenerateAsyncV4Data = {
    body: ImageGenerateRequestV3;
    headers: {
        /**
         * The model version to use for image generation.
         */
        'x-model-version': 'image5';
    };
    path?: never;
    query?: never;
    url: '/v4/images/generate-async';
};

export type FireflyImageV5GenerateAsyncV4Errors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden
     */
    403: ApiError;
    /**
     * Requested Resource Was Not Found
     */
    404: ApiError;
    /**
     * Request Timeout
     */
    408: ApiError;
    /**
     * Conflict
     */
    409: ApiError;
    /**
     * Gone
     */
    410: ApiError;
    /**
     * Unsupported Media Type
     */
    415: ApiError;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiError;
    /**
     * Unavailable For Legal Reasons
     */
    451: ContentPolicyErrorResponse;
    /**
     * Client Closed Request
     */
    499: ApiError;
    /**
     * Internal Server Error
     */
    500: ApiError;
    /**
     * Not Implemented
     */
    501: ApiError;
    /**
     * Service Unavailable
     */
    503: ApiError;
};

export type FireflyImageV5GenerateAsyncV4Error = FireflyImageV5GenerateAsyncV4Errors[keyof FireflyImageV5GenerateAsyncV4Errors];

export type FireflyImageV5GenerateAsyncV4Responses = {
    /**
     * Success
     */
    200: AsyncTaskResponse;
};

export type FireflyImageV5GenerateAsyncV4Response = FireflyImageV5GenerateAsyncV4Responses[keyof FireflyImageV5GenerateAsyncV4Responses];

export type GenerateSimilarImagesV3AsyncData = {
    body: GenerateSimilarImagesRequestV3;
    headers?: {
        /**
         * Specify the Firefly model version to use for the image generation.
         */
        'x-model-version'?: 'image3' | 'image4_standard' | 'image4_ultra';
    };
    path?: never;
    query?: never;
    url: '/v3/images/generate-similar-async';
};

export type GenerateSimilarImagesV3AsyncErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: ApiError;
    /**
     * Request Timeout
     */
    408: ApiError;
    /**
     * Request Entity Too Large
     */
    413: string;
    /**
     * Unsupported Media Type
     */
    415: ApiError;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiError;
    /**
     * Internal Server Error
     */
    500: ApiError;
};

export type GenerateSimilarImagesV3AsyncError = GenerateSimilarImagesV3AsyncErrors[keyof GenerateSimilarImagesV3AsyncErrors];

export type GenerateSimilarImagesV3AsyncResponses = {
    /**
     * Accepted
     */
    202: AsyncAcceptResponseV3;
};

export type GenerateSimilarImagesV3AsyncResponse = GenerateSimilarImagesV3AsyncResponses[keyof GenerateSimilarImagesV3AsyncResponses];

export type ExpandImagesV3AsyncData = {
    body: ExpandImageRequestV3;
    path?: never;
    query?: never;
    url: '/v3/images/expand-async';
};

export type ExpandImagesV3AsyncErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: ApiError;
    /**
     * Request Timeout
     */
    408: ApiError;
    /**
     * Request Entity Too Large
     */
    413: string;
    /**
     * Unsupported Media Type
     */
    415: ApiError;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiError;
    /**
     * Internal Server Error
     */
    500: ApiError;
};

export type ExpandImagesV3AsyncError = ExpandImagesV3AsyncErrors[keyof ExpandImagesV3AsyncErrors];

export type ExpandImagesV3AsyncResponses = {
    /**
     * Accepted
     */
    202: AsyncAcceptResponseV3;
};

export type ExpandImagesV3AsyncResponse = ExpandImagesV3AsyncResponses[keyof ExpandImagesV3AsyncResponses];

export type FillImagesV3AsyncData = {
    body: FillImageRequestV3;
    path?: never;
    query?: never;
    url: '/v3/images/fill-async';
};

export type FillImagesV3AsyncErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: ApiError;
    /**
     * Request Timeout
     */
    408: ApiError;
    /**
     * Request Entity Too Large
     */
    413: string;
    /**
     * Unsupported Media Type
     */
    415: ApiError;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiError;
    /**
     * Internal Server Error
     */
    500: ApiError;
};

export type FillImagesV3AsyncError = FillImagesV3AsyncErrors[keyof FillImagesV3AsyncErrors];

export type FillImagesV3AsyncResponses = {
    /**
     * Accepted
     */
    202: AsyncAcceptResponseV3;
};

export type FillImagesV3AsyncResponse = FillImagesV3AsyncResponses[keyof FillImagesV3AsyncResponses];

export type GenerateObjectCompositeV3AsyncData = {
    body: GenerateObjectCompositeRequestV3;
    path?: never;
    query?: never;
    url: '/v3/images/generate-object-composite-async';
};

export type GenerateObjectCompositeV3AsyncErrors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: ApiError;
    /**
     * Request Timeout
     */
    408: ApiError;
    /**
     * Unsupported Media Type
     */
    415: ApiError;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiError;
    /**
     * Internal Server Error
     */
    500: ApiError;
};

export type GenerateObjectCompositeV3AsyncError = GenerateObjectCompositeV3AsyncErrors[keyof GenerateObjectCompositeV3AsyncErrors];

export type GenerateObjectCompositeV3AsyncResponses = {
    /**
     * Accepted
     */
    202: AsyncAcceptResponseV3;
};

export type GenerateObjectCompositeV3AsyncResponse = GenerateObjectCompositeV3AsyncResponses[keyof GenerateObjectCompositeV3AsyncResponses];

export type PreciseCompositeData = {
    body: PreciseCompositeRequest;
    headers: {
        /**
         * Must be application/json for JSON request body.
         */
        'content-type': 'application/json';
    };
    path?: never;
    query?: never;
    url: '/v3/images/precise-composite';
};

export type PreciseCompositeErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorGeneric;
    /**
     * Unauthorized
     */
    401: ApiErrorGeneric;
    /**
     * Forbidden
     */
    403: ApiErrorGeneric;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiErrorGeneric;
    /**
     * Unavailable For Legal Reasons
     */
    451: ContentPolicyErrorResponse;
    /**
     * Internal Server Error
     */
    500: ApiErrorGeneric;
    /**
     * Service Unavailable
     */
    503: ApiErrorGeneric;
};

export type PreciseCompositeError = PreciseCompositeErrors[keyof PreciseCompositeErrors];

export type PreciseCompositeResponses = {
    /**
     * Accepted
     */
    202: AsyncJobResponse;
};

export type PreciseCompositeResponse = PreciseCompositeResponses[keyof PreciseCompositeResponses];

export type AdaptiveCompositeData = {
    body: AdaptiveCompositeRequest;
    headers: {
        /**
         * Must be application/json for JSON request body.
         */
        'content-type': 'application/json';
    };
    path?: never;
    query?: never;
    url: '/v3/images/adaptive-composite';
};

export type AdaptiveCompositeErrors = {
    /**
     * Bad Request
     */
    400: ApiErrorGeneric;
    /**
     * Unauthorized
     */
    401: ApiErrorGeneric;
    /**
     * Forbidden
     */
    403: ApiErrorGeneric;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiErrorGeneric;
    /**
     * Unavailable For Legal Reasons
     */
    451: ContentPolicyErrorResponse;
    /**
     * Internal Server Error
     */
    500: ApiErrorGeneric;
    /**
     * Service Unavailable
     */
    503: ApiErrorGeneric;
};

export type AdaptiveCompositeError = AdaptiveCompositeErrors[keyof AdaptiveCompositeErrors];

export type AdaptiveCompositeResponses = {
    /**
     * Accepted
     */
    202: AsyncJobResponse;
};

export type AdaptiveCompositeResponse = AdaptiveCompositeResponses[keyof AdaptiveCompositeResponses];

export type CreativeUpsamplerV3AsyncData = {
    body: CreativeUpsamplerRequestV3;
    headers?: {
        /**
         * Model version for the upscale operation. Use creative_upsampler_v1.
         */
        'x-model-version'?: string;
    };
    path?: never;
    query?: never;
    url: '/v3/images/upscale';
};

export type CreativeUpsamplerV3AsyncErrors = {
    /**
     * Bad Request
     */
    400: ValidationErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorGeneric;
    /**
     * Forbidden
     */
    403: ApiErrorGeneric;
    /**
     * Requested Resource Was Not Found
     */
    404: ApiErrorGeneric;
    /**
     * Input Validation Error
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiErrorGeneric;
    /**
     * Internal Server Error
     */
    500: ApiErrorGeneric;
    /**
     * Service Unavailable
     */
    503: ApiErrorGeneric;
};

export type CreativeUpsamplerV3AsyncError = CreativeUpsamplerV3AsyncErrors[keyof CreativeUpsamplerV3AsyncErrors];

export type CreativeUpsamplerV3AsyncResponses = {
    /**
     * Accepted
     */
    202: CreativeUpscaleAcceptResponseV3;
};

export type CreativeUpsamplerV3AsyncResponse = CreativeUpsamplerV3AsyncResponses[keyof CreativeUpsamplerV3AsyncResponses];

export type GenerateVideoV3Data = {
    /**
     * The request body for the video generation.
     */
    body: GenerateVideoRequestV3;
    headers: {
        /**
         * Specify the Firefly model version to use for the video generation.
         */
        'x-model-version': 'video1_standard';
    };
    path?: never;
    query?: never;
    url: '/v3/videos/generate';
};

export type GenerateVideoV3Errors = {
    /**
     * Bad Request
     */
    400: ApiError;
    /**
     * Forbidden
     */
    403: ApiError;
    /**
     * Request Timeout
     */
    408: ApiError;
    /**
     * Unsupported Media Type
     */
    415: ApiError;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiError;
    /**
     * Internal Server Error
     */
    500: ApiError;
};

export type GenerateVideoV3Error = GenerateVideoV3Errors[keyof GenerateVideoV3Errors];

export type GenerateVideoV3Responses = {
    /**
     * Accepted
     */
    202: AsyncAcceptResponseV3;
};

export type GenerateVideoV3Response = GenerateVideoV3Responses[keyof GenerateVideoV3Responses];

export type GetCustomModelsData = {
    body?: never;
    headers: {
        /**
         * A user token referencing the user's individual account, obtained using their credentials. The user token must be preceded by `Bearer`.
         */
        'x-user-token'?: string;
        /**
         * A unique request identifier defined by you. This is used by Adobe Support to trace the request in logs. This header is automatically generated by the server if not explicitly set.
         */
        'x-request-id': string;
    };
    path?: never;
    query?: {
        /**
         * A sorting option for the response list. For a reverse sort, use `-` (e.g., `-modifiedDate`). Multi-vector sorting is not currently supported.
         */
        sortBy?: 'assetName' | 'createdDate' | 'modifiedDate';
        /**
         * The first result to include in a paginated response. Required if a `limit` is specified.
         */
        start?: string;
        /**
         * The number of custom models to return in a paginated response.
         */
        limit?: string;
        /**
         * This filters custom models by published state.
         */
        publishedState?: 'all' | 'ready' | 'published' | 'unpublished' | 'queued' | 'training' | 'failed' | 'cancelled';
    };
    url: '/v3/custom-models';
};

export type GetCustomModelsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Acceptable
     */
    406: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type GetCustomModelsError = GetCustomModelsErrors[keyof GetCustomModelsErrors];

export type GetCustomModelsResponses = {
    /**
     * Success
     */
    200: CustomModelsFf3pInfo;
};

export type GetCustomModelsResponse = GetCustomModelsResponses[keyof GetCustomModelsResponses];

export type StorageImageV2Data = {
    /**
     * The PNG, JPEG, WEBP, TIFF, or JXL image to be stored (binary data). The maximum file size supported for uploading an image is 15MB.
     */
    body: Blob | File;
    path?: never;
    query?: never;
    url: '/v2/storage/image';
};

export type StorageImageV2Errors = {
    /**
     * Bad Request
     */
    400: ErrorBody;
    /**
     * Unauthorized
     */
    401: ErrorBody;
    /**
     * Forbidden
     */
    403: ErrorBody;
    /**
     * Too Many Requests
     */
    429: ErrorBody;
    /**
     * Unavailable for Legal Reasons
     */
    451: ContentPolicyErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorBody;
};

export type StorageImageV2Error = StorageImageV2Errors[keyof StorageImageV2Errors];

export type StorageImageV2Responses = {
    /**
     * Success
     */
    200: StorageImageResponse;
};

export type StorageImageV2Response = StorageImageV2Responses[keyof StorageImageV2Responses];

export type JobResultV3Data = {
    body?: never;
    path: {
        /**
         * Job ID
         *
         * The job ID or URN returned in async response links.
         */
        jobId: string;
    };
    query?: never;
    url: '/v3/status/{jobId}';
};

export type JobResultV3Errors = {
    /**
     * Unauthorized
     */
    401: ApiErrorGeneric;
    /**
     * Forbidden
     */
    403: ApiErrorGeneric;
    /**
     * Requested Resource Was Not Found
     */
    404: ApiErrorGeneric;
    /**
     * Unprocessable Entity
     */
    422: ValidationErrorResponse;
    /**
     * Too Many Requests
     */
    429: ApiErrorGeneric;
    /**
     * Internal Server Error
     */
    500: ApiErrorGeneric;
    /**
     * Service Unavailable
     */
    503: ApiErrorGeneric;
};

export type JobResultV3Error = JobResultV3Errors[keyof JobResultV3Errors];

export type JobResultV3Responses = {
    /**
     * Success
     */
    200: JobResponse;
};

export type JobResultV3Response = JobResultV3Responses[keyof JobResultV3Responses];

export type CancelJobV4Data = {
    body?: never;
    path: {
        /**
         * Job ID
         *
         * The job ID or URN returned in async response links.
         */
        jobId: string;
    };
    query?: never;
    url: '/v3/cancel/{jobId}';
};

export type CancelJobV4Errors = {
    /**
     * Unauthorized
     */
    401: ApiErrorGeneric;
    /**
     * Forbidden
     */
    403: ApiErrorGeneric;
    /**
     * Requested Resource Was Not Found
     */
    404: ApiErrorGeneric;
    /**
     * Conflict
     */
    409: ApiErrorGeneric;
    /**
     * Gone
     */
    410: ApiErrorGeneric;
    /**
     * Too Many Requests
     */
    429: ApiErrorGeneric;
    /**
     * Internal Server Error
     */
    500: ApiErrorGeneric;
    /**
     * Service Unavailable
     */
    503: ApiErrorGeneric;
};

export type CancelJobV4Error = CancelJobV4Errors[keyof CancelJobV4Errors];

export type CancelJobV4Responses = {
    /**
     * Job Cancelled
     */
    200: unknown;
};
